import Foundation

final class FragranceDatabase {
    static let shared = FragranceDatabase()

    let fragrances: [Fragrance]

    private init() {
        fragrances = Self.buildDatabase()
    }

    func fragrance(byId id: String) -> Fragrance? {
        fragrances.first { $0.id == id }
    }

    func fragrances(forRegion region: FragranceRegion) -> [Fragrance] {
        fragrances.filter { $0.region == region }
    }

    func fragrances(forTier tier: PriceTier) -> [Fragrance] {
        fragrances.filter { $0.priceTier == tier }
    }

    func fragrances(forAccord accord: AccordFamily) -> [Fragrance] {
        fragrances.filter { $0.accords.contains(accord) }
    }

    // MARK: - Convenience Color Builders

    // Hue ranges: Red=0/360, Orange=30, Yellow=60, Green=120, Cyan=180, Blue=240, Purple=270, Pink=330
    private static func warmColors(weight: Double = 1.0) -> [ColorAssociation] {
        [ColorAssociation(hueMin: 0, hueMax: 50, weight: weight),     // red-orange
         ColorAssociation(hueMin: 330, hueMax: 360, weight: weight)]   // pink-red
    }

    private static func coolColors(weight: Double = 1.0) -> [ColorAssociation] {
        [ColorAssociation(hueMin: 180, hueMax: 270, weight: weight)]   // cyan-blue-purple
    }

    private static func greenColors(weight: Double = 1.0) -> [ColorAssociation] {
        [ColorAssociation(hueMin: 80, hueMax: 160, weight: weight)]
    }

    private static func goldColors(weight: Double = 1.0) -> [ColorAssociation] {
        [ColorAssociation(hueMin: 35, hueMax: 55, satMin: 0.3, weight: weight)]
    }

    private static func darkColors(weight: Double = 1.0) -> [ColorAssociation] {
        [ColorAssociation(hueMin: 0, hueMax: 360, satMin: 0.0, satMax: 1.0, briMin: 0.0, briMax: 0.35, weight: weight)]
    }

    private static func neutralColors(weight: Double = 1.0) -> [ColorAssociation] {
        [ColorAssociation(hueMin: 0, hueMax: 360, satMin: 0.0, satMax: 0.15, briMin: 0.3, briMax: 0.8, weight: weight)]
    }

    private static func brightColors(weight: Double = 1.0) -> [ColorAssociation] {
        [ColorAssociation(hueMin: 0, hueMax: 360, satMin: 0.4, briMin: 0.7, weight: weight)]
    }

    private static func pinkColors(weight: Double = 1.0) -> [ColorAssociation] {
        [ColorAssociation(hueMin: 300, hueMax: 350, satMin: 0.2, weight: weight)]
    }

    private static func purpleColors(weight: Double = 1.0) -> [ColorAssociation] {
        [ColorAssociation(hueMin: 260, hueMax: 310, weight: weight)]
    }

    private static func whiteColors(weight: Double = 1.0) -> [ColorAssociation] {
        [ColorAssociation(hueMin: 0, hueMax: 360, satMin: 0.0, satMax: 0.1, briMin: 0.85, briMax: 1.0, weight: weight)]
    }

    private static func earthyColors(weight: Double = 1.0) -> [ColorAssociation] {
        [ColorAssociation(hueMin: 20, hueMax: 45, satMin: 0.2, satMax: 0.6, briMin: 0.2, briMax: 0.6, weight: weight)]
    }

    // MARK: - Database Builder

    private static func buildDatabase() -> [Fragrance] {
        var all = [Fragrance]()
        all.append(contentsOf: westernFragrances())
        all.append(contentsOf: germanFragrances())
        all.append(contentsOf: mexicanFragrances())
        all.append(contentsOf: brazilianFragrances())
        all.append(contentsOf: frenchFragrances())
        return all
    }

    // MARK: - Western / General (20 scents)

    private static func westernFragrances() -> [Fragrance] {
        [
            Fragrance(
                id: "w_sauvage",
                name: "Sauvage",
                house: "Dior",
                accords: [.aromatic, .fresh, .spicy],
                topNotes: ["Calabrian Bergamot", "Pepper"],
                heartNotes: ["Sichuan Pepper", "Lavender", "Geranium"],
                baseNotes: ["Ambroxan", "Cedar", "Labdanum"],
                moodTags: [.bold, .confident, .energetic],
                colorAssociations: coolColors() + darkColors(weight: 0.7),
                seasonality: [.spring, .summer, .fall],
                region: .western,
                priceTier: .mid,
                gender: .masculine,
                amazonASIN: "B01M65FHWI",
                iconName: "wind",
                shortDescription: "Raw, magnetic freshness with a wild edge"
            ),
            Fragrance(
                id: "w_chanelno5",
                name: "No. 5",
                house: "Chanel",
                accords: [.floral, .powdery, .woody],
                topNotes: ["Aldehydes", "Ylang-Ylang", "Neroli"],
                heartNotes: ["Rose", "Jasmine", "Iris"],
                baseNotes: ["Sandalwood", "Vanilla", "Vetiver"],
                moodTags: [.elegant, .sophisticated, .vintage],
                colorAssociations: goldColors() + whiteColors(weight: 0.8) + pinkColors(weight: 0.5),
                seasonality: [.spring, .fall, .winter],
                region: .western,
                priceTier: .luxury,
                gender: .feminine,
                amazonASIN: "B000C1V0LG",
                iconName: "sparkles",
                shortDescription: "Timeless floral elegance, the icon of luxury"
            ),
            Fragrance(
                id: "w_bleudechanel",
                name: "Bleu de Chanel",
                house: "Chanel",
                accords: [.woody, .aromatic, .citrus],
                topNotes: ["Grapefruit", "Lemon", "Mint"],
                heartNotes: ["Ginger", "Nutmeg", "Jasmine"],
                baseNotes: ["Sandalwood", "Cedar", "Incense"],
                moodTags: [.sophisticated, .confident, .elegant],
                colorAssociations: coolColors() + darkColors(weight: 0.6),
                seasonality: [.spring, .summer, .fall, .winter],
                region: .western,
                priceTier: .luxury,
                gender: .masculine,
                amazonASIN: "B01MFFH8HU",
                iconName: "circle.fill",
                shortDescription: "Refined woody-aromatic with understated power"
            ),
            Fragrance(
                id: "w_blackopium",
                name: "Black Opium",
                house: "Yves Saint Laurent",
                accords: [.oriental, .gourmand, .floral],
                topNotes: ["Pink Pepper", "Orange Blossom", "Pear"],
                heartNotes: ["Coffee", "Jasmine", "Bitter Almond"],
                baseNotes: ["Vanilla", "Patchouli", "Cedar"],
                moodTags: [.sensual, .bold, .mysterious],
                colorAssociations: darkColors() + purpleColors(weight: 0.7),
                seasonality: [.fall, .winter],
                region: .western,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: "B00N5TSGI4",
                iconName: "moon.stars.fill",
                shortDescription: "Addictive coffee-vanilla with dark glamour"
            ),
            Fragrance(
                id: "w_oudwood",
                name: "Oud Wood",
                house: "Tom Ford",
                accords: [.woody, .oriental, .spicy],
                topNotes: ["Oud", "Rosewood", "Cardamom"],
                heartNotes: ["Sandalwood", "Vetiver", "Tonka Bean"],
                baseNotes: ["Amber", "Synthetic Oud"],
                moodTags: [.opulent, .sophisticated, .warm],
                colorAssociations: earthyColors() + darkColors(weight: 0.8) + goldColors(weight: 0.6),
                seasonality: [.fall, .winter],
                region: .western,
                priceTier: .luxury,
                gender: .unisex,
                amazonASIN: "B0042AYPHY",
                iconName: "leaf.fill",
                shortDescription: "Smoky, exotic oud wrapped in creamy sandalwood"
            ),
            Fragrance(
                id: "w_englishpear",
                name: "English Pear & Freesia",
                house: "Jo Malone",
                accords: [.fruity, .floral, .fresh],
                topNotes: ["King William Pear", "Melon"],
                heartNotes: ["Freesia"],
                baseNotes: ["Patchouli", "Amber", "Musk"],
                moodTags: [.elegant, .fresh, .playful],
                colorAssociations: greenColors() + whiteColors(weight: 0.7) + brightColors(weight: 0.5),
                seasonality: [.spring, .summer, .fall],
                region: .western,
                priceTier: .luxury,
                gender: .feminine,
                amazonASIN: "B005DM426K",
                iconName: "leaf.arrow.triangle.circlepath",
                shortDescription: "Crisp, dewy pear with delicate freesia"
            ),
            Fragrance(
                id: "w_eros",
                name: "Eros",
                house: "Versace",
                accords: [.fresh, .aromatic, .woody],
                topNotes: ["Mint", "Green Apple", "Lemon"],
                heartNotes: ["Tonka Bean", "Ambroxan", "Geranium"],
                baseNotes: ["Vanilla", "Vetiver", "Oak Moss", "Cedar"],
                moodTags: [.bold, .energetic, .confident],
                colorAssociations: coolColors() + brightColors(weight: 0.6),
                seasonality: [.spring, .summer],
                region: .western,
                priceTier: .mid,
                gender: .masculine,
                amazonASIN: "B009ORIA88",
                iconName: "bolt.fill",
                shortDescription: "Fresh, vibrant power inspired by Greek mythology"
            ),
            Fragrance(
                id: "w_good_girl",
                name: "Good Girl",
                house: "Carolina Herrera",
                accords: [.oriental, .floral, .gourmand],
                topNotes: ["Almond", "Coffee", "Bergamot"],
                heartNotes: ["Tuberose", "Jasmine", "Orange Blossom"],
                baseNotes: ["Cacao", "Tonka Bean", "Sandalwood"],
                moodTags: [.sensual, .bold, .sophisticated],
                colorAssociations: darkColors() + pinkColors(weight: 0.6) + goldColors(weight: 0.5),
                seasonality: [.fall, .winter],
                region: .western,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: "B01LY04MRY",
                iconName: "star.fill",
                shortDescription: "Duality of light tuberose and dark cacao"
            ),
            Fragrance(
                id: "w_acquadigio",
                name: "Acqua di Gio",
                house: "Giorgio Armani",
                accords: [.aquatic, .fresh, .citrus],
                topNotes: ["Calabrian Bergamot", "Neroli", "Green Tangerine"],
                heartNotes: ["Marine Notes", "Rosemary", "Jasmine"],
                baseNotes: ["White Musk", "Cedar", "Patchouli"],
                moodTags: [.fresh, .serene, .natural],
                colorAssociations: coolColors() + whiteColors(weight: 0.6) + greenColors(weight: 0.4),
                seasonality: [.spring, .summer],
                region: .western,
                priceTier: .mid,
                gender: .masculine,
                amazonASIN: "B000E7WY2K",
                iconName: "water.waves",
                shortDescription: "Crystal-clear Mediterranean freshness"
            ),
            Fragrance(
                id: "w_la_vie_est_belle",
                name: "La Vie Est Belle",
                house: "Lancome",
                accords: [.gourmand, .floral, .oriental],
                topNotes: ["Black Currant", "Pear"],
                heartNotes: ["Iris", "Jasmine", "Orange Blossom"],
                baseNotes: ["Praline", "Vanilla", "Patchouli", "Tonka Bean"],
                moodTags: [.romantic, .warm, .elegant],
                colorAssociations: pinkColors() + goldColors(weight: 0.7) + warmColors(weight: 0.5),
                seasonality: [.fall, .winter, .spring],
                region: .western,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: "B009629YYA",
                iconName: "heart.fill",
                shortDescription: "Joyful iris-praline sweetness, a modern classic"
            ),
            Fragrance(
                id: "w_aventus",
                name: "Aventus",
                house: "Creed",
                accords: [.fruity, .woody, .fresh],
                topNotes: ["Pineapple", "Bergamot", "Black Currant", "Apple"],
                heartNotes: ["Birch", "Patchouli", "Moroccan Jasmine", "Rose"],
                baseNotes: ["Musk", "Oak Moss", "Ambergris", "Vanilla"],
                moodTags: [.confident, .bold, .sophisticated],
                colorAssociations: darkColors() + greenColors(weight: 0.5) + goldColors(weight: 0.6),
                seasonality: [.spring, .summer, .fall],
                region: .western,
                priceTier: .luxury,
                gender: .masculine,
                amazonASIN: "B004LDA71O",
                iconName: "crown.fill",
                shortDescription: "Legendary fruity-smoky power fragrance"
            ),
            Fragrance(
                id: "w_flowerbomb",
                name: "Flowerbomb",
                house: "Viktor & Rolf",
                accords: [.floral, .oriental, .gourmand],
                topNotes: ["Tea", "Bergamot"],
                heartNotes: ["Jasmine", "Rose", "Freesia", "Orchid"],
                baseNotes: ["Patchouli", "Musk", "Vanilla"],
                moodTags: [.romantic, .opulent, .warm],
                colorAssociations: pinkColors() + warmColors(weight: 0.7),
                seasonality: [.fall, .winter, .spring],
                region: .western,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: "B0012RO626",
                iconName: "camera.macro",
                shortDescription: "Explosive floral bouquet with vanilla warmth"
            ),
            Fragrance(
                id: "w_1million",
                name: "1 Million",
                house: "Paco Rabanne",
                accords: [.spicy, .leather, .woody],
                topNotes: ["Grapefruit", "Blood Mandarin", "Peppermint"],
                heartNotes: ["Rose", "Cinnamon"],
                baseNotes: ["Leather", "Amber", "Woody Notes"],
                moodTags: [.bold, .confident, .rebellious],
                colorAssociations: goldColors() + warmColors(weight: 0.6),
                seasonality: [.fall, .winter],
                region: .western,
                priceTier: .mid,
                gender: .masculine,
                amazonASIN: "B001Q4XLMI",
                iconName: "dollarsign.circle.fill",
                shortDescription: "Audacious spicy leather with liquid gold swagger"
            ),
            Fragrance(
                id: "w_chanel_chance",
                name: "Chance Eau Tendre",
                house: "Chanel",
                accords: [.floral, .fruity, .musky],
                topNotes: ["Quince", "Grapefruit"],
                heartNotes: ["Hyacinth", "Jasmine"],
                baseNotes: ["White Musk", "Iris", "Amber", "Cedar"],
                moodTags: [.playful, .fresh, .romantic],
                colorAssociations: pinkColors() + brightColors(weight: 0.6) + whiteColors(weight: 0.5),
                seasonality: [.spring, .summer],
                region: .western,
                priceTier: .luxury,
                gender: .feminine,
                amazonASIN: "B001V6OQXQ",
                iconName: "sparkle",
                shortDescription: "Soft, flirtatious grapefruit-jasmine radiance"
            ),
            Fragrance(
                id: "w_tobacco_vanille",
                name: "Tobacco Vanille",
                house: "Tom Ford",
                accords: [.oriental, .gourmand, .spicy],
                topNotes: ["Tobacco Leaf", "Spicy Notes"],
                heartNotes: ["Vanilla", "Cacao", "Tonka Bean"],
                baseNotes: ["Dried Fruits", "Woody Notes"],
                moodTags: [.opulent, .warm, .cozy],
                colorAssociations: earthyColors() + warmColors(weight: 0.7) + darkColors(weight: 0.6),
                seasonality: [.fall, .winter],
                region: .western,
                priceTier: .luxury,
                gender: .unisex,
                amazonASIN: "B0018OHBMG",
                iconName: "flame.fill",
                shortDescription: "Rich tobacco leaves drenched in sweet vanilla"
            ),
            Fragrance(
                id: "w_light_blue",
                name: "Light Blue",
                house: "Dolce & Gabbana",
                accords: [.citrus, .fresh, .floral],
                topNotes: ["Sicilian Lemon", "Apple", "Cedar"],
                heartNotes: ["Bamboo", "Jasmine", "White Rose"],
                baseNotes: ["Cedar", "Musk", "Amber"],
                moodTags: [.fresh, .playful, .energetic],
                colorAssociations: coolColors() + brightColors(weight: 0.7) + whiteColors(weight: 0.5),
                seasonality: [.spring, .summer],
                region: .western,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: "B000LPHV0Q",
                iconName: "sun.max.fill",
                shortDescription: "Sparkling Sicilian lemon captures summer joy"
            ),
            Fragrance(
                id: "w_molecule01",
                name: "Molecule 01",
                house: "Escentric Molecules",
                accords: [.musky, .woody, .fresh],
                topNotes: ["Iso E Super"],
                heartNotes: ["Iso E Super"],
                baseNotes: ["Iso E Super"],
                moodTags: [.minimal, .mysterious, .serene],
                colorAssociations: neutralColors() + whiteColors(weight: 0.7),
                seasonality: [.spring, .summer, .fall, .winter],
                region: .western,
                priceTier: .mid,
                gender: .unisex,
                amazonASIN: "B004FGWDDE",
                iconName: "atom",
                shortDescription: "Invisible velvety aura, a singular molecule"
            ),
            Fragrance(
                id: "w_coco_mademoiselle",
                name: "Coco Mademoiselle",
                house: "Chanel",
                accords: [.floral, .citrus, .oriental],
                topNotes: ["Orange", "Mandarin", "Bergamot"],
                heartNotes: ["Rose", "Jasmine", "Lychee"],
                baseNotes: ["Musk", "Vanilla", "Patchouli", "Vetiver"],
                moodTags: [.elegant, .confident, .sophisticated],
                colorAssociations: goldColors() + pinkColors(weight: 0.6) + warmColors(weight: 0.4),
                seasonality: [.spring, .summer, .fall],
                region: .western,
                priceTier: .luxury,
                gender: .feminine,
                amazonASIN: "B000GH5HN6",
                iconName: "wand.and.stars",
                shortDescription: "Fresh oriental elegance with citrus sparkle"
            ),
            Fragrance(
                id: "w_explorer",
                name: "Explorer",
                house: "Montblanc",
                accords: [.aromatic, .woody, .leather],
                topNotes: ["Bergamot", "Pink Pepper", "Clary Sage"],
                heartNotes: ["Leather", "Vetiver"],
                baseNotes: ["Indonesian Patchouli", "Akigalawood", "Cacao"],
                moodTags: [.bold, .natural, .confident],
                colorAssociations: earthyColors() + greenColors(weight: 0.6) + darkColors(weight: 0.5),
                seasonality: [.fall, .winter, .spring],
                region: .western,
                priceTier: .budget,
                gender: .masculine,
                amazonASIN: "B07LFG5N8P",
                iconName: "mountain.2.fill",
                shortDescription: "Rugged vetiver-leather adventure at great value"
            ),
            Fragrance(
                id: "w_cloud",
                name: "Cloud",
                house: "Ariana Grande",
                accords: [.gourmand, .musky, .fruity],
                topNotes: ["Lavender Blossom", "Juicy Pear", "Bergamot"],
                heartNotes: ["Coconut", "Praline", "Vanilla Orchid"],
                baseNotes: ["Creamy Musks", "Blonde Woods", "Cashmere"],
                moodTags: [.playful, .cozy, .romantic],
                colorAssociations: pinkColors(weight: 0.8) + whiteColors(weight: 0.7) + brightColors(weight: 0.5),
                seasonality: [.spring, .summer, .fall],
                region: .western,
                priceTier: .budget,
                gender: .feminine,
                amazonASIN: "B07GZD9VYX",
                iconName: "cloud.fill",
                shortDescription: "Dreamy coconut-praline wrapped in soft musk"
            ),
        ]
    }

    // MARK: - German (16 scents)

    private static func germanFragrances() -> [Fragrance] {
        [
            Fragrance(
                id: "de_4711_original",
                name: "4711 Original Eau de Cologne",
                house: "4711",
                accords: [.citrus, .fresh, .aromatic],
                topNotes: ["Bergamot", "Lemon", "Orange"],
                heartNotes: ["Rosemary", "Lavender"],
                baseNotes: ["Musk", "Cedar"],
                moodTags: [.fresh, .natural, .vintage],
                colorAssociations: greenColors() + brightColors(weight: 0.6) + coolColors(weight: 0.4),
                seasonality: [.spring, .summer],
                region: .german,
                priceTier: .budget,
                gender: .unisex,
                amazonASIN: "B000C1ZXAK",
                iconName: "drop.fill",
                shortDescription: "The original 1792 cologne, citrus heritage"
            ),
            Fragrance(
                id: "de_joop_homme",
                name: "Joop! Homme",
                house: "Joop!",
                accords: [.oriental, .floral, .aromatic],
                topNotes: ["Orange Blossom", "Bergamot"],
                heartNotes: ["Cinnamon", "Jasmine", "Heliotrope"],
                baseNotes: ["Sandalwood", "Tonka Bean", "Vanilla"],
                moodTags: [.bold, .sensual, .warm],
                colorAssociations: pinkColors() + warmColors(weight: 0.7) + darkColors(weight: 0.5),
                seasonality: [.fall, .winter],
                region: .german,
                priceTier: .budget,
                gender: .masculine,
                amazonASIN: "B000C1V2W2",
                iconName: "flame",
                shortDescription: "Intense cinnamon-vanilla in an iconic pink bottle"
            ),
            Fragrance(
                id: "de_hugo_boss_bottled",
                name: "Boss Bottled",
                house: "Hugo Boss",
                accords: [.woody, .aromatic, .spicy],
                topNotes: ["Apple", "Citrus", "Plum"],
                heartNotes: ["Geranium", "Cinnamon", "Carnation"],
                baseNotes: ["Sandalwood", "Cedar", "Vetiver", "Olive Tree"],
                moodTags: [.sophisticated, .confident, .elegant],
                colorAssociations: earthyColors() + goldColors(weight: 0.6) + neutralColors(weight: 0.5),
                seasonality: [.spring, .fall, .winter],
                region: .german,
                priceTier: .mid,
                gender: .masculine,
                amazonASIN: "B000E7Y5J0",
                iconName: "briefcase.fill",
                shortDescription: "Polished apple-cinnamon for the boardroom"
            ),
            Fragrance(
                id: "de_baldessarini",
                name: "Baldessarini",
                house: "Baldessarini",
                accords: [.aromatic, .woody, .oriental],
                topNotes: ["Mint", "Whiskey", "Tobacco"],
                heartNotes: ["Sage", "Juniper Berries"],
                baseNotes: ["Amber", "Sandalwood", "Musk"],
                moodTags: [.sophisticated, .warm, .mysterious],
                colorAssociations: darkColors() + earthyColors(weight: 0.7) + goldColors(weight: 0.5),
                seasonality: [.fall, .winter],
                region: .german,
                priceTier: .mid,
                gender: .masculine,
                amazonASIN: "B000P22FT6",
                iconName: "mustache.fill",
                shortDescription: "Whiskey-tobacco gravitas with German precision"
            ),
            Fragrance(
                id: "de_escada_cherry",
                name: "Cherry in Japan",
                house: "Escada",
                accords: [.fruity, .floral, .gourmand],
                topNotes: ["Cherry", "Raspberry"],
                heartNotes: ["Cherry Blossom", "Rose"],
                baseNotes: ["Sandalwood", "Musk", "Vanilla"],
                moodTags: [.playful, .romantic, .fresh],
                colorAssociations: pinkColors() + warmColors(weight: 0.5) + brightColors(weight: 0.6),
                seasonality: [.spring, .summer],
                region: .german,
                priceTier: .budget,
                gender: .feminine,
                amazonASIN: nil,
                iconName: "camera.macro",
                shortDescription: "Juicy cherry blossoms in a garden of joy"
            ),
            Fragrance(
                id: "de_marc_jacobs_daisy",
                name: "Daisy",
                house: "Marc Jacobs",
                accords: [.floral, .fresh, .fruity],
                topNotes: ["Strawberry", "Violet Leaves", "Ruby Red Grapefruit"],
                heartNotes: ["Gardenia", "Violet Petals", "Jasmine"],
                baseNotes: ["Musk", "Vanilla", "White Woods"],
                moodTags: [.playful, .fresh, .natural],
                colorAssociations: whiteColors() + brightColors(weight: 0.7) + greenColors(weight: 0.4),
                seasonality: [.spring, .summer],
                region: .german,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: "B001BYHIM8",
                iconName: "sun.min.fill",
                shortDescription: "Innocent garden-fresh daisies and strawberries"
            ),
            Fragrance(
                id: "de_mcdi_silk_mood",
                name: "Silk Mood",
                house: "Maison Christian Dior",
                accords: [.floral, .musky, .powdery],
                topNotes: ["Bergamot", "Pink Pepper"],
                heartNotes: ["Orange Blossom", "Magnolia", "Rose"],
                baseNotes: ["White Musk", "Cashmeran"],
                moodTags: [.elegant, .serene, .minimal],
                colorAssociations: whiteColors() + neutralColors(weight: 0.7) + pinkColors(weight: 0.4),
                seasonality: [.spring, .summer, .fall],
                region: .german,
                priceTier: .luxury,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "wand.and.rays",
                shortDescription: "Whisper-soft magnolia on cashmere musk"
            ),
            Fragrance(
                id: "de_xerjoff_naxos",
                name: "Naxos",
                house: "Xerjoff",
                accords: [.oriental, .gourmand, .aromatic],
                topNotes: ["Lavender", "Bergamot", "Lemon"],
                heartNotes: ["Cinnamon", "Cashmeran", "Honey"],
                baseNotes: ["Tobacco", "Vanilla", "Tonka Bean"],
                moodTags: [.opulent, .warm, .sophisticated],
                colorAssociations: goldColors() + warmColors(weight: 0.7) + earthyColors(weight: 0.6),
                seasonality: [.fall, .winter],
                region: .german,
                priceTier: .luxury,
                gender: .unisex,
                amazonASIN: "B077HM2FDN",
                iconName: "crown",
                shortDescription: "Honey-lavender-tobacco Italian luxury"
            ),
            Fragrance(
                id: "de_hugo_man",
                name: "Hugo Man",
                house: "Hugo Boss",
                accords: [.aromatic, .green, .fresh],
                topNotes: ["Green Apple", "Lavender"],
                heartNotes: ["Sage", "Geranium", "Pine"],
                baseNotes: ["Cedar", "Fir Resin", "Moss"],
                moodTags: [.energetic, .natural, .fresh],
                colorAssociations: greenColors() + coolColors(weight: 0.5),
                seasonality: [.spring, .summer],
                region: .german,
                priceTier: .budget,
                gender: .masculine,
                amazonASIN: "B000C1UWJK",
                iconName: "leaf.circle.fill",
                shortDescription: "Green apple energy meets forest freshness"
            ),
            Fragrance(
                id: "de_aigner_no1",
                name: "No 1",
                house: "Etienne Aigner",
                accords: [.leather, .woody, .aromatic],
                topNotes: ["Lavender", "Pepper", "Rosemary"],
                heartNotes: ["Leather", "Amber"],
                baseNotes: ["Sandalwood", "Tobacco", "Vetiver"],
                moodTags: [.sophisticated, .warm, .confident],
                colorAssociations: earthyColors() + darkColors(weight: 0.6),
                seasonality: [.fall, .winter],
                region: .german,
                priceTier: .budget,
                gender: .masculine,
                amazonASIN: nil,
                iconName: "bag.fill",
                shortDescription: "German leather craftsmanship in a bottle"
            ),
            Fragrance(
                id: "de_tabac_original",
                name: "Tabac Original",
                house: "Maurer & Wirtz",
                accords: [.aromatic, .spicy, .powdery],
                topNotes: ["Neroli", "Bergamot", "Petitgrain"],
                heartNotes: ["Carnation", "Geranium", "Lavender"],
                baseNotes: ["Tobacco", "Oak Moss", "Sandalwood", "Musk"],
                moodTags: [.vintage, .warm, .confident],
                colorAssociations: earthyColors() + warmColors(weight: 0.6) + neutralColors(weight: 0.4),
                seasonality: [.fall, .winter],
                region: .german,
                priceTier: .budget,
                gender: .masculine,
                amazonASIN: "B0012RQNMO",
                iconName: "smoke.fill",
                shortDescription: "Old-world barbershop tobacco elegance"
            ),
            Fragrance(
                id: "de_philipp_plein_no_limit",
                name: "No Limits",
                house: "Philipp Plein",
                accords: [.woody, .fresh, .aromatic],
                topNotes: ["Bergamot", "Pink Pepper", "Apple"],
                heartNotes: ["Lavender", "Geranium"],
                baseNotes: ["Ambroxan", "Cashmeran", "Musk"],
                moodTags: [.bold, .rebellious, .energetic],
                colorAssociations: darkColors() + coolColors(weight: 0.6) + goldColors(weight: 0.4),
                seasonality: [.spring, .summer, .fall],
                region: .german,
                priceTier: .luxury,
                gender: .masculine,
                amazonASIN: nil,
                iconName: "bolt.circle.fill",
                shortDescription: "Unapologetic urban luxury with edge"
            ),
            Fragrance(
                id: "de_bogner_man",
                name: "Bogner Man",
                house: "Bogner",
                accords: [.fresh, .aromatic, .woody],
                topNotes: ["Bergamot", "Grapefruit"],
                heartNotes: ["Sage", "Cedar"],
                baseNotes: ["Vetiver", "Musk", "Amber"],
                moodTags: [.natural, .fresh, .confident],
                colorAssociations: greenColors() + coolColors(weight: 0.6),
                seasonality: [.spring, .summer],
                region: .german,
                priceTier: .mid,
                gender: .masculine,
                amazonASIN: nil,
                iconName: "figure.skiing.downhill",
                shortDescription: "Alpine freshness for the outdoor spirit"
            ),
            Fragrance(
                id: "de_betty_barclay_tender",
                name: "Tender Blossom",
                house: "Betty Barclay",
                accords: [.floral, .fruity, .musky],
                topNotes: ["Peach", "Pear", "Bergamot"],
                heartNotes: ["Rose", "Peony", "Magnolia"],
                baseNotes: ["White Musk", "Cedar", "Sandalwood"],
                moodTags: [.romantic, .playful, .fresh],
                colorAssociations: pinkColors() + whiteColors(weight: 0.6),
                seasonality: [.spring, .summer],
                region: .german,
                priceTier: .budget,
                gender: .feminine,
                amazonASIN: nil,
                iconName: "heart.circle.fill",
                shortDescription: "Soft peach-rose petals for everyday charm"
            ),
            Fragrance(
                id: "de_escentric_02",
                name: "Escentric 02",
                house: "Escentric Molecules",
                accords: [.musky, .aromatic, .woody],
                topNotes: ["Hedione", "Orris"],
                heartNotes: ["Ambroxan", "Iris"],
                baseNotes: ["Vetiver", "Musk"],
                moodTags: [.minimal, .cool, .sophisticated],
                colorAssociations: neutralColors() + coolColors(weight: 0.5),
                seasonality: [.spring, .summer, .fall, .winter],
                region: .german,
                priceTier: .mid,
                gender: .unisex,
                amazonASIN: "B004FGWDES",
                iconName: "circle.hexagongrid.fill",
                shortDescription: "Molecular minimalism with iris and ambroxan"
            ),
            Fragrance(
                id: "de_iris_ganache",
                name: "Iris Ganache",
                house: "Therry Mugler",
                accords: [.gourmand, .floral, .powdery],
                topNotes: ["Iris", "Bergamot"],
                heartNotes: ["Chocolate", "Iris Butter"],
                baseNotes: ["Vanilla", "Tonka Bean", "Musk"],
                moodTags: [.cozy, .elegant, .warm],
                colorAssociations: earthyColors() + pinkColors(weight: 0.5) + warmColors(weight: 0.4),
                seasonality: [.fall, .winter],
                region: .german,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: nil,
                iconName: "cup.and.saucer.fill",
                shortDescription: "Elegant iris wrapped in chocolate ganache"
            ),
        ]
    }

    // MARK: - Mexican (16 scents)

    private static func mexicanFragrances() -> [Fragrance] {
        [
            Fragrance(
                id: "mx_flor_de_cactus",
                name: "Flor de Cactus",
                house: "Mexican Artisan",
                accords: [.green, .floral, .fresh],
                topNotes: ["Cactus Flower", "Lime", "Green Notes"],
                heartNotes: ["Agave", "Jasmine", "Geranium"],
                baseNotes: ["Vetiver", "Musk", "Cedar"],
                moodTags: [.natural, .fresh, .serene],
                colorAssociations: greenColors() + brightColors(weight: 0.5),
                seasonality: [.spring, .summer],
                region: .mexican,
                priceTier: .budget,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "leaf.fill",
                shortDescription: "Desert cactus bloom under the Mexican sun"
            ),
            Fragrance(
                id: "mx_copal_sagrado",
                name: "Copal Sagrado",
                house: "Mexican Artisan",
                accords: [.oriental, .woody, .spicy],
                topNotes: ["Copal Resin", "Pink Pepper"],
                heartNotes: ["Frankincense", "Myrrh", "Cinnamon"],
                baseNotes: ["Amber", "Sandalwood", "Vanilla"],
                moodTags: [.mysterious, .warm, .opulent],
                colorAssociations: warmColors() + earthyColors(weight: 0.7) + goldColors(weight: 0.5),
                seasonality: [.fall, .winter],
                region: .mexican,
                priceTier: .mid,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "smoke.fill",
                shortDescription: "Sacred copal incense from ancient Mesoamerica"
            ),
            Fragrance(
                id: "mx_vainilla_mexican",
                name: "Vainilla Mexicana",
                house: "Mexican Artisan",
                accords: [.gourmand, .oriental, .spicy],
                topNotes: ["Mexican Vanilla", "Cinnamon", "Cardamom"],
                heartNotes: ["Tonka Bean", "Caramel", "Orchid"],
                baseNotes: ["Amber", "Benzoin", "Musk"],
                moodTags: [.warm, .cozy, .sensual],
                colorAssociations: warmColors() + goldColors(weight: 0.7) + earthyColors(weight: 0.5),
                seasonality: [.fall, .winter],
                region: .mexican,
                priceTier: .budget,
                gender: .feminine,
                amazonASIN: nil,
                iconName: "flame.fill",
                shortDescription: "Rich Totonac vanilla with cinnamon-spice warmth"
            ),
            Fragrance(
                id: "mx_agua_de_jamaica",
                name: "Agua de Jamaica",
                house: "Mexican Artisan",
                accords: [.fruity, .floral, .fresh],
                topNotes: ["Hibiscus", "Lime", "Tamarind"],
                heartNotes: ["Rose", "Red Berries", "Pomegranate"],
                baseNotes: ["Light Musk", "Sugar Cane", "White Cedar"],
                moodTags: [.playful, .energetic, .tropical],
                colorAssociations: warmColors() + pinkColors(weight: 0.6) + brightColors(weight: 0.5),
                seasonality: [.spring, .summer],
                region: .mexican,
                priceTier: .budget,
                gender: .feminine,
                amazonASIN: nil,
                iconName: "cup.and.saucer.fill",
                shortDescription: "Vibrant hibiscus-lime like the beloved drink"
            ),
            Fragrance(
                id: "mx_noche_oaxaquena",
                name: "Noche Oaxaquena",
                house: "Mexican Artisan",
                accords: [.oriental, .gourmand, .spicy],
                topNotes: ["Dark Chocolate", "Chili Pepper"],
                heartNotes: ["Coffee", "Cinnamon", "Mole Spices"],
                baseNotes: ["Vanilla", "Tobacco", "Patchouli"],
                moodTags: [.mysterious, .bold, .warm],
                colorAssociations: darkColors() + warmColors(weight: 0.7) + earthyColors(weight: 0.5),
                seasonality: [.fall, .winter],
                region: .mexican,
                priceTier: .mid,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "moon.fill",
                shortDescription: "Oaxacan night: chocolate-chili mole darkness"
            ),
            Fragrance(
                id: "mx_tuberosa",
                name: "Tuberosa Nocturna",
                house: "Mexican Artisan",
                accords: [.floral, .oriental, .musky],
                topNotes: ["Tuberose", "Orange Blossom"],
                heartNotes: ["Jasmine", "Ylang-Ylang", "Gardenia"],
                baseNotes: ["Musk", "Amber", "Sandalwood"],
                moodTags: [.sensual, .opulent, .romantic],
                colorAssociations: whiteColors() + pinkColors(weight: 0.6) + darkColors(weight: 0.4),
                seasonality: [.spring, .summer, .fall],
                region: .mexican,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: nil,
                iconName: "sparkles",
                shortDescription: "Intoxicating midnight tuberose, voluptuous"
            ),
            Fragrance(
                id: "mx_mezcal_smoke",
                name: "Humo de Mezcal",
                house: "Mexican Artisan",
                accords: [.woody, .leather, .spicy],
                topNotes: ["Smoked Agave", "Black Pepper", "Lime Zest"],
                heartNotes: ["Mesquite", "Leather", "Guaiac Wood"],
                baseNotes: ["Vetiver", "Patchouli", "Amber"],
                moodTags: [.bold, .rebellious, .mysterious],
                colorAssociations: earthyColors() + darkColors(weight: 0.7),
                seasonality: [.fall, .winter],
                region: .mexican,
                priceTier: .mid,
                gender: .masculine,
                amazonASIN: nil,
                iconName: "smoke.fill",
                shortDescription: "Smoky mezcal campfire in an artisan palenque"
            ),
            Fragrance(
                id: "mx_flor_de_naranjo",
                name: "Flor de Naranjo",
                house: "Mexican Artisan",
                accords: [.floral, .citrus, .green],
                topNotes: ["Orange Blossom", "Neroli", "Petitgrain"],
                heartNotes: ["Jasmine", "Green Leaves"],
                baseNotes: ["White Musk", "Cedar"],
                moodTags: [.fresh, .romantic, .elegant],
                colorAssociations: whiteColors() + greenColors(weight: 0.5) + brightColors(weight: 0.4),
                seasonality: [.spring, .summer],
                region: .mexican,
                priceTier: .budget,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "sun.max",
                shortDescription: "Mexican orange blossom, pure and radiant"
            ),
            Fragrance(
                id: "mx_tierra_mojada",
                name: "Tierra Mojada",
                house: "Mexican Artisan",
                accords: [.green, .aquatic, .woody],
                topNotes: ["Petrichor", "Rain Notes", "Green Leaves"],
                heartNotes: ["Wet Earth", "Sage", "Wild Herbs"],
                baseNotes: ["Vetiver", "Oak Moss", "Musk"],
                moodTags: [.natural, .serene, .cool],
                colorAssociations: greenColors() + coolColors(weight: 0.6) + earthyColors(weight: 0.4),
                seasonality: [.spring, .summer, .fall],
                region: .mexican,
                priceTier: .budget,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "cloud.rain.fill",
                shortDescription: "Petrichor after rain on Mexican earth"
            ),
            Fragrance(
                id: "mx_rosa_damascena",
                name: "Rosa Mexicana",
                house: "Mexican Artisan",
                accords: [.floral, .spicy, .powdery],
                topNotes: ["Damask Rose", "Pink Pepper", "Bergamot"],
                heartNotes: ["Rose Absolute", "Geranium", "Cinnamon"],
                baseNotes: ["Sandalwood", "Musk", "Patchouli"],
                moodTags: [.romantic, .elegant, .warm],
                colorAssociations: pinkColors() + warmColors(weight: 0.5),
                seasonality: [.spring, .fall],
                region: .mexican,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: nil,
                iconName: "camera.macro",
                shortDescription: "Bold Mexican rose with spicy cinnamon warmth"
            ),
            Fragrance(
                id: "mx_cenote",
                name: "Cenote Azul",
                house: "Mexican Artisan",
                accords: [.aquatic, .fresh, .green],
                topNotes: ["Water Lily", "Cucumber", "Mint"],
                heartNotes: ["Sea Salt", "Lotus", "Bamboo"],
                baseNotes: ["Driftwood", "White Musk", "Ambergris"],
                moodTags: [.serene, .cool, .natural],
                colorAssociations: coolColors() + greenColors(weight: 0.5) + whiteColors(weight: 0.4),
                seasonality: [.spring, .summer],
                region: .mexican,
                priceTier: .mid,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "water.waves",
                shortDescription: "Crystal-clear Yucatan cenote waters"
            ),
            Fragrance(
                id: "mx_paloma",
                name: "Paloma Rosa",
                house: "Mexican Artisan",
                accords: [.citrus, .fruity, .fresh],
                topNotes: ["Grapefruit", "Lime", "Salt"],
                heartNotes: ["Rose Water", "Cucumber"],
                baseNotes: ["Light Musk", "White Wood"],
                moodTags: [.playful, .energetic, .fresh],
                colorAssociations: pinkColors() + brightColors(weight: 0.6) + coolColors(weight: 0.3),
                seasonality: [.spring, .summer],
                region: .mexican,
                priceTier: .budget,
                gender: .feminine,
                amazonASIN: nil,
                iconName: "wineglass.fill",
                shortDescription: "Sparkling grapefruit-salt like the beloved cocktail"
            ),
            Fragrance(
                id: "mx_madera_sagrada",
                name: "Madera Sagrada",
                house: "Mexican Artisan",
                accords: [.woody, .aromatic, .spicy],
                topNotes: ["Palo Santo", "Cardamom"],
                heartNotes: ["Sandalwood", "Frankincense"],
                baseNotes: ["Cedar", "Amber", "Vetiver"],
                moodTags: [.serene, .warm, .mysterious],
                colorAssociations: earthyColors() + warmColors(weight: 0.5) + neutralColors(weight: 0.4),
                seasonality: [.fall, .winter],
                region: .mexican,
                priceTier: .mid,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "tree.fill",
                shortDescription: "Palo santo sacred wood meditation"
            ),
            Fragrance(
                id: "mx_chile_y_mango",
                name: "Chile y Mango",
                house: "Mexican Artisan",
                accords: [.fruity, .spicy, .gourmand],
                topNotes: ["Mango", "Chili Pepper", "Lime"],
                heartNotes: ["Passion Fruit", "Pineapple", "Ginger"],
                baseNotes: ["Vanilla", "Coconut", "Sandalwood"],
                moodTags: [.playful, .bold, .tropical],
                colorAssociations: warmColors() + brightColors(weight: 0.7),
                seasonality: [.spring, .summer],
                region: .mexican,
                priceTier: .budget,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "flame",
                shortDescription: "Street-cart mango-chili street food vibes"
            ),
            Fragrance(
                id: "mx_alebrijes",
                name: "Alebrijes",
                house: "Mexican Artisan",
                accords: [.oriental, .floral, .fruity],
                topNotes: ["Marigold", "Blood Orange", "Saffron"],
                heartNotes: ["Jasmine", "Orchid", "Cempasuchil"],
                baseNotes: ["Copal", "Amber", "Vanilla"],
                moodTags: [.playful, .opulent, .mysterious],
                colorAssociations: warmColors() + goldColors(weight: 0.6) + pinkColors(weight: 0.4),
                seasonality: [.fall, .winter],
                region: .mexican,
                priceTier: .mid,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "paintpalette.fill",
                shortDescription: "Colorful spirit animals: marigold and copal"
            ),
            Fragrance(
                id: "mx_cafe_de_olla",
                name: "Cafe de Olla",
                house: "Mexican Artisan",
                accords: [.gourmand, .spicy, .oriental],
                topNotes: ["Coffee", "Cinnamon", "Piloncillo"],
                heartNotes: ["Chocolate", "Anise", "Clove"],
                baseNotes: ["Vanilla", "Amber", "Sandalwood"],
                moodTags: [.cozy, .warm, .bold],
                colorAssociations: earthyColors() + warmColors(weight: 0.7) + darkColors(weight: 0.5),
                seasonality: [.fall, .winter],
                region: .mexican,
                priceTier: .budget,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "mug.fill",
                shortDescription: "Traditional spiced coffee brewed in clay pot"
            ),
        ]
    }

    // MARK: - Brazilian (16 scents)

    private static func brazilianFragrances() -> [Fragrance] {
        [
            Fragrance(
                id: "br_natura_essencial",
                name: "Essencial Masculino",
                house: "Natura",
                accords: [.woody, .aromatic, .fresh],
                topNotes: ["Bergamot", "Cardamom"],
                heartNotes: ["Freesia", "Cedar", "Patchouli"],
                baseNotes: ["Sandalwood", "Musk", "Vetiver"],
                moodTags: [.confident, .natural, .sophisticated],
                colorAssociations: earthyColors() + greenColors(weight: 0.5),
                seasonality: [.spring, .summer, .fall],
                region: .brazilian,
                priceTier: .mid,
                gender: .masculine,
                amazonASIN: nil,
                iconName: "leaf.fill",
                shortDescription: "Brazilian rainforest woods, refined and clean"
            ),
            Fragrance(
                id: "br_boticario_malbec",
                name: "Malbec",
                house: "O Boticario",
                accords: [.oriental, .woody, .spicy],
                topNotes: ["Aged Wine Accord", "Artemisia"],
                heartNotes: ["Red Fruits", "Leather"],
                baseNotes: ["Oak", "Amber", "Vanilla"],
                moodTags: [.sophisticated, .warm, .bold],
                colorAssociations: warmColors() + darkColors(weight: 0.7) + earthyColors(weight: 0.5),
                seasonality: [.fall, .winter],
                region: .brazilian,
                priceTier: .mid,
                gender: .masculine,
                amazonASIN: nil,
                iconName: "wineglass.fill",
                shortDescription: "Aged wine barrel depth with leather warmth"
            ),
            Fragrance(
                id: "br_lily_absolu",
                name: "Lily Absolu",
                house: "O Boticario",
                accords: [.floral, .oriental, .powdery],
                topNotes: ["Mandarin", "Pear"],
                heartNotes: ["Lily", "Jasmine", "Rose"],
                baseNotes: ["Vanilla", "Sandalwood", "Musk"],
                moodTags: [.elegant, .romantic, .sophisticated],
                colorAssociations: whiteColors() + pinkColors(weight: 0.6) + goldColors(weight: 0.4),
                seasonality: [.spring, .fall, .winter],
                region: .brazilian,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: nil,
                iconName: "sparkles",
                shortDescription: "Luxurious Brazilian lily, rich and radiant"
            ),
            Fragrance(
                id: "br_kaiak_oceano",
                name: "Kaiak Oceano",
                house: "Natura",
                accords: [.aquatic, .fresh, .citrus],
                topNotes: ["Sea Water", "Bergamot", "Lemon"],
                heartNotes: ["Marine Accord", "Sage", "Cardamom"],
                baseNotes: ["Cedar", "Musk", "Amber"],
                moodTags: [.fresh, .energetic, .natural],
                colorAssociations: coolColors() + brightColors(weight: 0.5),
                seasonality: [.spring, .summer],
                region: .brazilian,
                priceTier: .budget,
                gender: .masculine,
                amazonASIN: nil,
                iconName: "water.waves",
                shortDescription: "Brazilian Atlantic coastline in a bottle"
            ),
            Fragrance(
                id: "br_floratta",
                name: "Floratta in Rose",
                house: "O Boticario",
                accords: [.floral, .fruity, .fresh],
                topNotes: ["Raspberry", "Pear", "Bergamot"],
                heartNotes: ["Rose", "Peony", "Violet"],
                baseNotes: ["Sandalwood", "Musk", "Vanilla"],
                moodTags: [.romantic, .playful, .fresh],
                colorAssociations: pinkColors() + brightColors(weight: 0.5),
                seasonality: [.spring, .summer],
                region: .brazilian,
                priceTier: .budget,
                gender: .feminine,
                amazonASIN: nil,
                iconName: "camera.macro",
                shortDescription: "Pink rose garden with fruity berry sparkle"
            ),
            Fragrance(
                id: "br_mate_verde",
                name: "Mate Verde",
                house: "Brazilian Artisan",
                accords: [.green, .aromatic, .fresh],
                topNotes: ["Yerba Mate", "Lime", "Grapefruit"],
                heartNotes: ["Green Tea", "Sage", "Basil"],
                baseNotes: ["Vetiver", "White Musk", "Cedar"],
                moodTags: [.energetic, .natural, .fresh],
                colorAssociations: greenColors() + brightColors(weight: 0.5) + coolColors(weight: 0.3),
                seasonality: [.spring, .summer],
                region: .brazilian,
                priceTier: .budget,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "mug.fill",
                shortDescription: "Invigorating yerba mate with citrus brightness"
            ),
            Fragrance(
                id: "br_amazonia",
                name: "Amazonia",
                house: "Brazilian Artisan",
                accords: [.green, .woody, .fresh],
                topNotes: ["Passion Fruit", "Acai", "Green Leaves"],
                heartNotes: ["Brazilian Rosewood", "Orchid", "Guarana"],
                baseNotes: ["Patchouli", "Vetiver", "Moss"],
                moodTags: [.natural, .bold, .mysterious],
                colorAssociations: greenColors() + earthyColors(weight: 0.6),
                seasonality: [.spring, .summer, .fall],
                region: .brazilian,
                priceTier: .mid,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "tree.fill",
                shortDescription: "Deep Amazon rainforest with rosewood heart"
            ),
            Fragrance(
                id: "br_caipirinha",
                name: "Caipirinha Fresca",
                house: "Brazilian Artisan",
                accords: [.citrus, .fresh, .green],
                topNotes: ["Lime", "Cachaca Accord", "Sugar Cane"],
                heartNotes: ["Mint", "Green Leaves", "Cucumber"],
                baseNotes: ["White Musk", "Light Woods"],
                moodTags: [.playful, .energetic, .tropical],
                colorAssociations: greenColors() + brightColors(weight: 0.7),
                seasonality: [.spring, .summer],
                region: .brazilian,
                priceTier: .budget,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "wineglass.fill",
                shortDescription: "Zesty lime-sugar cane cocktail freshness"
            ),
            Fragrance(
                id: "br_ipanema_sunset",
                name: "Ipanema Sunset",
                house: "Brazilian Artisan",
                accords: [.floral, .fruity, .musky],
                topNotes: ["Mango", "Passion Fruit", "Coconut Water"],
                heartNotes: ["Frangipani", "Jasmine", "Ylang-Ylang"],
                baseNotes: ["Vanilla", "Sandalwood", "Musk", "Amber"],
                moodTags: [.tropical, .romantic, .warm],
                colorAssociations: warmColors() + goldColors(weight: 0.6) + pinkColors(weight: 0.4),
                seasonality: [.summer, .spring],
                region: .brazilian,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: nil,
                iconName: "sunset.fill",
                shortDescription: "Golden hour on Ipanema Beach, tropical blooms"
            ),
            Fragrance(
                id: "br_madeira_nobre",
                name: "Madeira Nobre",
                house: "Brazilian Artisan",
                accords: [.woody, .spicy, .leather],
                topNotes: ["Pink Pepper", "Nutmeg"],
                heartNotes: ["Brazilian Rosewood", "Cedarwood", "Suede"],
                baseNotes: ["Oud", "Amber", "Tonka Bean"],
                moodTags: [.opulent, .sophisticated, .warm],
                colorAssociations: earthyColors() + darkColors(weight: 0.6) + goldColors(weight: 0.4),
                seasonality: [.fall, .winter],
                region: .brazilian,
                priceTier: .luxury,
                gender: .masculine,
                amazonASIN: nil,
                iconName: "shield.fill",
                shortDescription: "Noble Brazilian hardwoods with suede richness"
            ),
            Fragrance(
                id: "br_pitanga",
                name: "Pitanga Rosa",
                house: "Brazilian Artisan",
                accords: [.fruity, .floral, .fresh],
                topNotes: ["Pitanga Berry", "Lychee", "Pink Pepper"],
                heartNotes: ["Rose", "Freesia", "Hibiscus"],
                baseNotes: ["White Musk", "Cashmeran", "Cedar"],
                moodTags: [.playful, .energetic, .fresh],
                colorAssociations: pinkColors() + warmColors(weight: 0.5) + brightColors(weight: 0.4),
                seasonality: [.spring, .summer],
                region: .brazilian,
                priceTier: .budget,
                gender: .feminine,
                amazonASIN: nil,
                iconName: "heart.fill",
                shortDescription: "Tangy pitanga berry with floral brightness"
            ),
            Fragrance(
                id: "br_carnaval",
                name: "Carnaval",
                house: "Brazilian Artisan",
                accords: [.fruity, .gourmand, .oriental],
                topNotes: ["Tropical Fruits", "Coconut", "Lime"],
                heartNotes: ["Jasmine", "Ylang-Ylang", "Rum"],
                baseNotes: ["Vanilla", "Amber", "Sandalwood", "Musk"],
                moodTags: [.playful, .bold, .energetic],
                colorAssociations: brightColors() + warmColors(weight: 0.6) + goldColors(weight: 0.4),
                seasonality: [.summer, .spring],
                region: .brazilian,
                priceTier: .mid,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "party.popper.fill",
                shortDescription: "Explosive tropical party, rum and coconut"
            ),
            Fragrance(
                id: "br_orquidea",
                name: "Orquidea Negra",
                house: "Brazilian Artisan",
                accords: [.floral, .oriental, .musky],
                topNotes: ["Black Orchid", "Dark Plum", "Bergamot"],
                heartNotes: ["Orchid", "Ylang-Ylang", "Black Pepper"],
                baseNotes: ["Dark Chocolate", "Patchouli", "Vanilla"],
                moodTags: [.mysterious, .sensual, .opulent],
                colorAssociations: darkColors() + purpleColors(weight: 0.6) + warmColors(weight: 0.3),
                seasonality: [.fall, .winter],
                region: .brazilian,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: nil,
                iconName: "moon.stars.fill",
                shortDescription: "Dark orchid seduction with chocolate depth"
            ),
            Fragrance(
                id: "br_acai_power",
                name: "Acai Power",
                house: "Brazilian Artisan",
                accords: [.fruity, .fresh, .green],
                topNotes: ["Acai", "Guarana", "Lime"],
                heartNotes: ["Ginger", "Green Tea", "Basil"],
                baseNotes: ["Vetiver", "Light Musk", "Cedar"],
                moodTags: [.energetic, .fresh, .natural],
                colorAssociations: purpleColors() + greenColors(weight: 0.5) + coolColors(weight: 0.3),
                seasonality: [.spring, .summer],
                region: .brazilian,
                priceTier: .budget,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "bolt.fill",
                shortDescription: "Superfruit energy burst with herbal edge"
            ),
            Fragrance(
                id: "br_samba_nights",
                name: "Samba Nights",
                house: "Brazilian Artisan",
                accords: [.oriental, .spicy, .gourmand],
                topNotes: ["Cachaca", "Lime", "Pink Pepper"],
                heartNotes: ["Cinnamon", "Tonka Bean", "Jasmine"],
                baseNotes: ["Vanilla", "Amber", "Sandalwood", "Musk"],
                moodTags: [.sensual, .bold, .warm],
                colorAssociations: warmColors() + goldColors(weight: 0.6) + darkColors(weight: 0.4),
                seasonality: [.fall, .winter, .summer],
                region: .brazilian,
                priceTier: .mid,
                gender: .unisex,
                amazonASIN: nil,
                iconName: "music.note",
                shortDescription: "Spicy vanilla rhythms for late-night samba"
            ),
            Fragrance(
                id: "br_coco_bahia",
                name: "Coco Bahia",
                house: "Brazilian Artisan",
                accords: [.gourmand, .fresh, .fruity],
                topNotes: ["Coconut", "Lime", "Sea Salt"],
                heartNotes: ["Vanilla Orchid", "Tiare Flower"],
                baseNotes: ["Sandalwood", "Musk", "Tonka Bean"],
                moodTags: [.tropical, .playful, .serene],
                colorAssociations: whiteColors() + brightColors(weight: 0.6) + coolColors(weight: 0.3),
                seasonality: [.spring, .summer],
                region: .brazilian,
                priceTier: .budget,
                gender: .feminine,
                amazonASIN: nil,
                iconName: "sun.max.fill",
                shortDescription: "Bahia beach coconut with salty sea breeze"
            ),
        ]
    }

    // MARK: - French (18 scents)

    private static func frenchFragrances() -> [Fragrance] {
        [
            Fragrance(
                id: "fr_shalimar",
                name: "Shalimar",
                house: "Guerlain",
                accords: [.oriental, .powdery, .gourmand],
                topNotes: ["Bergamot", "Lemon", "Cedar"],
                heartNotes: ["Jasmine", "Rose", "Iris"],
                baseNotes: ["Vanilla", "Tonka Bean", "Opopanax", "Sandalwood"],
                moodTags: [.opulent, .vintage, .sensual],
                colorAssociations: goldColors() + warmColors(weight: 0.6) + darkColors(weight: 0.4),
                seasonality: [.fall, .winter],
                region: .french,
                priceTier: .luxury,
                gender: .feminine,
                amazonASIN: "B000C1YX18",
                iconName: "crown.fill",
                shortDescription: "1925 oriental legend, vanilla-incense grandeur"
            ),
            Fragrance(
                id: "fr_la_nuit",
                name: "La Nuit de L'Homme",
                house: "Yves Saint Laurent",
                accords: [.oriental, .spicy, .woody],
                topNotes: ["Cardamom", "Bergamot"],
                heartNotes: ["Lavender", "Cedar", "Virginian Cedar"],
                baseNotes: ["Vetiver", "Caraway", "Coumarin"],
                moodTags: [.sensual, .mysterious, .sophisticated],
                colorAssociations: darkColors() + coolColors(weight: 0.5) + purpleColors(weight: 0.3),
                seasonality: [.fall, .winter],
                region: .french,
                priceTier: .mid,
                gender: .masculine,
                amazonASIN: "B0030UQNA2",
                iconName: "moon.fill",
                shortDescription: "Seductive cardamom-lavender for the night"
            ),
            Fragrance(
                id: "fr_leau_dissey",
                name: "L'Eau d'Issey Pour Homme",
                house: "Issey Miyake",
                accords: [.aquatic, .citrus, .woody],
                topNotes: ["Yuzu", "Cypress", "Mandarin", "Bergamot"],
                heartNotes: ["Water Lily", "Calone", "Nutmeg"],
                baseNotes: ["Vetiver", "Sandalwood", "Musk", "Amber"],
                moodTags: [.fresh, .serene, .minimal],
                colorAssociations: coolColors() + whiteColors(weight: 0.7) + greenColors(weight: 0.3),
                seasonality: [.spring, .summer],
                region: .french,
                priceTier: .mid,
                gender: .masculine,
                amazonASIN: "B000E7WMUI",
                iconName: "drop.fill",
                shortDescription: "Zen-like yuzu and water, Japanese-French minimalism"
            ),
            Fragrance(
                id: "fr_musc_ravageur",
                name: "Musc Ravageur",
                house: "Frederic Malle",
                accords: [.oriental, .musky, .spicy],
                topNotes: ["Bergamot", "Lavender"],
                heartNotes: ["Cinnamon", "Clove"],
                baseNotes: ["Musk", "Amber", "Sandalwood", "Vanilla", "Gaiac Wood"],
                moodTags: [.sensual, .bold, .warm],
                colorAssociations: warmColors() + darkColors(weight: 0.6) + goldColors(weight: 0.4),
                seasonality: [.fall, .winter],
                region: .french,
                priceTier: .luxury,
                gender: .unisex,
                amazonASIN: "B000E82B42",
                iconName: "flame.fill",
                shortDescription: "Devastating musk-amber, pure French niche"
            ),
            Fragrance(
                id: "fr_miss_dior",
                name: "Miss Dior",
                house: "Dior",
                accords: [.floral, .fresh, .fruity],
                topNotes: ["Blood Orange", "Mandarin"],
                heartNotes: ["Rose", "Peony", "Lily of the Valley"],
                baseNotes: ["Patchouli", "Musk", "Rosewood"],
                moodTags: [.romantic, .elegant, .playful],
                colorAssociations: pinkColors() + whiteColors(weight: 0.6),
                seasonality: [.spring, .summer, .fall],
                region: .french,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: "B00GBYALRA",
                iconName: "heart.fill",
                shortDescription: "Parisian chic: rose-peony with citrus sparkle"
            ),
            Fragrance(
                id: "fr_baccarat_rouge",
                name: "Baccarat Rouge 540",
                house: "Maison Francis Kurkdjian",
                accords: [.oriental, .floral, .woody],
                topNotes: ["Saffron", "Jasmine"],
                heartNotes: ["Amberwood", "Ambergris"],
                baseNotes: ["Fir Resin", "Cedar"],
                moodTags: [.opulent, .mysterious, .elegant],
                colorAssociations: goldColors() + warmColors(weight: 0.6) + pinkColors(weight: 0.3),
                seasonality: [.fall, .winter, .spring],
                region: .french,
                priceTier: .luxury,
                gender: .unisex,
                amazonASIN: "B06XKT12QN",
                iconName: "diamond.fill",
                shortDescription: "Luminous saffron-amber crystal, iconic niche"
            ),
            Fragrance(
                id: "fr_mon_guerlain",
                name: "Mon Guerlain",
                house: "Guerlain",
                accords: [.oriental, .floral, .gourmand],
                topNotes: ["Lavender", "Bergamot"],
                heartNotes: ["Jasmine", "Iris"],
                baseNotes: ["Vanilla", "Sandalwood", "Coumarin"],
                moodTags: [.romantic, .warm, .elegant],
                colorAssociations: pinkColors() + goldColors(weight: 0.5) + warmColors(weight: 0.4),
                seasonality: [.fall, .winter, .spring],
                region: .french,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: "B06XBXJBSR",
                iconName: "sparkles",
                shortDescription: "Modern Guerlain: lavender-vanilla tenderness"
            ),
            Fragrance(
                id: "fr_terre_dhermes",
                name: "Terre d'Hermes",
                house: "Hermes",
                accords: [.woody, .citrus, .spicy],
                topNotes: ["Orange", "Grapefruit", "Flint"],
                heartNotes: ["Pepper", "Geranium", "Patchouli"],
                baseNotes: ["Vetiver", "Cedar", "Benzoin"],
                moodTags: [.sophisticated, .natural, .warm],
                colorAssociations: earthyColors() + warmColors(weight: 0.5) + greenColors(weight: 0.3),
                seasonality: [.spring, .summer, .fall],
                region: .french,
                priceTier: .mid,
                gender: .masculine,
                amazonASIN: "B000GHUWK6",
                iconName: "mountain.2.fill",
                shortDescription: "Earth, minerals, and citrus — Hermes masterwork"
            ),
            Fragrance(
                id: "fr_portrait_lady",
                name: "Portrait of a Lady",
                house: "Frederic Malle",
                accords: [.oriental, .floral, .spicy],
                topNotes: ["Turkish Rose", "Clove", "Raspberry"],
                heartNotes: ["Patchouli", "Cinnamon"],
                baseNotes: ["Sandalwood", "Frankincense", "Musk", "Amber"],
                moodTags: [.opulent, .bold, .sophisticated],
                colorAssociations: warmColors() + darkColors(weight: 0.6) + pinkColors(weight: 0.3),
                seasonality: [.fall, .winter],
                region: .french,
                priceTier: .luxury,
                gender: .feminine,
                amazonASIN: "B003TXZNTW",
                iconName: "person.crop.artframe",
                shortDescription: "Monumental rose-patchouli, a French masterpiece"
            ),
            Fragrance(
                id: "fr_vetiver",
                name: "Vetiver",
                house: "Guerlain",
                accords: [.aromatic, .woody, .green],
                topNotes: ["Lemon", "Neroli", "Bergamot"],
                heartNotes: ["Vetiver", "Pepper", "Nutmeg"],
                baseNotes: ["Tobacco", "Tonka Bean", "Cedar"],
                moodTags: [.sophisticated, .natural, .confident],
                colorAssociations: greenColors() + earthyColors(weight: 0.6),
                seasonality: [.spring, .summer, .fall],
                region: .french,
                priceTier: .mid,
                gender: .masculine,
                amazonASIN: "B000C1UNKM",
                iconName: "leaf.fill",
                shortDescription: "Definitive vetiver, grassy elegance since 1959"
            ),
            Fragrance(
                id: "fr_alien",
                name: "Alien",
                house: "Mugler",
                accords: [.oriental, .floral, .woody],
                topNotes: ["Jasmine Sambac"],
                heartNotes: ["Cashmeran", "Amber"],
                baseNotes: ["White Amber", "Cedar", "Tonka Bean"],
                moodTags: [.mysterious, .bold, .opulent],
                colorAssociations: purpleColors() + goldColors(weight: 0.5) + darkColors(weight: 0.4),
                seasonality: [.fall, .winter],
                region: .french,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: "B000E7Y3UM",
                iconName: "staroflife.fill",
                shortDescription: "Otherworldly solar jasmine-amber radiance"
            ),
            Fragrance(
                id: "fr_neroli_portofino",
                name: "Neroli Portofino",
                house: "Tom Ford",
                accords: [.citrus, .floral, .aromatic],
                topNotes: ["Bergamot", "Mandarin Orange", "Lemon", "Lavender"],
                heartNotes: ["African Orange Flower", "Neroli", "Jasmine"],
                baseNotes: ["Amber", "Amberwood", "Angelica"],
                moodTags: [.fresh, .elegant, .serene],
                colorAssociations: brightColors() + whiteColors(weight: 0.6) + coolColors(weight: 0.3),
                seasonality: [.spring, .summer],
                region: .french,
                priceTier: .luxury,
                gender: .unisex,
                amazonASIN: "B005DMCQU2",
                iconName: "sun.max.fill",
                shortDescription: "Italian Riviera neroli, effortless summer luxury"
            ),
            Fragrance(
                id: "fr_linterdit",
                name: "L'Interdit",
                house: "Givenchy",
                accords: [.floral, .oriental, .powdery],
                topNotes: ["Pear", "Bergamot"],
                heartNotes: ["Orange Blossom", "Jasmine", "Tuberose"],
                baseNotes: ["Patchouli", "Vetiver", "Ambroxan"],
                moodTags: [.bold, .elegant, .mysterious],
                colorAssociations: darkColors() + whiteColors(weight: 0.5) + pinkColors(weight: 0.3),
                seasonality: [.fall, .winter, .spring],
                region: .french,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: "B07R2YCKJY",
                iconName: "lock.fill",
                shortDescription: "Forbidden white flowers over dark vetiver"
            ),
            Fragrance(
                id: "fr_encre_noire",
                name: "Encre Noire",
                house: "Lalique",
                accords: [.woody, .aromatic, .green],
                topNotes: ["Cypress"],
                heartNotes: ["Vetiver"],
                baseNotes: ["Musk", "Cashmere Wood"],
                moodTags: [.mysterious, .minimal, .cool],
                colorAssociations: darkColors() + greenColors(weight: 0.5) + neutralColors(weight: 0.4),
                seasonality: [.fall, .winter],
                region: .french,
                priceTier: .budget,
                gender: .masculine,
                amazonASIN: "B001MKL6AA",
                iconName: "drop.degreesign.fill",
                shortDescription: "Dark ink, wet vetiver, austere beauty"
            ),
            Fragrance(
                id: "fr_angel",
                name: "Angel",
                house: "Mugler",
                accords: [.gourmand, .oriental, .floral],
                topNotes: ["Helional", "Bergamot", "Coconut"],
                heartNotes: ["Honey", "Caramel", "Apricot"],
                baseNotes: ["Patchouli", "Chocolate", "Vanilla", "Tonka Bean"],
                moodTags: [.bold, .opulent, .cozy],
                colorAssociations: purpleColors() + warmColors(weight: 0.5) + goldColors(weight: 0.4),
                seasonality: [.fall, .winter],
                region: .french,
                priceTier: .mid,
                gender: .feminine,
                amazonASIN: "B000C1V0MC",
                iconName: "star.fill",
                shortDescription: "Revolutionary patchouli-chocolate gourmand icon"
            ),
            Fragrance(
                id: "fr_eau_sauvage",
                name: "Eau Sauvage",
                house: "Dior",
                accords: [.citrus, .aromatic, .woody],
                topNotes: ["Lemon", "Bergamot", "Basil"],
                heartNotes: ["Vetiver", "Hedione", "Iris"],
                baseNotes: ["Oak Moss", "Musk"],
                moodTags: [.sophisticated, .fresh, .vintage],
                colorAssociations: greenColors() + brightColors(weight: 0.5) + coolColors(weight: 0.3),
                seasonality: [.spring, .summer],
                region: .french,
                priceTier: .mid,
                gender: .masculine,
                amazonASIN: "B000C1V0KY",
                iconName: "wind",
                shortDescription: "1966 citrus legend, the first Hedione fragrance"
            ),
            Fragrance(
                id: "fr_noir_extreme",
                name: "Noir Extreme",
                house: "Tom Ford",
                accords: [.oriental, .gourmand, .woody],
                topNotes: ["Mandarin", "Saffron", "Cardamom", "Nutmeg"],
                heartNotes: ["Rose Absolute", "Jasmine", "Orange Blossom"],
                baseNotes: ["Sandalwood", "Amber", "Vanilla", "Woody Notes"],
                moodTags: [.opulent, .warm, .sensual],
                colorAssociations: darkColors() + goldColors(weight: 0.6) + warmColors(weight: 0.5),
                seasonality: [.fall, .winter],
                region: .french,
                priceTier: .luxury,
                gender: .masculine,
                amazonASIN: "B01LXHTEZ2",
                iconName: "moon.stars.fill",
                shortDescription: "Rich amber-saffron indulgence, evening opulence"
            ),
            Fragrance(
                id: "fr_jardin_sur_nil",
                name: "Un Jardin sur le Nil",
                house: "Hermes",
                accords: [.green, .citrus, .fruity],
                topNotes: ["Grapefruit", "Mango", "Lotus"],
                heartNotes: ["Green Tomato", "Peony", "Calamus"],
                baseNotes: ["Incense", "Sycamore", "Iris"],
                moodTags: [.fresh, .playful, .natural],
                colorAssociations: greenColors() + brightColors(weight: 0.6) + whiteColors(weight: 0.3),
                seasonality: [.spring, .summer],
                region: .french,
                priceTier: .mid,
                gender: .unisex,
                amazonASIN: "B000FQ0QQO",
                iconName: "leaf.arrow.triangle.circlepath",
                shortDescription: "Green mango and lotus on the Nile"
            ),
        ]
    }
}
