import Foundation

// MARK: - Brazilian Market Fragrances
// Sources: O Boticario 2025 bestsellers, Natura 2025 bestsellers, Eudora, industry reports

enum FragranceDB_Brazilian {
    static let all: [Fragrance] = boticario + natura + eudoraAndOthers + internationalInBrazil + moreBoticario + moreNatura

    // MARK: - O Boticário (~50)

    static let boticario: [Fragrance] = [
        Fragrance(id: "br_malbec", name: "Malbec", house: "O Boticario",
                  accords: [.oriental, .woody, .spicy],
                  topNotes: ["Aged Wine Accord", "Artemisia"], heartNotes: ["Red Fruits", "Leather"], baseNotes: ["Oak", "Amber", "Vanilla"],
                  moodTags: [.sophisticated, .warm, .bold],
                  colorAssociations: ColorPreset.warm() + ColorPreset.dark(0.7) + ColorPreset.earthy(0.5),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "wineglass.fill", shortDescription: "#1 men's in Brazil — aged wine barrel depth",
                  bottleColor: "#722F37", bottleShape: .square),
        Fragrance(id: "br_malbec_bleu", name: "Malbec Bleu", house: "O Boticario",
                  accords: [.aquatic, .woody, .citrus],
                  topNotes: ["Bergamot", "Lemon"], heartNotes: ["Sea Notes", "Lavender"], baseNotes: ["Cedar", "Amber", "Musk"],
                  moodTags: [.fresh, .confident, .natural],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "water.waves", shortDescription: "Lighter aquatic Malbec for Brazilian heat",
                  bottleColor: "#4682B4", bottleShape: .square),
        Fragrance(id: "br_malbec_gold", name: "Malbec Gold", house: "O Boticario",
                  accords: [.oriental, .woody, .gourmand],
                  topNotes: ["Rum Accord", "Plum"], heartNotes: ["Honey", "Cinnamon"], baseNotes: ["Vanilla", "Tonka Bean", "Oak"],
                  moodTags: [.opulent, .warm, .sophisticated],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.7),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "wineglass.fill", shortDescription: "Premium Malbec with honey-rum richness",
                  bottleColor: "#DAA520", bottleShape: .square),
        Fragrance(id: "br_malbec_x", name: "Malbec X", house: "O Boticario",
                  accords: [.woody, .spicy, .aromatic],
                  topNotes: ["Black Pepper", "Cardamom"], heartNotes: ["Leather", "Geranium"], baseNotes: ["Sandalwood", "Amber", "Musk"],
                  moodTags: [.bold, .rebellious, .confident],
                  colorAssociations: ColorPreset.dark() + ColorPreset.warm(0.5),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "bolt.fill", shortDescription: "Edgy leather-pepper Malbec evolution",
                  bottleColor: "#1C1C1C", bottleShape: .square),
        Fragrance(id: "br_floratta_rose", name: "Floratta Rose", house: "O Boticario",
                  accords: [.floral, .fruity, .fresh],
                  topNotes: ["Raspberry", "Pear", "Bergamot"], heartNotes: ["Rose", "Peony", "Violet"], baseNotes: ["Sandalwood", "Musk", "Vanilla"],
                  moodTags: [.romantic, .playful, .fresh],
                  colorAssociations: ColorPreset.pink() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "camera.macro", shortDescription: "#1 women's at Boticário — pink rose garden charm",
                  bottleColor: "#FF69B4", bottleShape: .round),
        Fragrance(id: "br_floratta_eclipse", name: "Floratta Fleur D'Eclipse", house: "O Boticario",
                  accords: [.floral, .fruity, .musky],
                  topNotes: ["Pear", "Peach"], heartNotes: ["Jasmine", "Magnolia", "Orange Blossom"], baseNotes: ["Musk", "Sandalwood", "Vanilla"],
                  moodTags: [.elegant, .fresh, .romantic],
                  colorAssociations: ColorPreset.pink() + ColorPreset.white(0.6),
                  seasonality: [.spring, .summer, .fall], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "moon.fill", shortDescription: "Modern solar floral, 2025 breakout hit",
                  bottleColor: "#E6C2D9", bottleShape: .round),
        Fragrance(id: "br_floratta_blue", name: "Floratta in Blue", house: "O Boticario",
                  accords: [.floral, .fresh, .aquatic],
                  topNotes: ["Blueberry", "Bergamot"], heartNotes: ["Violet", "Water Lily", "Jasmine"], baseNotes: ["Musk", "Cedar"],
                  moodTags: [.fresh, .playful, .serene],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "drop.fill", shortDescription: "Blueberry-violet freshness for sunny days",
                  bottleColor: "#6495ED", bottleShape: .round),
        Fragrance(id: "br_egeo_dolce", name: "Egeo Dolce", house: "O Boticario",
                  accords: [.gourmand, .fruity, .musky],
                  topNotes: ["Marshmallow", "Red Berries"], heartNotes: ["Vanilla", "Coconut"], baseNotes: ["Caramel", "Musk", "Sandalwood"],
                  moodTags: [.playful, .cozy, .romantic],
                  colorAssociations: ColorPreset.pink() + ColorPreset.warm(0.6),
                  seasonality: [.fall, .winter, .spring], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "cup.and.saucer.fill", shortDescription: "Marshmallow-vanilla sweetness, iconic Brazilian gourmand",
                  bottleColor: "#FFB6C1", bottleShape: .round),
        Fragrance(id: "br_egeo_choc_berry", name: "Egeo Choc Berry", house: "O Boticario",
                  accords: [.gourmand, .fruity, .oriental],
                  topNotes: ["Red Berries", "Raspberry"], heartNotes: ["White Chocolate", "Rose"], baseNotes: ["Vanilla", "Musk", "Caramel"],
                  moodTags: [.playful, .bold, .warm],
                  colorAssociations: ColorPreset.pink() + ColorPreset.warm(0.5),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "heart.fill", shortDescription: "Chocolate-berry indulgence, 2025 breakout",
                  bottleColor: "#C71585", bottleShape: .round),
        Fragrance(id: "br_egeo_choc_mint", name: "Egeo Choc Mint", house: "O Boticario",
                  accords: [.gourmand, .aromatic, .fresh],
                  topNotes: ["Mint", "Bergamot"], heartNotes: ["Dark Chocolate", "Coffee"], baseNotes: ["Vanilla", "Tonka Bean", "Musk"],
                  moodTags: [.playful, .energetic, .cozy],
                  colorAssociations: ColorPreset.green() + ColorPreset.earthy(0.5),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .budget, gender: .unisex,
                  amazonASIN: nil, iconName: "leaf.fill", shortDescription: "After-dinner mint chocolate freshness",
                  bottleColor: "#2E8B57", bottleShape: .round),
        Fragrance(id: "br_egeo_hit", name: "Egeo Hit", house: "O Boticario",
                  accords: [.fresh, .citrus, .musky],
                  topNotes: ["Lemon", "Green Apple"], heartNotes: ["Jasmine", "Magnolia"], baseNotes: ["Musk", "Cedar"],
                  moodTags: [.energetic, .playful, .fresh],
                  colorAssociations: ColorPreset.bright() + ColorPreset.cool(0.4),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "bolt.fill", shortDescription: "Citrus-floral energy hit for everyday",
                  bottleColor: "#FFD700", bottleShape: .round),
        Fragrance(id: "br_lily_edp", name: "Lily Eau de Parfum", house: "O Boticario",
                  accords: [.floral, .oriental, .powdery],
                  topNotes: ["Mandarin", "Pear"], heartNotes: ["Lily", "Jasmine", "Rose"], baseNotes: ["Vanilla", "Sandalwood", "Musk"],
                  moodTags: [.elegant, .romantic, .sophisticated],
                  colorAssociations: ColorPreset.white() + ColorPreset.pink(0.6) + ColorPreset.gold(0.4),
                  seasonality: [.spring, .fall, .winter], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "sparkles", shortDescription: "Luxurious lily elegance, Boticário's premium line",
                  bottleColor: "#F5F5DC", bottleShape: .tall),
        Fragrance(id: "br_lily_absolu", name: "Lily Absolu", house: "O Boticario",
                  accords: [.floral, .oriental, .gourmand],
                  topNotes: ["Pink Pepper", "Rose Petals"], heartNotes: ["Lily", "Iris", "Jasmine"], baseNotes: ["Vanilla Absolute", "Sandalwood", "Amber"],
                  moodTags: [.opulent, .warm, .elegant],
                  colorAssociations: ColorPreset.gold() + ColorPreset.pink(0.5),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "sparkles", shortDescription: "Rich lily-vanilla luxury, Boticário's finest",
                  bottleColor: "#C5B358", bottleShape: .tall),
        Fragrance(id: "br_quasar_brave", name: "Quasar Brave", house: "O Boticario",
                  accords: [.fresh, .woody, .aromatic],
                  topNotes: ["Bergamot", "Grapefruit"], heartNotes: ["Mint", "Sage", "Lavender"], baseNotes: ["Cedar", "Musk", "Amber"],
                  moodTags: [.energetic, .confident, .fresh],
                  colorAssociations: ColorPreset.cool() + ColorPreset.green(0.5),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .masculine,
                  amazonASIN: nil, iconName: "bolt.circle.fill", shortDescription: "Fresh-aromatic for active Brazilian men",
                  bottleColor: "#4169E1", bottleShape: .modern),
        Fragrance(id: "br_quasar_surf", name: "Quasar Surf", house: "O Boticario",
                  accords: [.aquatic, .fresh, .citrus],
                  topNotes: ["Lemon", "Sea Salt", "Green Notes"], heartNotes: ["Marine Accord", "Coconut Water"], baseNotes: ["Driftwood", "Musk"],
                  moodTags: [.energetic, .fresh, .natural],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.6),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .masculine,
                  amazonASIN: nil, iconName: "water.waves", shortDescription: "Brazilian beach wave in a bottle",
                  bottleColor: "#00CED1", bottleShape: .modern),
        Fragrance(id: "br_coffee_man", name: "Coffee Man", house: "O Boticario",
                  accords: [.gourmand, .oriental, .aromatic],
                  topNotes: ["Coffee", "Bergamot", "Cardamom"], heartNotes: ["Lavender", "Geranium", "Cinnamon"], baseNotes: ["Vanilla", "Tonka Bean", "Musk", "Amber"],
                  moodTags: [.warm, .bold, .sophisticated],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.warm(0.6) + ColorPreset.dark(0.4),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .budget, gender: .masculine,
                  amazonASIN: nil, iconName: "mug.fill", shortDescription: "Brazilian espresso warmth with spice and vanilla",
                  bottleColor: "#3C1414", bottleShape: .square),
        Fragrance(id: "br_coffee_woman", name: "Coffee Woman", house: "O Boticario",
                  accords: [.gourmand, .floral, .oriental],
                  topNotes: ["Coffee", "Rose", "Bergamot"], heartNotes: ["Jasmine", "Praline"], baseNotes: ["Vanilla", "Sandalwood", "Musk"],
                  moodTags: [.warm, .romantic, .cozy],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.pink(0.5),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "mug.fill", shortDescription: "Rose-coffee sweetness for feminine warmth",
                  bottleColor: "#5D3A1A", bottleShape: .round),
        Fragrance(id: "br_zaad", name: "Zaad", house: "O Boticario",
                  accords: [.woody, .aromatic, .fresh],
                  topNotes: ["Bergamot", "Grapefruit", "Cardamom"], heartNotes: ["Violet", "Cedar", "Geranium"], baseNotes: ["Sandalwood", "Vetiver", "Musk", "Tonka Bean"],
                  moodTags: [.sophisticated, .elegant, .confident],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.cool(0.4),
                  seasonality: [.spring, .fall], region: .brazilian, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "leaf.fill", shortDescription: "Refined woody elegance, Boticário premium men's",
                  bottleColor: "#2F4F4F", bottleShape: .square),
        Fragrance(id: "br_zaad_arctic", name: "Zaad Arctic", house: "O Boticario",
                  accords: [.fresh, .aromatic, .aquatic],
                  topNotes: ["Grapefruit", "Mint", "Juniper"], heartNotes: ["Lavender", "Marine Notes"], baseNotes: ["Vetiver", "Musk", "Ambroxan"],
                  moodTags: [.fresh, .energetic, .cool],
                  colorAssociations: ColorPreset.cool() + ColorPreset.white(0.5),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "snowflake", shortDescription: "Ice-cool mint-marine freshness",
                  bottleColor: "#B0E0E6", bottleShape: .square),
        Fragrance(id: "br_elysee", name: "Elysee Blanc", house: "O Boticario",
                  accords: [.floral, .gourmand, .musky],
                  topNotes: ["Pear", "Bergamot"], heartNotes: ["Iris", "White Rose", "Orange Blossom"], baseNotes: ["Vanilla", "Musk", "Sandalwood"],
                  moodTags: [.elegant, .romantic, .warm],
                  colorAssociations: ColorPreset.white() + ColorPreset.pink(0.4) + ColorPreset.gold(0.3),
                  seasonality: [.spring, .fall, .winter], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "crown", shortDescription: "White iris-vanilla sophistication",
                  bottleColor: "#FFFAF0", bottleShape: .flacon),
        Fragrance(id: "br_glamour_midnight", name: "Glamour Midnight", house: "O Boticario",
                  accords: [.oriental, .gourmand, .floral],
                  topNotes: ["Black Currant", "Pink Pepper"], heartNotes: ["Jasmine", "Praline", "Iris"], baseNotes: ["Vanilla", "Amber", "Musk", "Patchouli"],
                  moodTags: [.sensual, .mysterious, .bold],
                  colorAssociations: ColorPreset.dark() + ColorPreset.purple(0.5),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "moon.stars.fill", shortDescription: "Midnight seduction with praline and jasmine",
                  bottleColor: "#191970", bottleShape: .flacon),
        Fragrance(id: "br_make_b_gold", name: "Make B. Gold", house: "O Boticario",
                  accords: [.oriental, .floral, .gourmand],
                  topNotes: ["Bergamot", "Passion Fruit"], heartNotes: ["Jasmine", "Rose", "Ylang-Ylang"], baseNotes: ["Amber", "Vanilla", "Sandalwood", "Tonka Bean"],
                  moodTags: [.opulent, .warm, .elegant],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.6),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "sparkles", shortDescription: "Golden luxury floral-oriental",
                  bottleColor: "#FFD700", bottleShape: .flacon),
    ]

    // MARK: - Natura (~35)

    static let natura: [Fragrance] = [
        Fragrance(id: "br_luna_intenso", name: "Luna Intenso", house: "Natura",
                  accords: [.floral, .woody, .oriental],
                  topNotes: ["Bergamot", "Pink Pepper"], heartNotes: ["Rose", "Jasmine", "Iris"], baseNotes: ["Sandalwood", "Patchouli", "Vanilla", "Musk"],
                  moodTags: [.sophisticated, .warm, .elegant],
                  colorAssociations: ColorPreset.dark() + ColorPreset.purple(0.4) + ColorPreset.warm(0.3),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "moon.fill", shortDescription: "#1 Natura women's — sophisticated chypre mastery",
                  bottleColor: "#2C1A4A", bottleShape: .tall),
        Fragrance(id: "br_luna_absoluta", name: "Luna Absoluta", house: "Natura",
                  accords: [.floral, .oriental, .gourmand],
                  topNotes: ["Pear", "Mandarin"], heartNotes: ["Tuberose", "Jasmine"], baseNotes: ["Vanilla", "Amber", "Sandalwood"],
                  moodTags: [.opulent, .sensual, .warm],
                  colorAssociations: ColorPreset.gold() + ColorPreset.purple(0.4),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "moon.stars.fill", shortDescription: "Tuberose-vanilla indulgence from Natura's Luna line",
                  bottleColor: "#4B0082", bottleShape: .tall),
        Fragrance(id: "br_kaiak_aventura", name: "Kaiak Aventura", house: "Natura",
                  accords: [.fresh, .aromatic, .woody],
                  topNotes: ["Grapefruit", "Green Notes", "Bergamot"], heartNotes: ["Geranium", "Sage", "Lavender"], baseNotes: ["Cedar", "Musk", "Vetiver"],
                  moodTags: [.energetic, .natural, .bold],
                  colorAssociations: ColorPreset.green() + ColorPreset.cool(0.5),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .masculine,
                  amazonASIN: nil, iconName: "figure.hiking", shortDescription: "Adventure-ready herbal freshness",
                  bottleColor: "#2E8B57", bottleShape: .modern),
        Fragrance(id: "br_kaiak_oceano", name: "Kaiak Oceano", house: "Natura",
                  accords: [.aquatic, .fresh, .citrus],
                  topNotes: ["Sea Water", "Bergamot", "Lemon"], heartNotes: ["Marine Accord", "Sage", "Cardamom"], baseNotes: ["Cedar", "Musk", "Amber"],
                  moodTags: [.fresh, .energetic, .natural],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .masculine,
                  amazonASIN: nil, iconName: "water.waves", shortDescription: "Brazilian Atlantic coastline in a bottle",
                  bottleColor: "#4682B4", bottleShape: .modern),
        Fragrance(id: "br_kaiak_urbe", name: "Kaiak Urbe", house: "Natura",
                  accords: [.aromatic, .woody, .spicy],
                  topNotes: ["Pink Pepper", "Cardamom"], heartNotes: ["Lavender", "Geranium"], baseNotes: ["Amber", "Tonka Bean", "Vetiver"],
                  moodTags: [.confident, .bold, .sophisticated],
                  colorAssociations: ColorPreset.dark() + ColorPreset.warm(0.4),
                  seasonality: [.fall, .winter, .spring], region: .brazilian, priceTier: .budget, gender: .masculine,
                  amazonASIN: nil, iconName: "building.2.fill", shortDescription: "Urban sophistication for city nights",
                  bottleColor: "#2C2C2C", bottleShape: .modern),
        Fragrance(id: "br_ilia", name: "Ilia Deo Parfum", house: "Natura",
                  accords: [.floral, .musky, .fresh],
                  topNotes: ["Bergamot", "Pear"], heartNotes: ["Jasmine", "Rose", "Peony"], baseNotes: ["White Musk", "Cedar", "Vanilla"],
                  moodTags: [.elegant, .fresh, .romantic],
                  colorAssociations: ColorPreset.pink() + ColorPreset.white(0.6),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "sparkle", shortDescription: "Best cost-benefit Natura women's — modern and delicate",
                  bottleColor: "#FFC0CB", bottleShape: .tall),
        Fragrance(id: "br_ilia_luminata", name: "Ilia Luminata", house: "Natura",
                  accords: [.floral, .fruity, .gourmand],
                  topNotes: ["Pink Pepper", "Pear", "Raspberry"], heartNotes: ["Rose", "Iris", "Osmanthus"], baseNotes: ["Vanilla", "Sandalwood", "Musk"],
                  moodTags: [.playful, .warm, .elegant],
                  colorAssociations: ColorPreset.pink() + ColorPreset.gold(0.4),
                  seasonality: [.spring, .fall], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "sparkles", shortDescription: "Luminous rose-iris with golden warmth",
                  bottleColor: "#FFD700", bottleShape: .tall),
        Fragrance(id: "br_essencial_exclusivo", name: "Essencial Exclusivo", house: "Natura",
                  accords: [.woody, .aromatic, .fresh],
                  topNotes: ["Bergamot", "Cardamom"], heartNotes: ["Freesia", "Cedar", "Patchouli"], baseNotes: ["Sandalwood", "Musk", "Vetiver"],
                  moodTags: [.confident, .natural, .sophisticated],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.green(0.5),
                  seasonality: [.spring, .summer, .fall], region: .brazilian, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "leaf.fill", shortDescription: "Brazilian rainforest woods, refined and clean",
                  bottleColor: "#556B2F", bottleShape: .tall),
        Fragrance(id: "br_essencial_supreme", name: "Essencial Supreme", house: "Natura",
                  accords: [.woody, .oriental, .spicy],
                  topNotes: ["Black Pepper", "Nutmeg", "Bergamot"], heartNotes: ["Cedarwood", "Iris"], baseNotes: ["Amber", "Vetiver", "Tonka Bean", "Oud"],
                  moodTags: [.opulent, .warm, .bold],
                  colorAssociations: ColorPreset.dark() + ColorPreset.earthy(0.6),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "shield.fill", shortDescription: "Supreme oud-amber depth from Natura's premium line",
                  bottleColor: "#2C1810", bottleShape: .tall),
        Fragrance(id: "br_essencial_atrai", name: "Essencial Atrai", house: "Natura",
                  accords: [.gourmand, .oriental, .floral],
                  topNotes: ["Pink Pepper", "Pear"], heartNotes: ["Iris", "Jasmine", "Praline"], baseNotes: ["Vanilla", "Sandalwood", "Amber"],
                  moodTags: [.sensual, .warm, .elegant],
                  colorAssociations: ColorPreset.gold() + ColorPreset.pink(0.5),
                  seasonality: [.fall, .winter, .spring], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "heart.fill", shortDescription: "2025 hero launch — sweet attraction fragrance",
                  bottleColor: "#C5B358", bottleShape: .tall),
        Fragrance(id: "br_humor", name: "Meu Primeiro Humor", house: "Natura",
                  accords: [.fruity, .floral, .fresh],
                  topNotes: ["Apple", "Lychee", "Bergamot"], heartNotes: ["Rose", "Peony", "Lily of the Valley"], baseNotes: ["Musk", "Sandalwood"],
                  moodTags: [.playful, .fresh, .energetic],
                  colorAssociations: ColorPreset.bright() + ColorPreset.pink(0.4),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "face.smiling.fill", shortDescription: "Fun fruity-floral for young Brazilian women",
                  bottleColor: "#FF69B4", bottleShape: .round),
        Fragrance(id: "br_biografia", name: "Biografia Inspire", house: "Natura",
                  accords: [.woody, .aromatic, .oriental],
                  topNotes: ["Bergamot", "Ginger", "Cardamom"], heartNotes: ["Sage", "Lavender", "Geranium"], baseNotes: ["Tonka Bean", "Amber", "Sandalwood"],
                  moodTags: [.sophisticated, .warm, .confident],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.warm(0.5),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .budget, gender: .masculine,
                  amazonASIN: nil, iconName: "book.fill", shortDescription: "Inspired woody-aromatic daily companion",
                  bottleColor: "#4A3728", bottleShape: .tall),
        Fragrance(id: "br_kriska", name: "Kriska", house: "Natura",
                  accords: [.floral, .fruity, .musky],
                  topNotes: ["Passion Fruit", "Lemon"], heartNotes: ["Jasmine", "Rose", "Freesia"], baseNotes: ["Musk", "Sandalwood", "Vanilla"],
                  moodTags: [.playful, .tropical, .energetic],
                  colorAssociations: ColorPreset.bright() + ColorPreset.warm(0.5),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "sun.max.fill", shortDescription: "Tropical passion fruit energy, quintessentially Brazilian",
                  bottleColor: "#FF6347", bottleShape: .round),
        Fragrance(id: "br_ekos_acai", name: "Ekos Acai", house: "Natura",
                  accords: [.fruity, .fresh, .green],
                  topNotes: ["Acai", "Guarana", "Lime"], heartNotes: ["Ginger", "Green Tea"], baseNotes: ["Vetiver", "Musk", "Cedar"],
                  moodTags: [.energetic, .fresh, .natural],
                  colorAssociations: ColorPreset.purple() + ColorPreset.green(0.5),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .unisex,
                  amazonASIN: nil, iconName: "bolt.fill", shortDescription: "Amazonian superfruit energy from sustainable source",
                  bottleColor: "#4B0082", bottleShape: .tall),
        Fragrance(id: "br_ekos_flor_luar", name: "Ekos Flor do Luar", house: "Natura",
                  accords: [.floral, .musky, .green],
                  topNotes: ["Green Leaves", "Bergamot"], heartNotes: ["White Flowers", "Jasmine", "Ylang-Ylang"], baseNotes: ["Musk", "Sandalwood"],
                  moodTags: [.serene, .romantic, .natural],
                  colorAssociations: ColorPreset.white() + ColorPreset.green(0.4),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "moon.fill", shortDescription: "Moonlit Amazonian white flowers",
                  bottleColor: "#E0E0E0", bottleShape: .tall),
        Fragrance(id: "br_homem_essence", name: "Homem Essence", house: "Natura",
                  accords: [.woody, .aromatic, .spicy],
                  topNotes: ["Black Pepper", "Bergamot"], heartNotes: ["Lavender", "Cedar"], baseNotes: ["Vetiver", "Musk", "Amber"],
                  moodTags: [.confident, .natural, .sophisticated],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.dark(0.4),
                  seasonality: [.fall, .winter, .spring], region: .brazilian, priceTier: .budget, gender: .masculine,
                  amazonASIN: nil, iconName: "person.fill", shortDescription: "Essential woody masculinity, everyday elegance",
                  bottleColor: "#36454F", bottleShape: .tall),
        Fragrance(id: "br_homem_sagaz", name: "Homem Sagaz", house: "Natura",
                  accords: [.aromatic, .fresh, .woody],
                  topNotes: ["Grapefruit", "Pink Pepper", "Basil"], heartNotes: ["Sage", "Geranium", "Lavender"], baseNotes: ["Cedar", "Musk", "Ambroxan"],
                  moodTags: [.energetic, .bold, .confident],
                  colorAssociations: ColorPreset.cool() + ColorPreset.green(0.4),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .masculine,
                  amazonASIN: nil, iconName: "bolt.fill", shortDescription: "Sharp sage-grapefruit for smart men",
                  bottleColor: "#2E8B57", bottleShape: .modern),
    ]

    // MARK: - Eudora & Other Brazilian Brands (~15)

    static let eudoraAndOthers: [Fragrance] = [
        Fragrance(id: "br_eudora_kiss", name: "Kiss Me", house: "Eudora",
                  accords: [.fruity, .floral, .gourmand],
                  topNotes: ["Red Berries", "Mandarin"], heartNotes: ["Rose", "Peony"], baseNotes: ["Vanilla", "Musk", "Sandalwood"],
                  moodTags: [.romantic, .playful, .warm],
                  colorAssociations: ColorPreset.pink() + ColorPreset.warm(0.5),
                  seasonality: [.spring, .fall], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "heart.fill", shortDescription: "Sweet berry-rose kiss, Eudora's bestseller",
                  bottleColor: "#FF1493", bottleShape: .round),
        Fragrance(id: "br_eudora_instance_cafe", name: "Instance Cafe", house: "Eudora",
                  accords: [.gourmand, .oriental, .aromatic],
                  topNotes: ["Coffee", "Hazelnut"], heartNotes: ["Chocolate", "Vanilla"], baseNotes: ["Tonka Bean", "Musk"],
                  moodTags: [.cozy, .warm, .bold],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.warm(0.6),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .budget, gender: .unisex,
                  amazonASIN: nil, iconName: "mug.fill", shortDescription: "Hazelnut coffee indulgence in a bottle",
                  bottleColor: "#3C1414", bottleShape: .round),
        Fragrance(id: "br_avon_far_away", name: "Far Away", house: "Avon",
                  accords: [.oriental, .floral, .gourmand],
                  topNotes: ["Freesia", "Peach"], heartNotes: ["Jasmine", "Osmanthus", "Ylang-Ylang"], baseNotes: ["Vanilla", "Musk", "Sandalwood"],
                  moodTags: [.tropical, .warm, .romantic],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.6),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "globe", shortDescription: "Exotic jasmine-vanilla, massive in Brazil via Avon",
                  bottleColor: "#DAA520", bottleShape: .round),
        Fragrance(id: "br_avon_black_suede", name: "Black Suede", house: "Avon",
                  accords: [.leather, .woody, .aromatic],
                  topNotes: ["Bergamot", "Mandarin"], heartNotes: ["Lavender", "Sage", "Leather"], baseNotes: ["Sandalwood", "Musk", "Amber"],
                  moodTags: [.bold, .confident, .mysterious],
                  colorAssociations: ColorPreset.dark() + ColorPreset.earthy(0.5),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .budget, gender: .masculine,
                  amazonASIN: nil, iconName: "bag.fill", shortDescription: "Dark suede-leather at Avon budget price",
                  bottleColor: "#1C1C1C", bottleShape: .square),
        Fragrance(id: "br_good_girl_br", name: "Good Girl", house: "Carolina Herrera",
                  accords: [.oriental, .floral, .gourmand],
                  topNotes: ["Almond", "Coffee", "Bergamot"], heartNotes: ["Tuberose", "Jasmine", "Orange Blossom"], baseNotes: ["Cacao", "Tonka Bean", "Sandalwood"],
                  moodTags: [.sensual, .bold, .sophisticated],
                  colorAssociations: ColorPreset.dark() + ColorPreset.pink(0.6) + ColorPreset.gold(0.5),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "star.fill", shortDescription: "Stiletto bottle icon, huge in Brazilian market",
                  bottleColor: "#1A0A2E", bottleShape: .modern),
        Fragrance(id: "br_sauvage_br", name: "Sauvage", house: "Dior",
                  accords: [.aromatic, .fresh, .spicy],
                  topNotes: ["Calabrian Bergamot", "Pepper"], heartNotes: ["Sichuan Pepper", "Lavender", "Geranium"], baseNotes: ["Ambroxan", "Cedar", "Labdanum"],
                  moodTags: [.bold, .confident, .energetic],
                  colorAssociations: ColorPreset.cool() + ColorPreset.dark(0.7),
                  seasonality: [.spring, .summer, .fall], region: .brazilian, priceTier: .luxury, gender: .masculine,
                  amazonASIN: nil, iconName: "wind", shortDescription: "Global phenomenon, Brazilian men's aspirational pick",
                  bottleColor: "#1A3A5C", bottleShape: .tall),
        Fragrance(id: "br_invictus_br", name: "Invictus", house: "Paco Rabanne",
                  accords: [.aquatic, .fresh, .woody],
                  topNotes: ["Marine Notes", "Grapefruit", "Mandarin"], heartNotes: ["Bay Leaf", "Jasmine"], baseNotes: ["Guaiac Wood", "Patchouli", "Oak Moss"],
                  moodTags: [.energetic, .bold, .confident],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.6),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "trophy.fill", shortDescription: "Trophy fragrance, hugely popular in Brazil",
                  bottleColor: "#C0C0C0", bottleShape: .modern),
        Fragrance(id: "br_212_vip_rose", name: "212 VIP Rose", house: "Carolina Herrera",
                  accords: [.floral, .fruity, .musky],
                  topNotes: ["Champagne Rose", "Pink Pepper"], heartNotes: ["Peach Blossom", "Queen of the Night Flower"], baseNotes: ["Musk", "Woody Notes"],
                  moodTags: [.playful, .bold, .elegant],
                  colorAssociations: ColorPreset.pink() + ColorPreset.gold(0.5),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "party.popper.fill", shortDescription: "Champagne rose party, VIP Brazilian style",
                  bottleColor: "#FFB6C1", bottleShape: .modern),
    ]

    // MARK: - International Brands Popular in Brazil (~40)

    static let internationalInBrazil: [Fragrance] = [
        Fragrance(id: "br_jadore", name: "J'adore", house: "Dior",
                  accords: [.floral, .fruity, .woody],
                  topNotes: ["Pear", "Melon", "Magnolia"], heartNotes: ["Jasmine", "Tuberose", "Rose"], baseNotes: ["Musk", "Vanilla", "Cedar"],
                  moodTags: [.elegant, .warm, .opulent],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.5),
                  seasonality: [.spring, .summer, .fall], region: .brazilian, priceTier: .luxury, gender: .feminine,
                  amazonASIN: nil, iconName: "crown.fill", shortDescription: "Golden goddess bouquet, huge aspirational pick in Brazil",
                  bottleColor: "#FFD700", bottleShape: .tall),
        Fragrance(id: "br_libre", name: "Libre", house: "Yves Saint Laurent",
                  accords: [.floral, .oriental, .aromatic],
                  topNotes: ["Mandarin", "Lavender", "Black Currant"], heartNotes: ["Orange Blossom", "Jasmine"], baseNotes: ["Vanilla", "Cedar", "Musk"],
                  moodTags: [.bold, .confident, .elegant],
                  colorAssociations: ColorPreset.gold() + ColorPreset.purple(0.4),
                  seasonality: [.fall, .winter, .spring], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "flame", shortDescription: "Bold lavender-vanilla freedom, trending in Brazil",
                  bottleColor: "#D4AF37", bottleShape: .modern),
        Fragrance(id: "br_black_opium", name: "Black Opium", house: "Yves Saint Laurent",
                  accords: [.oriental, .gourmand, .floral],
                  topNotes: ["Pink Pepper", "Orange Blossom", "Pear"], heartNotes: ["Coffee", "Jasmine", "Bitter Almond"], baseNotes: ["Vanilla", "Patchouli", "Cedar"],
                  moodTags: [.sensual, .bold, .mysterious],
                  colorAssociations: ColorPreset.dark() + ColorPreset.purple(0.7),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "moon.stars.fill", shortDescription: "Coffee-vanilla addiction, massive in Brazilian nightlife",
                  bottleColor: "#1A0A2E", bottleShape: .modern),
        Fragrance(id: "br_la_vie", name: "La Vie Est Belle", house: "Lancome",
                  accords: [.gourmand, .floral, .oriental],
                  topNotes: ["Black Currant", "Pear"], heartNotes: ["Iris", "Jasmine", "Orange Blossom"], baseNotes: ["Praline", "Vanilla", "Patchouli"],
                  moodTags: [.romantic, .warm, .elegant],
                  colorAssociations: ColorPreset.pink() + ColorPreset.gold(0.7),
                  seasonality: [.fall, .winter, .spring], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "heart.fill", shortDescription: "Iris-praline joy, one of Brazil's most gifted fragrances",
                  bottleColor: "#E8B4B8", bottleShape: .tall),
        Fragrance(id: "br_eros", name: "Eros", house: "Versace",
                  accords: [.fresh, .aromatic, .woody],
                  topNotes: ["Mint", "Green Apple", "Lemon"], heartNotes: ["Tonka Bean", "Ambroxan", "Geranium"], baseNotes: ["Vanilla", "Vetiver", "Oak Moss"],
                  moodTags: [.bold, .energetic, .confident],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.6),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "bolt.fill", shortDescription: "Vibrant Greek power, huge with young Brazilian men",
                  bottleColor: "#1E90FF", bottleShape: .modern),
        Fragrance(id: "br_1million", name: "1 Million", house: "Paco Rabanne",
                  accords: [.spicy, .leather, .woody],
                  topNotes: ["Grapefruit", "Blood Mandarin", "Peppermint"], heartNotes: ["Rose", "Cinnamon"], baseNotes: ["Leather", "Amber", "Woody Notes"],
                  moodTags: [.bold, .confident, .rebellious],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.6),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "dollarsign.circle.fill", shortDescription: "Gold bar swagger, iconic in Brazilian party scene",
                  bottleColor: "#FFD700", bottleShape: .modern),
        Fragrance(id: "br_ch_men", name: "CH Men", house: "Carolina Herrera",
                  accords: [.leather, .woody, .spicy],
                  topNotes: ["Bergamot", "Grapefruit"], heartNotes: ["Nutmeg", "Saffron", "Violet Leaf"], baseNotes: ["Leather", "Suede", "Woodsy Notes"],
                  moodTags: [.sophisticated, .bold, .warm],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.dark(0.5),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "briefcase.fill", shortDescription: "Leather sophistication, Carolina Herrera's Brazilian staple",
                  bottleColor: "#8B4513", bottleShape: .round),
        Fragrance(id: "br_bleu_chanel", name: "Bleu de Chanel", house: "Chanel",
                  accords: [.woody, .aromatic, .citrus],
                  topNotes: ["Grapefruit", "Lemon", "Mint"], heartNotes: ["Ginger", "Nutmeg", "Jasmine"], baseNotes: ["Sandalwood", "Cedar", "Incense"],
                  moodTags: [.sophisticated, .confident, .elegant],
                  colorAssociations: ColorPreset.cool() + ColorPreset.dark(0.6),
                  seasonality: [.spring, .summer, .fall, .winter], region: .brazilian, priceTier: .luxury, gender: .masculine,
                  amazonASIN: nil, iconName: "circle.fill", shortDescription: "Refined woody-aromatic, aspirational pick in Brazil",
                  bottleColor: "#1B2838", bottleShape: .tall),
        Fragrance(id: "br_miss_dior", name: "Miss Dior", house: "Dior",
                  accords: [.floral, .fresh, .fruity],
                  topNotes: ["Blood Orange", "Mandarin"], heartNotes: ["Rose", "Peony", "Lily of the Valley"], baseNotes: ["Patchouli", "Musk", "Rosewood"],
                  moodTags: [.romantic, .elegant, .playful],
                  colorAssociations: ColorPreset.pink() + ColorPreset.white(0.6),
                  seasonality: [.spring, .summer, .fall], region: .brazilian, priceTier: .luxury, gender: .feminine,
                  amazonASIN: nil, iconName: "heart.fill", shortDescription: "Parisian rose-peony chic, a Brazilian dream",
                  bottleColor: "#FFD1DC", bottleShape: .tall),
        Fragrance(id: "br_flowerbomb", name: "Flowerbomb", house: "Viktor & Rolf",
                  accords: [.floral, .oriental, .gourmand],
                  topNotes: ["Tea", "Bergamot"], heartNotes: ["Jasmine", "Rose", "Freesia", "Orchid"], baseNotes: ["Patchouli", "Musk", "Vanilla"],
                  moodTags: [.romantic, .opulent, .warm],
                  colorAssociations: ColorPreset.pink() + ColorPreset.warm(0.7),
                  seasonality: [.fall, .winter, .spring], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "camera.macro", shortDescription: "Floral explosion, a top gift in Brazilian market",
                  bottleColor: "#FF69B4", bottleShape: .round),
        Fragrance(id: "br_gucci_bloom", name: "Gucci Bloom", house: "Gucci",
                  accords: [.floral, .green, .powdery],
                  topNotes: ["Rangoon Creeper"], heartNotes: ["Jasmine", "Tuberose"], baseNotes: ["Sandalwood", "Musk", "Orris"],
                  moodTags: [.natural, .romantic, .elegant],
                  colorAssociations: ColorPreset.pink() + ColorPreset.white(0.6),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "leaf.fill", shortDescription: "White floral garden, gaining fast in Brazil",
                  bottleColor: "#FFC0CB", bottleShape: .square),
        Fragrance(id: "br_le_male", name: "Le Male", house: "Jean Paul Gaultier",
                  accords: [.oriental, .aromatic, .fresh],
                  topNotes: ["Mint", "Lavender", "Bergamot"], heartNotes: ["Orange Blossom", "Cinnamon", "Cumin"], baseNotes: ["Vanilla", "Tonka Bean", "Cedar"],
                  moodTags: [.bold, .sensual, .playful],
                  colorAssociations: ColorPreset.cool() + ColorPreset.warm(0.4),
                  seasonality: [.spring, .fall, .winter], region: .brazilian, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "figure.stand", shortDescription: "Iconic sailor, long-time Brazilian men's favorite",
                  bottleColor: "#5B8DBE", bottleShape: .modern),
        Fragrance(id: "br_olympea", name: "Olympea", house: "Paco Rabanne",
                  accords: [.oriental, .floral, .aquatic],
                  topNotes: ["Green Mandarin", "Aquatic Notes"], heartNotes: ["Jasmine", "Salt", "Ginger Lily"], baseNotes: ["Cashmere Wood", "Amber", "Sandalwood"],
                  moodTags: [.sensual, .elegant, .bold],
                  colorAssociations: ColorPreset.gold() + ColorPreset.cool(0.4),
                  seasonality: [.fall, .winter, .spring], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "crown.fill", shortDescription: "Goddess cologne, huge in Brazil",
                  bottleColor: "#C5B358", bottleShape: .modern),
        Fragrance(id: "br_light_blue", name: "Light Blue", house: "Dolce & Gabbana",
                  accords: [.citrus, .fresh, .floral],
                  topNotes: ["Sicilian Lemon", "Apple", "Cedar"], heartNotes: ["Bamboo", "Jasmine", "White Rose"], baseNotes: ["Cedar", "Musk", "Amber"],
                  moodTags: [.fresh, .playful, .energetic],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.7),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "sun.max.fill", shortDescription: "Sicilian lemon joy, perfect for Brazilian summer",
                  bottleColor: "#87CEEB", bottleShape: .square),
        Fragrance(id: "br_dylan_blue", name: "Dylan Blue", house: "Versace",
                  accords: [.aromatic, .fresh, .woody],
                  topNotes: ["Calabrian Bergamot", "Grapefruit", "Fig Leaf"], heartNotes: ["Violet Leaf", "Papyrus", "Ambroxan"], baseNotes: ["Musk", "Tonka Bean", "Saffron"],
                  moodTags: [.confident, .fresh, .sophisticated],
                  colorAssociations: ColorPreset.cool() + ColorPreset.dark(0.4),
                  seasonality: [.spring, .summer, .fall], region: .brazilian, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "drop.fill", shortDescription: "Mediterranean blue, gaining fast in Brazil",
                  bottleColor: "#1565C0", bottleShape: .modern),
        Fragrance(id: "br_lady_million", name: "Lady Million", house: "Paco Rabanne",
                  accords: [.floral, .woody, .fresh],
                  topNotes: ["Amalfi Lemon", "Raspberry"], heartNotes: ["Gardenia", "African Orange Flower"], baseNotes: ["Patchouli", "Honey", "Amber"],
                  moodTags: [.bold, .confident, .opulent],
                  colorAssociations: ColorPreset.gold() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .fall], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "dollarsign.circle.fill", shortDescription: "Diamond gardenia-honey, top gift in Brazil",
                  bottleColor: "#FFD700", bottleShape: .modern),
        Fragrance(id: "br_scandal", name: "Scandal", house: "Jean Paul Gaultier",
                  accords: [.oriental, .gourmand, .floral],
                  topNotes: ["Blood Orange", "Mandarin"], heartNotes: ["Honey", "Gardenia"], baseNotes: ["Caramel", "Beeswax", "Patchouli"],
                  moodTags: [.sensual, .bold, .warm],
                  colorAssociations: ColorPreset.gold() + ColorPreset.pink(0.5),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "exclamationmark.triangle.fill", shortDescription: "Honey-caramel legs, scandalously addictive",
                  bottleColor: "#FFD700", bottleShape: .modern),
        Fragrance(id: "br_bright_crystal", name: "Bright Crystal", house: "Versace",
                  accords: [.floral, .fresh, .musky],
                  topNotes: ["Pomegranate", "Yuzu", "Frost Accord"], heartNotes: ["Peony", "Magnolia", "Lotus"], baseNotes: ["Musk", "Amber", "Mahogany"],
                  moodTags: [.elegant, .fresh, .romantic],
                  colorAssociations: ColorPreset.pink() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "sparkle", shortDescription: "Crystal floral freshness for Brazilian summers",
                  bottleColor: "#FFD1DC", bottleShape: .modern),
        Fragrance(id: "br_coco_mademoiselle", name: "Coco Mademoiselle", house: "Chanel",
                  accords: [.floral, .citrus, .oriental],
                  topNotes: ["Orange", "Mandarin", "Bergamot"], heartNotes: ["Rose", "Jasmine", "Lychee"], baseNotes: ["Musk", "Vanilla", "Patchouli"],
                  moodTags: [.elegant, .confident, .sophisticated],
                  colorAssociations: ColorPreset.gold() + ColorPreset.pink(0.6),
                  seasonality: [.spring, .summer, .fall], region: .brazilian, priceTier: .luxury, gender: .feminine,
                  amazonASIN: nil, iconName: "wand.and.stars", shortDescription: "Fresh oriental elegance, ultimate Brazilian aspiration",
                  bottleColor: "#FFDAB9", bottleShape: .tall),
        Fragrance(id: "br_cloud", name: "Cloud", house: "Ariana Grande",
                  accords: [.gourmand, .musky, .fruity],
                  topNotes: ["Lavender Blossom", "Juicy Pear", "Bergamot"], heartNotes: ["Coconut", "Praline", "Vanilla Orchid"], baseNotes: ["Creamy Musks", "Blonde Woods"],
                  moodTags: [.playful, .cozy, .romantic],
                  colorAssociations: ColorPreset.pink(0.8) + ColorPreset.white(0.7),
                  seasonality: [.spring, .summer, .fall], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "cloud.fill", shortDescription: "Dreamy coconut-praline, TikTok viral in Brazil",
                  bottleColor: "#E6E6FA", bottleShape: .round),
    ]

    // MARK: - More O Boticário (~20)

    static let moreBoticario: [Fragrance] = [
        Fragrance(id: "br_floratta_love", name: "Floratta Simple Love", house: "O Boticario",
                  accords: [.floral, .fruity, .fresh],
                  topNotes: ["Raspberry", "Lychee"], heartNotes: ["Peony", "Rose"], baseNotes: ["Musk", "Vanilla"],
                  moodTags: [.romantic, .playful, .fresh],
                  colorAssociations: ColorPreset.pink() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "heart.fill", shortDescription: "Sweet simple love in floral form",
                  bottleColor: "#FF69B4", bottleShape: .round),
        Fragrance(id: "br_lily_lumiere", name: "Lily Lumiere", house: "O Boticario",
                  accords: [.floral, .fresh, .musky],
                  topNotes: ["Bergamot", "Pink Pepper"], heartNotes: ["Lily", "Jasmine", "Freesia"], baseNotes: ["White Musk", "Cedar"],
                  moodTags: [.elegant, .fresh, .serene],
                  colorAssociations: ColorPreset.white() + ColorPreset.pink(0.4),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "sun.max.fill", shortDescription: "Luminous lily freshness, daytime elegance",
                  bottleColor: "#FFFACD", bottleShape: .tall),
        Fragrance(id: "br_quasar_rush", name: "Quasar Rush", house: "O Boticario",
                  accords: [.aromatic, .woody, .spicy],
                  topNotes: ["Cardamom", "Bergamot"], heartNotes: ["Lavender", "Geranium"], baseNotes: ["Tonka Bean", "Vetiver", "Amber"],
                  moodTags: [.bold, .energetic, .confident],
                  colorAssociations: ColorPreset.dark() + ColorPreset.warm(0.4),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .budget, gender: .masculine,
                  amazonASIN: nil, iconName: "bolt.fill", shortDescription: "Rush of spicy-woody energy",
                  bottleColor: "#1C1C1C", bottleShape: .modern),
        Fragrance(id: "br_coffee_seduction", name: "Coffee Man Seduction", house: "O Boticario",
                  accords: [.gourmand, .oriental, .woody],
                  topNotes: ["Coffee", "Rum", "Cardamom"], heartNotes: ["Cinnamon", "Tonka Bean"], baseNotes: ["Vanilla", "Amber", "Sandalwood"],
                  moodTags: [.sensual, .warm, .bold],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.dark(0.6),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .budget, gender: .masculine,
                  amazonASIN: nil, iconName: "mug.fill", shortDescription: "Seductive rum-coffee with cinnamon warmth",
                  bottleColor: "#2C1810", bottleShape: .square),
        Fragrance(id: "br_zaad_mondo", name: "Zaad Mondo", house: "O Boticario",
                  accords: [.woody, .oriental, .spicy],
                  topNotes: ["Pink Pepper", "Saffron", "Bergamot"], heartNotes: ["Oud", "Cedarwood"], baseNotes: ["Amber", "Vanilla", "Leather"],
                  moodTags: [.opulent, .sophisticated, .warm],
                  colorAssociations: ColorPreset.dark() + ColorPreset.gold(0.5),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "globe", shortDescription: "Oud-saffron world traveler from Zaad premium line",
                  bottleColor: "#3B2F2F", bottleShape: .square),
        Fragrance(id: "br_elysee_succes", name: "Elysee Succes", house: "O Boticario",
                  accords: [.floral, .oriental, .gourmand],
                  topNotes: ["Mandarin", "Rose Petals"], heartNotes: ["Iris", "Jasmine", "Praline"], baseNotes: ["Vanilla", "Amber", "Sandalwood", "Musk"],
                  moodTags: [.elegant, .warm, .opulent],
                  colorAssociations: ColorPreset.gold() + ColorPreset.pink(0.4),
                  seasonality: [.fall, .winter, .spring], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "crown", shortDescription: "Successful woman's iris-praline luxury",
                  bottleColor: "#C5B358", bottleShape: .flacon),
        Fragrance(id: "br_glamour_love", name: "Glamour Love Me", house: "O Boticario",
                  accords: [.fruity, .floral, .gourmand],
                  topNotes: ["Raspberry", "Passion Fruit"], heartNotes: ["Rose", "Peony", "Jasmine"], baseNotes: ["Vanilla", "Musk", "Caramel"],
                  moodTags: [.playful, .romantic, .warm],
                  colorAssociations: ColorPreset.pink() + ColorPreset.warm(0.5),
                  seasonality: [.spring, .fall], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "heart.circle.fill", shortDescription: "Fruity-floral love letter in a bottle",
                  bottleColor: "#FF1493", bottleShape: .flacon),
        Fragrance(id: "br_glamour_dazzle", name: "Glamour Dazzle", house: "O Boticario",
                  accords: [.oriental, .floral, .gourmand],
                  topNotes: ["Bergamot", "Pink Pepper"], heartNotes: ["Rose", "Jasmine", "Orchid"], baseNotes: ["Amber", "Vanilla", "Tonka Bean", "Sandalwood"],
                  moodTags: [.opulent, .sensual, .bold],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.6),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "sparkles", shortDescription: "Dazzling amber-orchid night out glamour",
                  bottleColor: "#DAA520", bottleShape: .flacon),
        Fragrance(id: "br_make_b_rose", name: "Make B. Rose", house: "O Boticario",
                  accords: [.floral, .powdery, .musky],
                  topNotes: ["Rose Petals", "Bergamot"], heartNotes: ["Peony", "Iris", "Magnolia"], baseNotes: ["White Musk", "Sandalwood", "Vanilla"],
                  moodTags: [.romantic, .elegant, .serene],
                  colorAssociations: ColorPreset.pink() + ColorPreset.white(0.5),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "camera.macro", shortDescription: "Pure rose elegance from Boticario's luxury line",
                  bottleColor: "#FFB6C1", bottleShape: .flacon),
    ]

    // MARK: - More Natura (~15)

    static let moreNatura: [Fragrance] = [
        Fragrance(id: "br_luna_radiante", name: "Luna Radiante", house: "Natura",
                  accords: [.floral, .citrus, .fresh],
                  topNotes: ["Bergamot", "Mandarin"], heartNotes: ["Jasmine", "Peony", "Rose"], baseNotes: ["Musk", "Cedar", "Vanilla"],
                  moodTags: [.fresh, .elegant, .playful],
                  colorAssociations: ColorPreset.bright() + ColorPreset.pink(0.4),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "sun.max.fill", shortDescription: "Radiant daytime Luna for sunny Brazilian days",
                  bottleColor: "#FFD700", bottleShape: .tall),
        Fragrance(id: "br_kaiak_ultra", name: "Kaiak Ultra", house: "Natura",
                  accords: [.aromatic, .fresh, .woody],
                  topNotes: ["Grapefruit", "Basil", "Mint"], heartNotes: ["Lavender", "Sage"], baseNotes: ["Cedar", "Vetiver", "Musk"],
                  moodTags: [.energetic, .bold, .fresh],
                  colorAssociations: ColorPreset.cool() + ColorPreset.green(0.4),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .masculine,
                  amazonASIN: nil, iconName: "bolt.fill", shortDescription: "Ultra-fresh herbal energy for active men",
                  bottleColor: "#228B22", bottleShape: .modern),
        Fragrance(id: "br_kriska_envolvente", name: "Kriska Envolvente", house: "Natura",
                  accords: [.oriental, .fruity, .gourmand],
                  topNotes: ["Passion Fruit", "Raspberry"], heartNotes: ["Jasmine", "Praline"], baseNotes: ["Vanilla", "Amber", "Musk"],
                  moodTags: [.sensual, .warm, .playful],
                  colorAssociations: ColorPreset.warm() + ColorPreset.pink(0.5),
                  seasonality: [.fall, .winter], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "heart.fill", shortDescription: "Enveloping passion fruit warmth",
                  bottleColor: "#C71585", bottleShape: .round),
        Fragrance(id: "br_tododia_ameixa", name: "Tododia Ameixa e Flor de Cerejeira", house: "Natura",
                  accords: [.fruity, .floral, .gourmand],
                  topNotes: ["Plum", "Cherry Blossom"], heartNotes: ["Rose", "Peony"], baseNotes: ["Vanilla", "Musk"],
                  moodTags: [.playful, .romantic, .warm],
                  colorAssociations: ColorPreset.pink() + ColorPreset.purple(0.3),
                  seasonality: [.spring, .fall], region: .brazilian, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "camera.macro", shortDescription: "Everyday plum-cherry blossom sweetness",
                  bottleColor: "#DDA0DD", bottleShape: .tall),
        Fragrance(id: "br_humor_proprio", name: "Humor Proprio", house: "Natura",
                  accords: [.aromatic, .fresh, .woody],
                  topNotes: ["Grapefruit", "Mint"], heartNotes: ["Lavender", "Geranium"], baseNotes: ["Musk", "Cedar", "Tonka Bean"],
                  moodTags: [.playful, .fresh, .confident],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer], region: .brazilian, priceTier: .budget, gender: .masculine,
                  amazonASIN: nil, iconName: "face.smiling.fill", shortDescription: "Fun fresh confidence for everyday Brazilian men",
                  bottleColor: "#4169E1", bottleShape: .round),
        Fragrance(id: "br_eudora_edp", name: "Eudora Eau de Parfum", house: "Eudora",
                  accords: [.floral, .oriental, .musky],
                  topNotes: ["Bergamot", "Pink Pepper"], heartNotes: ["Rose", "Jasmine", "Iris"], baseNotes: ["Vanilla", "Sandalwood", "Musk"],
                  moodTags: [.elegant, .warm, .sophisticated],
                  colorAssociations: ColorPreset.gold() + ColorPreset.pink(0.4),
                  seasonality: [.fall, .winter, .spring], region: .brazilian, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "sparkles", shortDescription: "Eudora's signature rose-vanilla sophistication",
                  bottleColor: "#D4AF37", bottleShape: .tall),
    ]
}
