import Foundation

// MARK: - French Market Fragrances
// Sources: Sephora France bestsellers 2025, Fragrance Foundation France Awards, French niche houses

enum FragranceDB_French {
    static let all: [Fragrance] = frenchHouses + frenchNiche + sephraFrBestsellers

    // MARK: - French Heritage Houses (~35)

    static let frenchHouses: [Fragrance] = [
        Fragrance(id: "fr_shalimar", name: "Shalimar", house: "Guerlain",
                  accords: [.oriental, .powdery, .gourmand],
                  topNotes: ["Bergamot", "Lemon", "Cedar"], heartNotes: ["Jasmine", "Rose", "Iris"], baseNotes: ["Vanilla", "Tonka Bean", "Opopanax", "Sandalwood"],
                  moodTags: [.opulent, .vintage, .sensual],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.6) + ColorPreset.dark(0.4),
                  seasonality: [.fall, .winter], region: .french, priceTier: .luxury, gender: .feminine,
                  amazonASIN: "B000C1YX18", iconName: "crown.fill", shortDescription: "1925 oriental legend, vanilla-incense grandeur",
                  bottleColor: "#DAA520", bottleShape: .flacon),
        Fragrance(id: "fr_shalimar_essence", name: "Shalimar L'Essence", house: "Guerlain",
                  accords: [.oriental, .floral, .gourmand],
                  topNotes: ["Bergamot", "Mandarin"], heartNotes: ["Rose", "Jasmine", "Iris"], baseNotes: ["Vanilla", "Sandalwood", "Amber", "Tonka Bean"],
                  moodTags: [.opulent, .elegant, .warm],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.7),
                  seasonality: [.fall, .winter], region: .french, priceTier: .luxury, gender: .feminine,
                  amazonASIN: nil, iconName: "crown.fill", shortDescription: "Fragrantica 2025 women's winner — reimagined Shalimar",
                  bottleColor: "#B8860B", bottleShape: .flacon),
        Fragrance(id: "fr_mon_guerlain", name: "Mon Guerlain", house: "Guerlain",
                  accords: [.oriental, .floral, .gourmand],
                  topNotes: ["Lavender", "Bergamot"], heartNotes: ["Jasmine", "Iris"], baseNotes: ["Vanilla", "Sandalwood", "Coumarin"],
                  moodTags: [.romantic, .warm, .elegant],
                  colorAssociations: ColorPreset.pink() + ColorPreset.gold(0.5) + ColorPreset.warm(0.4),
                  seasonality: [.fall, .winter, .spring], region: .french, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B06XBXJBSR", iconName: "sparkles", shortDescription: "Modern Guerlain: lavender-vanilla tenderness",
                  bottleColor: "#E8B4B8", bottleShape: .flacon),
        Fragrance(id: "fr_petite_robe", name: "La Petite Robe Noire", house: "Guerlain",
                  accords: [.gourmand, .floral, .fruity],
                  topNotes: ["Cherry", "Almond", "Bergamot"], heartNotes: ["Rose", "Peach", "Liquorice"], baseNotes: ["Tonka Bean", "Vanilla", "Tea"],
                  moodTags: [.playful, .elegant, .romantic],
                  colorAssociations: ColorPreset.dark() + ColorPreset.pink(0.5),
                  seasonality: [.spring, .fall], region: .french, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "tshirt.fill", shortDescription: "Little black dress in perfume form — cherry-rose",
                  bottleColor: "#1A1A1A", bottleShape: .flacon),
        Fragrance(id: "fr_vetiver", name: "Vetiver", house: "Guerlain",
                  accords: [.aromatic, .woody, .green],
                  topNotes: ["Lemon", "Neroli", "Bergamot"], heartNotes: ["Vetiver", "Pepper", "Nutmeg"], baseNotes: ["Tobacco", "Tonka Bean", "Cedar"],
                  moodTags: [.sophisticated, .natural, .confident],
                  colorAssociations: ColorPreset.green() + ColorPreset.earthy(0.6),
                  seasonality: [.spring, .summer, .fall], region: .french, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B000C1UNKM", iconName: "leaf.fill", shortDescription: "Definitive vetiver, grassy elegance since 1959",
                  bottleColor: "#6B8E23", bottleShape: .flacon),
        Fragrance(id: "fr_lhomme_ideal", name: "L'Homme Ideal", house: "Guerlain",
                  accords: [.oriental, .aromatic, .gourmand],
                  topNotes: ["Almond", "Bergamot", "Lemon"], heartNotes: ["Cherry", "Rose", "Leather"], baseNotes: ["Vanilla", "Tonka Bean", "Sandalwood"],
                  moodTags: [.warm, .sophisticated, .sensual],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.warm(0.6),
                  seasonality: [.fall, .winter], region: .french, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "person.fill", shortDescription: "Almond-cherry ideal man, French gourmand",
                  bottleColor: "#5D3A1A", bottleShape: .flacon),
        Fragrance(id: "fr_terre_dhermes", name: "Terre d'Hermes", house: "Hermes",
                  accords: [.woody, .citrus, .spicy],
                  topNotes: ["Orange", "Grapefruit", "Flint"], heartNotes: ["Pepper", "Geranium", "Patchouli"], baseNotes: ["Vetiver", "Cedar", "Benzoin"],
                  moodTags: [.sophisticated, .natural, .warm],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.warm(0.5) + ColorPreset.green(0.3),
                  seasonality: [.spring, .summer, .fall], region: .french, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B000GHUWK6", iconName: "mountain.2.fill", shortDescription: "Earth, minerals, and citrus — Hermes masterwork",
                  bottleColor: "#B5651D", bottleShape: .square),
        Fragrance(id: "fr_h24", name: "H24", house: "Hermes",
                  accords: [.aromatic, .green, .woody],
                  topNotes: ["Clary Sage", "Narcissus"], heartNotes: ["Sclarene", "Rosewood"], baseNotes: ["Musk", "Ambroxan"],
                  moodTags: [.minimal, .fresh, .sophisticated],
                  colorAssociations: ColorPreset.neutral() + ColorPreset.green(0.4),
                  seasonality: [.spring, .summer], region: .french, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "clock.fill", shortDescription: "Futuristic green-metallic, Hermes for a new era",
                  bottleColor: "#C0C0C0", bottleShape: .modern),
        Fragrance(id: "fr_jardin_nil", name: "Un Jardin sur le Nil", house: "Hermes",
                  accords: [.green, .citrus, .fruity],
                  topNotes: ["Grapefruit", "Mango", "Lotus"], heartNotes: ["Green Tomato", "Peony", "Calamus"], baseNotes: ["Incense", "Sycamore", "Iris"],
                  moodTags: [.fresh, .playful, .natural],
                  colorAssociations: ColorPreset.green() + ColorPreset.bright(0.6) + ColorPreset.white(0.3),
                  seasonality: [.spring, .summer], region: .french, priceTier: .mid, gender: .unisex,
                  amazonASIN: "B000FQ0QQO", iconName: "leaf.arrow.triangle.circlepath", shortDescription: "Green mango and lotus on the Nile",
                  bottleColor: "#90EE90", bottleShape: .square),
        Fragrance(id: "fr_twilly", name: "Twilly d'Hermes", house: "Hermes",
                  accords: [.floral, .oriental, .spicy],
                  topNotes: ["Ginger"], heartNotes: ["Tuberose"], baseNotes: ["Sandalwood"],
                  moodTags: [.playful, .bold, .warm],
                  colorAssociations: ColorPreset.warm() + ColorPreset.pink(0.5),
                  seasonality: [.spring, .fall], region: .french, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "scribble.variable", shortDescription: "Spicy tuberose wrapped in ginger silk scarves",
                  bottleColor: "#FF6347", bottleShape: .square),
        Fragrance(id: "fr_eau_merveilles", name: "Eau des Merveilles", house: "Hermes",
                  accords: [.woody, .citrus, .aquatic],
                  topNotes: ["Orange", "Lemon"], heartNotes: ["Pink Pepper", "Elemi"], baseNotes: ["Ambergris", "Oak", "Cedar"],
                  moodTags: [.elegant, .mysterious, .fresh],
                  colorAssociations: ColorPreset.gold() + ColorPreset.cool(0.4),
                  seasonality: [.spring, .summer, .fall], region: .french, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "wand.and.stars", shortDescription: "Liquid wood wonder with amber enchantment",
                  bottleColor: "#DAA520", bottleShape: .round),
        Fragrance(id: "fr_sauvage_forte", name: "Sauvage Eau Forte", house: "Dior",
                  accords: [.aromatic, .woody, .fresh],
                  topNotes: ["Bergamot", "Nutmeg"], heartNotes: ["Provençal Lavender", "Ambroxan"], baseNotes: ["Amberwood", "Cedar"],
                  moodTags: [.bold, .sophisticated, .warm],
                  colorAssociations: ColorPreset.dark() + ColorPreset.cool(0.5),
                  seasonality: [.fall, .winter, .spring], region: .french, priceTier: .luxury, gender: .masculine,
                  amazonASIN: nil, iconName: "wind", shortDescription: "2025 FF France men's winner — reformulated Sauvage",
                  bottleColor: "#1A2A4C", bottleShape: .tall),
        Fragrance(id: "fr_dior_homme", name: "Dior Homme", house: "Dior",
                  accords: [.floral, .woody, .powdery],
                  topNotes: ["Lavender", "Bergamot", "Sage"], heartNotes: ["Iris", "Ambrette", "Cardamom"], baseNotes: ["Vetiver", "Cedar", "Leather"],
                  moodTags: [.elegant, .sophisticated, .minimal],
                  colorAssociations: ColorPreset.neutral() + ColorPreset.cool(0.4),
                  seasonality: [.spring, .fall], region: .french, priceTier: .luxury, gender: .masculine,
                  amazonASIN: nil, iconName: "person.fill", shortDescription: "Iris-focused French masculinity, refined and quiet",
                  bottleColor: "#A9A9A9", bottleShape: .tall),
        Fragrance(id: "fr_jadore", name: "J'adore Eau de Parfum", house: "Dior",
                  accords: [.floral, .fruity, .woody],
                  topNotes: ["Pear", "Melon", "Magnolia"], heartNotes: ["Jasmine", "Tuberose", "Rose"], baseNotes: ["Musk", "Vanilla", "Cedar"],
                  moodTags: [.elegant, .warm, .opulent],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.5),
                  seasonality: [.spring, .summer, .fall], region: .french, priceTier: .luxury, gender: .feminine,
                  amazonASIN: nil, iconName: "crown.fill", shortDescription: "Golden goddess bouquet, France's #1 feminine icon",
                  bottleColor: "#FFD700", bottleShape: .tall),
        Fragrance(id: "fr_miss_dior", name: "Miss Dior", house: "Dior",
                  accords: [.floral, .fresh, .fruity],
                  topNotes: ["Blood Orange", "Mandarin"], heartNotes: ["Rose", "Peony", "Lily of the Valley"], baseNotes: ["Patchouli", "Musk", "Rosewood"],
                  moodTags: [.romantic, .elegant, .playful],
                  colorAssociations: ColorPreset.pink() + ColorPreset.white(0.6),
                  seasonality: [.spring, .summer, .fall], region: .french, priceTier: .luxury, gender: .feminine,
                  amazonASIN: nil, iconName: "heart.fill", shortDescription: "#1 women's in France 2025, Parisian rose perfection",
                  bottleColor: "#FFD1DC", bottleShape: .tall),
        Fragrance(id: "fr_dior_addict", name: "Dior Addict", house: "Dior",
                  accords: [.oriental, .floral, .woody],
                  topNotes: ["Mandarin Leaf", "Blood Orange"], heartNotes: ["Jasmine", "Rose", "Orange Blossom"], baseNotes: ["Sandalwood", "Vanilla", "Tonka Bean"],
                  moodTags: [.sensual, .bold, .warm],
                  colorAssociations: ColorPreset.gold() + ColorPreset.dark(0.5),
                  seasonality: [.fall, .winter], region: .french, priceTier: .luxury, gender: .feminine,
                  amazonASIN: nil, iconName: "sparkle", shortDescription: "Addictive jasmine-vanilla luxury",
                  bottleColor: "#B8860B", bottleShape: .tall),
        Fragrance(id: "fr_eau_sauvage", name: "Eau Sauvage", house: "Dior",
                  accords: [.citrus, .aromatic, .woody],
                  topNotes: ["Lemon", "Bergamot", "Basil"], heartNotes: ["Vetiver", "Hedione", "Iris"], baseNotes: ["Oak Moss", "Musk"],
                  moodTags: [.sophisticated, .fresh, .vintage],
                  colorAssociations: ColorPreset.green() + ColorPreset.bright(0.5) + ColorPreset.cool(0.3),
                  seasonality: [.spring, .summer], region: .french, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "wind", shortDescription: "1966 citrus legend, the first Hedione fragrance",
                  bottleColor: "#90EE90", bottleShape: .tall),
        Fragrance(id: "fr_lveb_elixir", name: "La Vie Est Belle L'Elixir", house: "Lancome",
                  accords: [.gourmand, .floral, .oriental],
                  topNotes: ["Raspberry", "Bergamot"], heartNotes: ["Iris", "Orange Blossom", "Rose"], baseNotes: ["Praline", "Vanilla", "Sandalwood", "Amber"],
                  moodTags: [.romantic, .opulent, .warm],
                  colorAssociations: ColorPreset.pink() + ColorPreset.gold(0.6),
                  seasonality: [.fall, .winter], region: .french, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "heart.fill", shortDescription: "2025 FF France women's winner — intensified LVEB",
                  bottleColor: "#C71585", bottleShape: .tall),
        Fragrance(id: "fr_loulou", name: "Loulou", house: "Cacharel",
                  accords: [.oriental, .floral, .powdery],
                  topNotes: ["Mimosa", "Plum"], heartNotes: ["Jasmine", "Ylang-Ylang", "Heliotrope", "Iris"], baseNotes: ["Vanilla", "Tonka Bean", "Sandalwood", "Musk"],
                  moodTags: [.romantic, .warm, .vintage],
                  colorAssociations: ColorPreset.purple() + ColorPreset.warm(0.5),
                  seasonality: [.fall, .winter], region: .french, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "heart.circle.fill", shortDescription: "French vintage oriental, Sephora France top 5",
                  bottleColor: "#6A0DAD", bottleShape: .round),
    ]

    // MARK: - French Niche (~30)

    static let frenchNiche: [Fragrance] = [
        Fragrance(id: "fr_br540", name: "Baccarat Rouge 540", house: "Maison Francis Kurkdjian",
                  accords: [.oriental, .floral, .woody],
                  topNotes: ["Saffron", "Jasmine"], heartNotes: ["Amberwood", "Ambergris"], baseNotes: ["Fir Resin", "Cedar"],
                  moodTags: [.opulent, .mysterious, .elegant],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.6) + ColorPreset.pink(0.3),
                  seasonality: [.fall, .winter, .spring], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "diamond.fill", shortDescription: "Iconic saffron-amber crystal, born in Paris",
                  bottleColor: "#D4A574", bottleShape: .flacon),
        Fragrance(id: "fr_oud_satin", name: "Oud Satin Mood", house: "Maison Francis Kurkdjian",
                  accords: [.oriental, .woody, .floral],
                  topNotes: ["Violet", "Bulgarian Rose"], heartNotes: ["Oud", "Benzoin"], baseNotes: ["Vanilla", "Sandalwood"],
                  moodTags: [.opulent, .warm, .sensual],
                  colorAssociations: ColorPreset.dark() + ColorPreset.gold(0.5),
                  seasonality: [.fall, .winter], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "sparkles", shortDescription: "Rose-oud satin luxury from the MFK atelier",
                  bottleColor: "#800020", bottleShape: .flacon),
        Fragrance(id: "fr_gentle_fluidity", name: "Gentle Fluidity Silver", house: "Maison Francis Kurkdjian",
                  accords: [.woody, .aromatic, .musky],
                  topNotes: ["Juniper Berry", "Nutmeg", "Coriander"], heartNotes: ["Musks"], baseNotes: ["Amber", "Woods", "Vanilla"],
                  moodTags: [.minimal, .serene, .sophisticated],
                  colorAssociations: ColorPreset.neutral() + ColorPreset.cool(0.4),
                  seasonality: [.spring, .summer, .fall, .winter], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "drop.fill", shortDescription: "Juniper-musk fluidity, French minimalist niche",
                  bottleColor: "#C0C0C0", bottleShape: .flacon),
        Fragrance(id: "fr_portrait_lady", name: "Portrait of a Lady", house: "Frederic Malle",
                  accords: [.oriental, .floral, .spicy],
                  topNotes: ["Turkish Rose", "Clove", "Raspberry"], heartNotes: ["Patchouli", "Cinnamon"], baseNotes: ["Sandalwood", "Frankincense", "Musk", "Amber"],
                  moodTags: [.opulent, .bold, .sophisticated],
                  colorAssociations: ColorPreset.warm() + ColorPreset.dark(0.6) + ColorPreset.pink(0.3),
                  seasonality: [.fall, .winter], region: .french, priceTier: .luxury, gender: .feminine,
                  amazonASIN: "B003TXZNTW", iconName: "person.crop.artframe", shortDescription: "Monumental rose-patchouli, a French masterpiece",
                  bottleColor: "#8B0000", bottleShape: .tall),
        Fragrance(id: "fr_musc_ravageur", name: "Musc Ravageur", house: "Frederic Malle",
                  accords: [.oriental, .musky, .spicy],
                  topNotes: ["Bergamot", "Lavender"], heartNotes: ["Cinnamon", "Clove"], baseNotes: ["Musk", "Amber", "Sandalwood", "Vanilla", "Gaiac Wood"],
                  moodTags: [.sensual, .bold, .warm],
                  colorAssociations: ColorPreset.warm() + ColorPreset.dark(0.6) + ColorPreset.gold(0.4),
                  seasonality: [.fall, .winter], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: "B000E82B42", iconName: "flame.fill", shortDescription: "Devastating musk-amber, pure French niche art",
                  bottleColor: "#D2691E", bottleShape: .tall),
        Fragrance(id: "fr_santal_33", name: "Santal 33", house: "Le Labo",
                  accords: [.woody, .aromatic, .leather],
                  topNotes: ["Violet", "Cardamom"], heartNotes: ["Iris", "Ambrox"], baseNotes: ["Australian Sandalwood", "Cedarwood", "Leather", "Musk"],
                  moodTags: [.sophisticated, .minimal, .warm],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.neutral(0.6),
                  seasonality: [.spring, .summer, .fall, .winter], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "leaf.fill", shortDescription: "Smoky sandalwood icon, Le Marais favorite",
                  bottleColor: "#D2B48C", bottleShape: .tall),
        Fragrance(id: "fr_another_13", name: "Another 13", house: "Le Labo",
                  accords: [.musky, .woody, .fresh],
                  topNotes: ["Ambroxan"], heartNotes: ["Jasmine Petals", "Ambrette Seeds"], baseNotes: ["Moss", "Musk", "Woody Notes"],
                  moodTags: [.minimal, .mysterious, .cool],
                  colorAssociations: ColorPreset.neutral() + ColorPreset.cool(0.4),
                  seasonality: [.spring, .summer, .fall, .winter], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "atom", shortDescription: "Invisible second-skin ambroxan, Parisian cool",
                  bottleColor: "#C0C0C0", bottleShape: .tall),
        Fragrance(id: "fr_rose_31", name: "Rose 31", house: "Le Labo",
                  accords: [.floral, .woody, .spicy],
                  topNotes: ["Rose", "Cumin"], heartNotes: ["Cedar", "Oud", "Ambrette"], baseNotes: ["Vetiver", "Amber", "Musk", "Gaiac Wood"],
                  moodTags: [.bold, .sophisticated, .warm],
                  colorAssociations: ColorPreset.pink() + ColorPreset.earthy(0.5),
                  seasonality: [.fall, .winter, .spring], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "camera.macro", shortDescription: "Masculine rose with cumin and cedar edge",
                  bottleColor: "#CD5C5C", bottleShape: .tall),
        Fragrance(id: "fr_philosykos", name: "Philosykos", house: "Diptyque",
                  accords: [.green, .woody, .fruity],
                  topNotes: ["Fig Leaf", "Fig Tree"], heartNotes: ["Green Notes", "Fig Fruit"], baseNotes: ["Cedar", "Coconut Milk", "Woody Notes"],
                  moodTags: [.natural, .serene, .fresh],
                  colorAssociations: ColorPreset.green() + ColorPreset.earthy(0.4),
                  seasonality: [.spring, .summer], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "tree.fill", shortDescription: "Fig garden escape, quintessential Parisian niche",
                  bottleColor: "#6B8E23", bottleShape: .round),
        Fragrance(id: "fr_tam_dao", name: "Tam Dao", house: "Diptyque",
                  accords: [.woody, .aromatic, .spicy],
                  topNotes: ["Rose", "Myrtle"], heartNotes: ["Cypress", "Italian Cypress"], baseNotes: ["Sandalwood", "Cedar", "Musk", "Amber"],
                  moodTags: [.serene, .sophisticated, .warm],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.warm(0.4),
                  seasonality: [.fall, .winter, .spring], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "leaf.fill", shortDescription: "Vietnamese temple sandalwood, meditative depth",
                  bottleColor: "#DEB887", bottleShape: .round),
        Fragrance(id: "fr_do_son", name: "Do Son", house: "Diptyque",
                  accords: [.floral, .aquatic, .musky],
                  topNotes: ["Orange Blossom", "Neroli"], heartNotes: ["Tuberose", "Jasmine"], baseNotes: ["Musk", "Benzoin"],
                  moodTags: [.romantic, .serene, .elegant],
                  colorAssociations: ColorPreset.white() + ColorPreset.green(0.3),
                  seasonality: [.spring, .summer], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "water.waves", shortDescription: "Vietnamese bay tuberose, ethereal and clean",
                  bottleColor: "#F5F5DC", bottleShape: .round),
        Fragrance(id: "fr_ambre_sultan", name: "Ambre Sultan", house: "Serge Lutens",
                  accords: [.oriental, .woody, .spicy],
                  topNotes: ["Oregano", "Bay Leaf", "Myrtle"], heartNotes: ["Amber", "Coriander", "Angelic Root"], baseNotes: ["Sandalwood", "Benzoin", "Vanilla"],
                  moodTags: [.opulent, .warm, .mysterious],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.7) + ColorPreset.earthy(0.5),
                  seasonality: [.fall, .winter], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "flame.fill", shortDescription: "Herb-amber masterwork from the sultan of niche",
                  bottleColor: "#B8860B", bottleShape: .tall),
        Fragrance(id: "fr_fille_berlin", name: "La Fille de Berlin", house: "Serge Lutens",
                  accords: [.floral, .spicy, .woody],
                  topNotes: ["Berry", "Geranium"], heartNotes: ["Rose", "Pepper"], baseNotes: ["Beeswax", "Cedar", "Musk"],
                  moodTags: [.bold, .romantic, .mysterious],
                  colorAssociations: ColorPreset.warm() + ColorPreset.pink(0.6),
                  seasonality: [.fall, .winter, .spring], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "camera.macro", shortDescription: "Berlin girl rose — spicy, dark, unforgettable",
                  bottleColor: "#8B0000", bottleShape: .tall),
        Fragrance(id: "fr_angels_share", name: "Angels' Share", house: "By Kilian",
                  accords: [.oriental, .gourmand, .woody],
                  topNotes: ["Cognac", "Cinnamon"], heartNotes: ["Praline", "Oak", "Tonka Bean"], baseNotes: ["Vanilla", "Sandalwood", "Musk"],
                  moodTags: [.opulent, .warm, .cozy],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.7) + ColorPreset.earthy(0.4),
                  seasonality: [.fall, .winter], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "wineglass.fill", shortDescription: "Cognac-vanilla aging in French oak, Kilian icon",
                  bottleColor: "#8B4513", bottleShape: .flacon),
        Fragrance(id: "fr_angels_paradis", name: "Angels' Share Paradis", house: "By Kilian",
                  accords: [.gourmand, .oriental, .fruity],
                  topNotes: ["Cognac", "Passionfruit"], heartNotes: ["Rose", "Praline", "Cinnamon"], baseNotes: ["Vanilla", "Oak", "Musk"],
                  moodTags: [.opulent, .playful, .warm],
                  colorAssociations: ColorPreset.gold() + ColorPreset.pink(0.4),
                  seasonality: [.fall, .winter], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "wineglass.fill", shortDescription: "Fragrantica 2025 unisex winner — paradisiacal cognac",
                  bottleColor: "#DAA520", bottleShape: .flacon),
        Fragrance(id: "fr_love_shy", name: "Love, Don't Be Shy", house: "By Kilian",
                  accords: [.gourmand, .floral, .oriental],
                  topNotes: ["Neroli", "Pink Pepper"], heartNotes: ["Orange Blossom", "Honeysuckle", "Iris"], baseNotes: ["Marshmallow", "Vanilla", "Sugar", "Musk"],
                  moodTags: [.romantic, .playful, .warm],
                  colorAssociations: ColorPreset.pink() + ColorPreset.gold(0.5),
                  seasonality: [.spring, .fall, .winter], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "heart.fill", shortDescription: "Marshmallow-neroli kiss from Kilian's love collection",
                  bottleColor: "#FFB6C1", bottleShape: .flacon),
        Fragrance(id: "fr_good_gone_bad", name: "Good Girl Gone Bad", house: "By Kilian",
                  accords: [.floral, .fresh, .musky],
                  topNotes: ["Osmanthus", "Rose", "Jasmine"], heartNotes: ["Narcissus", "Tuberose", "May Rose"], baseNotes: ["Amber", "Cedar", "Cashmeran", "Musk"],
                  moodTags: [.bold, .sensual, .elegant],
                  colorAssociations: ColorPreset.pink() + ColorPreset.dark(0.4),
                  seasonality: [.spring, .fall], region: .french, priceTier: .luxury, gender: .feminine,
                  amazonASIN: nil, iconName: "sparkle", shortDescription: "White flowers going dark, French femme fatale",
                  bottleColor: "#FF69B4", bottleShape: .flacon),
        Fragrance(id: "fr_guidance_46", name: "Guidance 46", house: "Amouage",
                  accords: [.oriental, .gourmand, .woody],
                  topNotes: ["Cardamom", "Pink Pepper"], heartNotes: ["Orris", "Cinnamon", "Rose"], baseNotes: ["Amber", "Vanilla", "Sandalwood", "Oud"],
                  moodTags: [.opulent, .warm, .mysterious],
                  colorAssociations: ColorPreset.gold() + ColorPreset.dark(0.5) + ColorPreset.warm(0.4),
                  seasonality: [.fall, .winter], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "compass.drawing", shortDescription: "Fragrantica 2025 overall winner — Omani-French luxury",
                  bottleColor: "#B8860B", bottleShape: .flacon),
        Fragrance(id: "fr_bal_afrique_absolu", name: "Bal d'Afrique Absolu", house: "Byredo",
                  accords: [.woody, .floral, .musky],
                  topNotes: ["African Marigold", "Bergamot"], heartNotes: ["Violet", "Jasmine", "Cyclamen"], baseNotes: ["Vetiver", "Amber", "Musk", "Sandalwood"],
                  moodTags: [.bold, .natural, .warm],
                  colorAssociations: ColorPreset.gold() + ColorPreset.green(0.4),
                  seasonality: [.spring, .summer, .fall], region: .french, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "sun.max.fill", shortDescription: "Fragrantica 2025 unisex pick — intensified Bal d'Afrique",
                  bottleColor: "#DAA520", bottleShape: .tall),
    ]

    // MARK: - Sephora France Bestsellers (International brands popular in France) (~20)

    static let sephraFrBestsellers: [Fragrance] = [
        Fragrance(id: "fr_bleu_chanel", name: "Bleu de Chanel", house: "Chanel",
                  accords: [.woody, .aromatic, .citrus],
                  topNotes: ["Grapefruit", "Lemon", "Mint"], heartNotes: ["Ginger", "Nutmeg", "Jasmine"], baseNotes: ["Sandalwood", "Cedar", "Incense"],
                  moodTags: [.sophisticated, .confident, .elegant],
                  colorAssociations: ColorPreset.cool() + ColorPreset.dark(0.6),
                  seasonality: [.spring, .summer, .fall, .winter], region: .french, priceTier: .luxury, gender: .masculine,
                  amazonASIN: nil, iconName: "circle.fill", shortDescription: "#1 men's in France — refined woody-aromatic power",
                  bottleColor: "#1B2838", bottleShape: .tall),
        Fragrance(id: "fr_allure_sport", name: "Allure Homme Sport", house: "Chanel",
                  accords: [.citrus, .aromatic, .woody],
                  topNotes: ["Mandarin Orange", "Sea Notes"], heartNotes: ["Neroli", "Aldehydes", "Pepper"], baseNotes: ["Tonka Bean", "Cedar", "Vetiver", "White Musk"],
                  moodTags: [.energetic, .fresh, .confident],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer], region: .french, priceTier: .luxury, gender: .masculine,
                  amazonASIN: nil, iconName: "figure.run", shortDescription: "Sporty Chanel citrus for active Frenchmen",
                  bottleColor: "#C0C0C0", bottleShape: .tall),
        Fragrance(id: "fr_gabrielle", name: "Gabrielle Chanel", house: "Chanel",
                  accords: [.floral, .fresh, .musky],
                  topNotes: ["Mandarin Orange", "Grapefruit", "Black Currant"], heartNotes: ["Jasmine", "Ylang-Ylang", "Orange Blossom", "Tuberose"], baseNotes: ["Musk", "Sandalwood", "Cashmeran", "Cedar"],
                  moodTags: [.elegant, .bold, .fresh],
                  colorAssociations: ColorPreset.gold() + ColorPreset.white(0.5),
                  seasonality: [.spring, .summer], region: .french, priceTier: .luxury, gender: .feminine,
                  amazonASIN: nil, iconName: "sparkle", shortDescription: "Radiant four-flower bouquet, Chanel's sunlight",
                  bottleColor: "#FFD700", bottleShape: .tall),
        Fragrance(id: "fr_coco_noir", name: "Coco Noir", house: "Chanel",
                  accords: [.oriental, .woody, .floral],
                  topNotes: ["Grapefruit", "Bergamot"], heartNotes: ["Rose", "Jasmine", "Narcissus", "Geranium"], baseNotes: ["Patchouli", "Sandalwood", "Vanilla", "Tonka Bean"],
                  moodTags: [.mysterious, .elegant, .sensual],
                  colorAssociations: ColorPreset.dark() + ColorPreset.gold(0.4),
                  seasonality: [.fall, .winter], region: .french, priceTier: .luxury, gender: .feminine,
                  amazonASIN: nil, iconName: "moon.fill", shortDescription: "Dark Venetian Chanel with rose-patchouli depth",
                  bottleColor: "#1A1A1A", bottleShape: .tall),
        Fragrance(id: "fr_si_intense", name: "Si Intense", house: "Giorgio Armani",
                  accords: [.oriental, .gourmand, .floral],
                  topNotes: ["Black Currant", "Davana"], heartNotes: ["Rose", "Osmanthus", "Orris"], baseNotes: ["Vanilla", "Patchouli", "Woody Notes", "Musk"],
                  moodTags: [.opulent, .warm, .elegant],
                  colorAssociations: ColorPreset.warm() + ColorPreset.dark(0.5),
                  seasonality: [.fall, .winter], region: .french, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "s.circle.fill", shortDescription: "Sephora France top 5 — intensified Si with vanilla",
                  bottleColor: "#800020", bottleShape: .square),
        Fragrance(id: "fr_encre_noire", name: "Encre Noire", house: "Lalique",
                  accords: [.woody, .aromatic, .green],
                  topNotes: ["Cypress"], heartNotes: ["Vetiver"], baseNotes: ["Musk", "Cashmere Wood"],
                  moodTags: [.mysterious, .minimal, .cool],
                  colorAssociations: ColorPreset.dark() + ColorPreset.green(0.5) + ColorPreset.neutral(0.4),
                  seasonality: [.fall, .winter], region: .french, priceTier: .budget, gender: .masculine,
                  amazonASIN: "B001MKL6AA", iconName: "drop.degreesign.fill", shortDescription: "Dark ink, wet vetiver — France's budget champion",
                  bottleColor: "#0D0D0D", bottleShape: .square),
        Fragrance(id: "fr_adg_parfum", name: "Acqua di Gio Parfum", house: "Giorgio Armani",
                  accords: [.aquatic, .woody, .aromatic],
                  topNotes: ["Bergamot", "Marine Notes"], heartNotes: ["Rosemary", "Clary Sage", "Patchouli"], baseNotes: ["Incense", "Woody Notes"],
                  moodTags: [.fresh, .sophisticated, .bold],
                  colorAssociations: ColorPreset.cool() + ColorPreset.dark(0.4),
                  seasonality: [.spring, .summer, .fall], region: .french, priceTier: .luxury, gender: .masculine,
                  amazonASIN: nil, iconName: "water.waves", shortDescription: "Latest AdG evolution, huge in French market",
                  bottleColor: "#2C3E50", bottleShape: .tall),
        Fragrance(id: "fr_alien", name: "Alien", house: "Mugler",
                  accords: [.oriental, .floral, .woody],
                  topNotes: ["Jasmine Sambac"], heartNotes: ["Cashmeran", "Amber"], baseNotes: ["White Amber", "Cedar", "Tonka Bean"],
                  moodTags: [.mysterious, .bold, .opulent],
                  colorAssociations: ColorPreset.purple() + ColorPreset.gold(0.5) + ColorPreset.dark(0.4),
                  seasonality: [.fall, .winter], region: .french, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "staroflife.fill", shortDescription: "Sephora France top 5 — French-born cosmic jasmine",
                  bottleColor: "#6A0DAD", bottleShape: .flacon),
        Fragrance(id: "fr_angel", name: "Angel", house: "Mugler",
                  accords: [.gourmand, .oriental, .floral],
                  topNotes: ["Helional", "Bergamot", "Coconut"], heartNotes: ["Honey", "Caramel", "Apricot"], baseNotes: ["Patchouli", "Chocolate", "Vanilla"],
                  moodTags: [.bold, .opulent, .cozy],
                  colorAssociations: ColorPreset.purple() + ColorPreset.warm(0.5) + ColorPreset.gold(0.4),
                  seasonality: [.fall, .winter], region: .french, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "star.fill", shortDescription: "Sephora France top 5 — the original gourmand revolution",
                  bottleColor: "#4B0082", bottleShape: .flacon),
        Fragrance(id: "fr_libre", name: "Libre Eau de Parfum", house: "Yves Saint Laurent",
                  accords: [.floral, .oriental, .aromatic],
                  topNotes: ["Mandarin", "Lavender", "Black Currant"], heartNotes: ["Orange Blossom", "Jasmine"], baseNotes: ["Vanilla", "Cedar", "Musk"],
                  moodTags: [.bold, .confident, .elegant],
                  colorAssociations: ColorPreset.gold() + ColorPreset.purple(0.4),
                  seasonality: [.fall, .winter, .spring], region: .french, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "flame", shortDescription: "YSL freedom scent, massive in French market",
                  bottleColor: "#D4AF37", bottleShape: .modern),
        Fragrance(id: "fr_la_nuit", name: "La Nuit de L'Homme", house: "Yves Saint Laurent",
                  accords: [.oriental, .spicy, .woody],
                  topNotes: ["Cardamom", "Bergamot"], heartNotes: ["Lavender", "Cedar"], baseNotes: ["Vetiver", "Caraway", "Coumarin"],
                  moodTags: [.sensual, .mysterious, .sophisticated],
                  colorAssociations: ColorPreset.dark() + ColorPreset.cool(0.5),
                  seasonality: [.fall, .winter], region: .french, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "moon.fill", shortDescription: "Seductive cardamom-lavender, a Paris nightlife icon",
                  bottleColor: "#16213E", bottleShape: .modern),
    ]
}
