import Foundation

// MARK: - Western/US Market Fragrances
// Sources: Amazon US Bestsellers, Sephora, Fragrantica Awards 2025, industry reports

enum FragranceDB_Western {
    static let all: [Fragrance] = mensBestsellers + womensBestsellers + unisexNiche + budgetPicks

    // MARK: - Men's Bestsellers (~55)

    static let mensBestsellers: [Fragrance] = [
        Fragrance(id: "w_sauvage_edt", name: "Sauvage Eau de Toilette", house: "Dior",
                  accords: [.aromatic, .fresh, .spicy],
                  topNotes: ["Calabrian Bergamot", "Pepper"], heartNotes: ["Sichuan Pepper", "Lavender", "Geranium"], baseNotes: ["Ambroxan", "Cedar", "Labdanum"],
                  moodTags: [.bold, .confident, .energetic],
                  colorAssociations: ColorPreset.cool() + ColorPreset.dark(0.7),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .luxury, gender: .masculine,
                  amazonASIN: "B01M65FHWI", iconName: "wind", shortDescription: "Raw, magnetic freshness with a wild edge",
                  bottleColor: "#1A3A5C", bottleShape: .tall),
        Fragrance(id: "w_sauvage_edp", name: "Sauvage Eau de Parfum", house: "Dior",
                  accords: [.aromatic, .woody, .spicy],
                  topNotes: ["Bergamot", "Pepper"], heartNotes: ["Sichuan Pepper", "Lavender", "Star Anise"], baseNotes: ["Ambroxan", "Vanilla", "Cedar"],
                  moodTags: [.bold, .sophisticated, .warm],
                  colorAssociations: ColorPreset.cool() + ColorPreset.dark(0.8),
                  seasonality: [.fall, .winter, .spring], region: .western, priceTier: .luxury, gender: .masculine,
                  amazonASIN: "B07GZD8LW5", iconName: "wind", shortDescription: "Deeper, warmer take on the Sauvage legend",
                  bottleColor: "#1A2A4C", bottleShape: .tall),
        Fragrance(id: "w_sauvage_elixir", name: "Sauvage Elixir", house: "Dior",
                  accords: [.woody, .spicy, .aromatic],
                  topNotes: ["Cinnamon", "Nutmeg", "Cardamom"], heartNotes: ["Lavender", "Licorice"], baseNotes: ["Haitian Vetiver", "Sandalwood", "Amber"],
                  moodTags: [.opulent, .bold, .mysterious],
                  colorAssociations: ColorPreset.dark() + ColorPreset.warm(0.6),
                  seasonality: [.fall, .winter], region: .western, priceTier: .luxury, gender: .masculine,
                  amazonASIN: "B099NJPQL1", iconName: "wind", shortDescription: "Intense spiced elixir, the most concentrated Sauvage",
                  bottleColor: "#0D1B2A", bottleShape: .tall),
        Fragrance(id: "w_bleu_edp", name: "Bleu de Chanel Eau de Parfum", house: "Chanel",
                  accords: [.woody, .aromatic, .citrus],
                  topNotes: ["Grapefruit", "Lemon", "Mint"], heartNotes: ["Ginger", "Nutmeg", "Jasmine"], baseNotes: ["Sandalwood", "Cedar", "Incense"],
                  moodTags: [.sophisticated, .confident, .elegant],
                  colorAssociations: ColorPreset.cool() + ColorPreset.dark(0.6),
                  seasonality: [.spring, .summer, .fall, .winter], region: .western, priceTier: .luxury, gender: .masculine,
                  amazonASIN: "B01MFFH8HU", iconName: "circle.fill", shortDescription: "Refined woody-aromatic with understated power",
                  bottleColor: "#1B2838", bottleShape: .tall),
        Fragrance(id: "w_bleu_edt", name: "Bleu de Chanel Eau de Toilette", house: "Chanel",
                  accords: [.citrus, .aromatic, .woody],
                  topNotes: ["Grapefruit", "Lemon", "Peppermint"], heartNotes: ["Ginger", "Nutmeg", "Iso E Super"], baseNotes: ["Incense", "Cedar", "Vetiver"],
                  moodTags: [.fresh, .confident, .sophisticated],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .luxury, gender: .masculine,
                  amazonASIN: nil, iconName: "circle.fill", shortDescription: "Lighter, crisper Bleu for warm days",
                  bottleColor: "#2A4060", bottleShape: .tall),
        Fragrance(id: "w_adg_edt", name: "Acqua di Gio Eau de Toilette", house: "Giorgio Armani",
                  accords: [.aquatic, .fresh, .citrus],
                  topNotes: ["Calabrian Bergamot", "Neroli", "Green Tangerine"], heartNotes: ["Marine Notes", "Rosemary", "Jasmine"], baseNotes: ["White Musk", "Cedar", "Patchouli"],
                  moodTags: [.fresh, .serene, .natural],
                  colorAssociations: ColorPreset.cool() + ColorPreset.white(0.6) + ColorPreset.green(0.4),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B000E7WY2K", iconName: "water.waves", shortDescription: "Crystal-clear Mediterranean freshness",
                  bottleColor: "#87CEEB", bottleShape: .tall),
        Fragrance(id: "w_adg_profumo", name: "Acqua di Gio Profumo", house: "Giorgio Armani",
                  accords: [.aquatic, .aromatic, .woody],
                  topNotes: ["Bergamot", "Marine Notes", "Rosemary"], heartNotes: ["Geranium", "Sage", "Amber"], baseNotes: ["Patchouli", "Incense", "Oud"],
                  moodTags: [.sophisticated, .confident, .fresh],
                  colorAssociations: ColorPreset.cool() + ColorPreset.dark(0.5),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .luxury, gender: .masculine,
                  amazonASIN: "B00P8FMWKA", iconName: "water.waves", shortDescription: "Deeper, smokier evolution of Acqua di Gio",
                  bottleColor: "#2C3E50", bottleShape: .tall),
        Fragrance(id: "w_adg_profondo", name: "Acqua di Gio Profondo", house: "Giorgio Armani",
                  accords: [.aquatic, .woody, .aromatic],
                  topNotes: ["Green Mandarin", "Aquatic Notes", "Bergamot"], heartNotes: ["Cypress", "Rosemary", "Lavender"], baseNotes: ["Mineral Amber", "Musk", "Patchouli"],
                  moodTags: [.fresh, .bold, .natural],
                  colorAssociations: ColorPreset.cool() + ColorPreset.dark(0.4),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B0851CSYJP", iconName: "water.waves", shortDescription: "Ocean-depth freshness with mineral amber",
                  bottleColor: "#1B4F72", bottleShape: .tall),
        Fragrance(id: "w_eros_edt", name: "Eros Eau de Toilette", house: "Versace",
                  accords: [.fresh, .aromatic, .woody],
                  topNotes: ["Mint", "Green Apple", "Lemon"], heartNotes: ["Tonka Bean", "Ambroxan", "Geranium"], baseNotes: ["Vanilla", "Vetiver", "Oak Moss", "Cedar"],
                  moodTags: [.bold, .energetic, .confident],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.6),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B009ORIA88", iconName: "bolt.fill", shortDescription: "Fresh, vibrant power inspired by Greek mythology",
                  bottleColor: "#1E90FF", bottleShape: .modern),
        Fragrance(id: "w_eros_edp", name: "Eros Eau de Parfum", house: "Versace",
                  accords: [.oriental, .aromatic, .woody],
                  topNotes: ["Mint", "Green Apple", "Cedarwood"], heartNotes: ["Tonka Bean", "Vanilla", "Geranium"], baseNotes: ["Sandalwood", "Vetiver", "Leather"],
                  moodTags: [.bold, .sensual, .warm],
                  colorAssociations: ColorPreset.dark() + ColorPreset.cool(0.5),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "bolt.fill", shortDescription: "Richer, darker Eros with leather and sandalwood",
                  bottleColor: "#0D47A1", bottleShape: .modern),
        Fragrance(id: "w_dylan_blue", name: "Dylan Blue", house: "Versace",
                  accords: [.aromatic, .fresh, .woody],
                  topNotes: ["Calabrian Bergamot", "Grapefruit", "Fig Leaf"], heartNotes: ["Violet Leaf", "Papyrus", "Ambroxan"], baseNotes: ["Musk", "Tonka Bean", "Saffron"],
                  moodTags: [.confident, .fresh, .sophisticated],
                  colorAssociations: ColorPreset.cool() + ColorPreset.dark(0.4),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B01MSBK31M", iconName: "drop.fill", shortDescription: "Mediterranean blue spirit with fig and violet",
                  bottleColor: "#1565C0", bottleShape: .modern),
        Fragrance(id: "w_pour_homme", name: "Versace Pour Homme", house: "Versace",
                  accords: [.citrus, .aromatic, .aquatic],
                  topNotes: ["Lemon", "Neroli", "Bergamot"], heartNotes: ["Hyacinth", "Cedar", "Sage"], baseNotes: ["Amber", "Musk"],
                  moodTags: [.fresh, .elegant, .serene],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B000VHDDMQ", iconName: "drop.fill", shortDescription: "Clean Mediterranean citrus-amber refinement",
                  bottleColor: "#4FC3F7", bottleShape: .modern),
        Fragrance(id: "w_1million_edt", name: "1 Million Eau de Toilette", house: "Paco Rabanne",
                  accords: [.spicy, .leather, .woody],
                  topNotes: ["Grapefruit", "Blood Mandarin", "Peppermint"], heartNotes: ["Rose", "Cinnamon"], baseNotes: ["Leather", "Amber", "Woody Notes"],
                  moodTags: [.bold, .confident, .rebellious],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.6),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B001Q4XLMI", iconName: "dollarsign.circle.fill", shortDescription: "Audacious spicy leather with liquid gold swagger",
                  bottleColor: "#FFD700", bottleShape: .modern),
        Fragrance(id: "w_invictus", name: "Invictus", house: "Paco Rabanne",
                  accords: [.aquatic, .fresh, .woody],
                  topNotes: ["Marine Notes", "Grapefruit", "Mandarin"], heartNotes: ["Bay Leaf", "Jasmine"], baseNotes: ["Guaiac Wood", "Patchouli", "Oak Moss", "Ambergris"],
                  moodTags: [.energetic, .bold, .confident],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.6),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B00CO8BOFC", iconName: "trophy.fill", shortDescription: "Athletic fresh aquatic for champions",
                  bottleColor: "#C0C0C0", bottleShape: .modern),
        Fragrance(id: "w_invictus_victory", name: "Invictus Victory", house: "Paco Rabanne",
                  accords: [.aromatic, .oriental, .woody],
                  topNotes: ["Laurel Leaf", "Black Pepper"], heartNotes: ["Incense", "Cardamom"], baseNotes: ["Amber", "Benzoin", "Guaiac Wood"],
                  moodTags: [.bold, .opulent, .warm],
                  colorAssociations: ColorPreset.warm() + ColorPreset.gold(0.6),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "trophy.fill", shortDescription: "Incense-amber triumph, richer and darker",
                  bottleColor: "#B8860B", bottleShape: .modern),
        Fragrance(id: "w_ysl_y_edp", name: "Y Eau de Parfum", house: "Yves Saint Laurent",
                  accords: [.aromatic, .woody, .fresh],
                  topNotes: ["Apple", "Ginger", "Bergamot"], heartNotes: ["Sage", "Juniper Berries", "Geranium"], baseNotes: ["Amberwood", "Tonka Bean", "Cedar", "Vetiver"],
                  moodTags: [.confident, .bold, .sophisticated],
                  colorAssociations: ColorPreset.dark() + ColorPreset.cool(0.5),
                  seasonality: [.spring, .fall, .winter], region: .western, priceTier: .luxury, gender: .masculine,
                  amazonASIN: "B07K2STWGJ", iconName: "y.circle.fill", shortDescription: "Bold apple-sage with amberwood depth",
                  bottleColor: "#1A1A2E", bottleShape: .modern),
        Fragrance(id: "w_la_nuit", name: "La Nuit de L'Homme", house: "Yves Saint Laurent",
                  accords: [.oriental, .spicy, .woody],
                  topNotes: ["Cardamom", "Bergamot"], heartNotes: ["Lavender", "Cedar", "Virginian Cedar"], baseNotes: ["Vetiver", "Caraway", "Coumarin"],
                  moodTags: [.sensual, .mysterious, .sophisticated],
                  colorAssociations: ColorPreset.dark() + ColorPreset.cool(0.5) + ColorPreset.purple(0.3),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B0030UQNA2", iconName: "moon.fill", shortDescription: "Seductive cardamom-lavender for the night",
                  bottleColor: "#16213E", bottleShape: .modern),
        Fragrance(id: "w_the_one_edp", name: "The One Eau de Parfum", house: "Dolce & Gabbana",
                  accords: [.oriental, .spicy, .woody],
                  topNotes: ["Grapefruit", "Coriander", "Basil"], heartNotes: ["Cardamom", "Ginger", "Orange Blossom"], baseNotes: ["Amber", "Cedar", "Labdanum"],
                  moodTags: [.sophisticated, .warm, .elegant],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.6) + ColorPreset.dark(0.4),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B001FQXZOM", iconName: "crown", shortDescription: "Warm ginger-cardamom elegance with amber depth",
                  bottleColor: "#8B6914", bottleShape: .square),
        Fragrance(id: "w_light_blue_ph", name: "Light Blue Pour Homme", house: "Dolce & Gabbana",
                  accords: [.citrus, .aquatic, .woody],
                  topNotes: ["Grapefruit", "Bergamot", "Mandarin"], heartNotes: ["Rosewood", "Pepper", "Rosemary"], baseNotes: ["Musk", "Oak Moss", "Incense"],
                  moodTags: [.fresh, .energetic, .playful],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.7),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B000GKVBQ2", iconName: "sun.max.fill", shortDescription: "Mediterranean sun and citrus energy",
                  bottleColor: "#87CEEB", bottleShape: .square),
        Fragrance(id: "w_explorer", name: "Explorer", house: "Montblanc",
                  accords: [.aromatic, .woody, .leather],
                  topNotes: ["Bergamot", "Pink Pepper", "Clary Sage"], heartNotes: ["Leather", "Vetiver"], baseNotes: ["Indonesian Patchouli", "Akigalawood", "Cacao"],
                  moodTags: [.bold, .natural, .confident],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.green(0.6) + ColorPreset.dark(0.5),
                  seasonality: [.fall, .winter, .spring], region: .western, priceTier: .budget, gender: .masculine,
                  amazonASIN: "B07LFG5N8P", iconName: "mountain.2.fill", shortDescription: "Rugged vetiver-leather adventure at great value",
                  bottleColor: "#2F4F4F", bottleShape: .square),
        Fragrance(id: "w_legend", name: "Legend", house: "Montblanc",
                  accords: [.aromatic, .fresh, .woody],
                  topNotes: ["Bergamot", "Pineapple", "Lavender"], heartNotes: ["Rose", "Geranium", "Coumarin"], baseNotes: ["Sandalwood", "Tonka Bean", "Oak Moss"],
                  moodTags: [.confident, .fresh, .elegant],
                  colorAssociations: ColorPreset.cool() + ColorPreset.neutral(0.5),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .budget, gender: .masculine,
                  amazonASIN: "B005NPA03U", iconName: "mountain.2.fill", shortDescription: "Classic fresh fougere for everyday confidence",
                  bottleColor: "#3D5A80", bottleShape: .square),
        Fragrance(id: "w_aventus", name: "Aventus", house: "Creed",
                  accords: [.fruity, .woody, .fresh],
                  topNotes: ["Pineapple", "Bergamot", "Black Currant", "Apple"], heartNotes: ["Birch", "Patchouli", "Moroccan Jasmine", "Rose"], baseNotes: ["Musk", "Oak Moss", "Ambergris", "Vanilla"],
                  moodTags: [.confident, .bold, .sophisticated],
                  colorAssociations: ColorPreset.dark() + ColorPreset.green(0.5) + ColorPreset.gold(0.6),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .luxury, gender: .masculine,
                  amazonASIN: "B004LDA71O", iconName: "crown.fill", shortDescription: "Legendary fruity-smoky power fragrance",
                  bottleColor: "#2E4057", bottleShape: .flacon),
        Fragrance(id: "w_green_irish", name: "Green Irish Tweed", house: "Creed",
                  accords: [.green, .aromatic, .woody],
                  topNotes: ["Lemon Verbena", "Iris"], heartNotes: ["Violet Leaf", "French Verbena"], baseNotes: ["Ambergris", "Mysore Sandalwood"],
                  moodTags: [.elegant, .natural, .sophisticated],
                  colorAssociations: ColorPreset.green() + ColorPreset.cool(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .luxury, gender: .masculine,
                  amazonASIN: nil, iconName: "leaf.fill", shortDescription: "Irish countryside green elegance, timeless classic",
                  bottleColor: "#2D6A4F", bottleShape: .flacon),
        Fragrance(id: "w_terre_dhermes", name: "Terre d'Hermes", house: "Hermes",
                  accords: [.woody, .citrus, .spicy],
                  topNotes: ["Orange", "Grapefruit", "Flint"], heartNotes: ["Pepper", "Geranium", "Patchouli"], baseNotes: ["Vetiver", "Cedar", "Benzoin"],
                  moodTags: [.sophisticated, .natural, .warm],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.warm(0.5) + ColorPreset.green(0.3),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B000GHUWK6", iconName: "mountain.2.fill", shortDescription: "Earth, minerals, and citrus — Hermes masterwork",
                  bottleColor: "#B5651D", bottleShape: .square),
        Fragrance(id: "w_spicebomb_ext", name: "Spicebomb Extreme", house: "Viktor & Rolf",
                  accords: [.oriental, .spicy, .gourmand],
                  topNotes: ["Black Pepper", "Lavender"], heartNotes: ["Cinnamon", "Caraway"], baseNotes: ["Tobacco", "Vanilla"],
                  moodTags: [.bold, .warm, .sensual],
                  colorAssociations: ColorPreset.warm() + ColorPreset.dark(0.7),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B01N0MYIIP", iconName: "flame.fill", shortDescription: "Explosive spice-tobacco warmth, winter essential",
                  bottleColor: "#8B0000", bottleShape: .round),
        Fragrance(id: "w_polo_blue", name: "Polo Blue", house: "Ralph Lauren",
                  accords: [.aquatic, .fresh, .woody],
                  topNotes: ["Cucumber Melon", "Washed Suede"], heartNotes: ["Basil Verveina", "Sage Leaf"], baseNotes: ["Woodsy Musk", "Suede"],
                  moodTags: [.fresh, .natural, .confident],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B000GHUWHA", iconName: "figure.equestrian.sports", shortDescription: "Clean blue freshness with sporty elegance",
                  bottleColor: "#4169E1", bottleShape: .tall),
        Fragrance(id: "w_guilty_ph", name: "Guilty Pour Homme", house: "Gucci",
                  accords: [.aromatic, .woody, .spicy],
                  topNotes: ["Lavender", "Lemon"], heartNotes: ["Orange Blossom", "Neroli"], baseNotes: ["Cedar", "Patchouli"],
                  moodTags: [.bold, .rebellious, .confident],
                  colorAssociations: ColorPreset.dark() + ColorPreset.warm(0.4),
                  seasonality: [.spring, .fall], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B004CSZK9M", iconName: "g.circle.fill", shortDescription: "Urban lavender-neroli rebellion",
                  bottleColor: "#2C2C2C", bottleShape: .square),
        Fragrance(id: "w_most_wanted", name: "The Most Wanted", house: "Azzaro",
                  accords: [.oriental, .spicy, .woody],
                  topNotes: ["Cardamom", "Toffee"], heartNotes: ["Chestnut", "Hazelnut"], baseNotes: ["Amber", "Patchouli", "Woody Notes"],
                  moodTags: [.bold, .warm, .sensual],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.7),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "flame", shortDescription: "Irresistible toffee-cardamom magnetism",
                  bottleColor: "#DAA520", bottleShape: .round),
        Fragrance(id: "w_luna_rossa_carbon", name: "Luna Rossa Carbon", house: "Prada",
                  accords: [.aromatic, .fresh, .woody],
                  topNotes: ["Bergamot", "Lavender"], heartNotes: ["Ambroxan", "Metallic Notes"], baseNotes: ["Amberwood", "Patchouli"],
                  moodTags: [.bold, .minimal, .confident],
                  colorAssociations: ColorPreset.dark() + ColorPreset.cool(0.5),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .luxury, gender: .masculine,
                  amazonASIN: "B071X7VBJ7", iconName: "car.fill", shortDescription: "Sleek lavender-ambroxan with carbon edge",
                  bottleColor: "#1C1C1C", bottleShape: .square),
        Fragrance(id: "w_stronger_with_you", name: "Stronger With You Intensely", house: "Emporio Armani",
                  accords: [.oriental, .gourmand, .spicy],
                  topNotes: ["Pink Pepper", "Violet", "Juniper"], heartNotes: ["Toffee", "Cinnamon", "Sage"], baseNotes: ["Vanilla", "Amber", "Suede"],
                  moodTags: [.warm, .sensual, .cozy],
                  colorAssociations: ColorPreset.warm() + ColorPreset.gold(0.5),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B07QSPWQMQ", iconName: "heart.fill", shortDescription: "Warm toffee-vanilla embrace, cozy and sweet",
                  bottleColor: "#8B4513", bottleShape: .square),
        Fragrance(id: "w_le_male_edt", name: "Le Male Eau de Toilette", house: "Jean Paul Gaultier",
                  accords: [.oriental, .aromatic, .fresh],
                  topNotes: ["Mint", "Lavender", "Bergamot", "Artemisia"], heartNotes: ["Orange Blossom", "Cinnamon", "Cumin"], baseNotes: ["Vanilla", "Tonka Bean", "Cedar", "Amber", "Sandalwood"],
                  moodTags: [.bold, .sensual, .playful],
                  colorAssociations: ColorPreset.cool() + ColorPreset.warm(0.4),
                  seasonality: [.spring, .fall, .winter], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B000C1V0JK", iconName: "figure.stand", shortDescription: "Iconic mint-vanilla sailor in a torso bottle",
                  bottleColor: "#5B8DBE", bottleShape: .modern),
        Fragrance(id: "w_le_male_parfum", name: "Le Male Le Parfum", house: "Jean Paul Gaultier",
                  accords: [.oriental, .gourmand, .woody],
                  topNotes: ["Cardamom", "Iris"], heartNotes: ["Lavender", "Vanilla"], baseNotes: ["Woody Notes", "Leather"],
                  moodTags: [.sensual, .sophisticated, .warm],
                  colorAssociations: ColorPreset.dark() + ColorPreset.warm(0.6),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "figure.stand", shortDescription: "Intensified Le Male with iris and leather depth",
                  bottleColor: "#2E1A47", bottleShape: .modern),
        Fragrance(id: "w_boss_bottled", name: "Boss Bottled", house: "Hugo Boss",
                  accords: [.woody, .aromatic, .spicy],
                  topNotes: ["Apple", "Citrus", "Plum"], heartNotes: ["Geranium", "Cinnamon", "Carnation"], baseNotes: ["Sandalwood", "Cedar", "Vetiver", "Olive Tree"],
                  moodTags: [.sophisticated, .confident, .elegant],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.gold(0.6) + ColorPreset.neutral(0.5),
                  seasonality: [.spring, .fall, .winter], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B000E7Y5J0", iconName: "briefcase.fill", shortDescription: "Polished apple-cinnamon for the boardroom",
                  bottleColor: "#C9B037", bottleShape: .square),
        Fragrance(id: "w_oud_wood", name: "Oud Wood", house: "Tom Ford",
                  accords: [.woody, .oriental, .spicy],
                  topNotes: ["Oud", "Rosewood", "Cardamom"], heartNotes: ["Sandalwood", "Vetiver", "Tonka Bean"], baseNotes: ["Amber", "Synthetic Oud"],
                  moodTags: [.opulent, .sophisticated, .warm],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.dark(0.8) + ColorPreset.gold(0.6),
                  seasonality: [.fall, .winter], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: "B0042AYPHY", iconName: "leaf.fill", shortDescription: "Smoky, exotic oud wrapped in creamy sandalwood",
                  bottleColor: "#4A3728", bottleShape: .square),
        Fragrance(id: "w_tobacco_vanille", name: "Tobacco Vanille", house: "Tom Ford",
                  accords: [.oriental, .gourmand, .spicy],
                  topNotes: ["Tobacco Leaf", "Spicy Notes"], heartNotes: ["Vanilla", "Cacao", "Tonka Bean"], baseNotes: ["Dried Fruits", "Woody Notes"],
                  moodTags: [.opulent, .warm, .cozy],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.warm(0.7) + ColorPreset.dark(0.6),
                  seasonality: [.fall, .winter], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: "B0018OHBMG", iconName: "flame.fill", shortDescription: "Rich tobacco leaves drenched in sweet vanilla",
                  bottleColor: "#5D3A1A", bottleShape: .square),
        Fragrance(id: "w_noir_extreme", name: "Noir Extreme", house: "Tom Ford",
                  accords: [.oriental, .gourmand, .woody],
                  topNotes: ["Mandarin", "Saffron", "Cardamom", "Nutmeg"], heartNotes: ["Rose Absolute", "Jasmine", "Orange Blossom"], baseNotes: ["Sandalwood", "Amber", "Vanilla", "Woody Notes"],
                  moodTags: [.opulent, .warm, .sensual],
                  colorAssociations: ColorPreset.dark() + ColorPreset.gold(0.6) + ColorPreset.warm(0.5),
                  seasonality: [.fall, .winter], region: .western, priceTier: .luxury, gender: .masculine,
                  amazonASIN: "B01LXHTEZ2", iconName: "moon.stars.fill", shortDescription: "Rich amber-saffron indulgence, evening opulence",
                  bottleColor: "#1A0F0A", bottleShape: .square),
        Fragrance(id: "w_ombre_leather", name: "Ombre Leather", house: "Tom Ford",
                  accords: [.leather, .woody, .spicy],
                  topNotes: ["Cardamom", "Violet Leaf"], heartNotes: ["Leather", "Jasmine Sambac"], baseNotes: ["Patchouli", "Moss", "Amber"],
                  moodTags: [.bold, .sophisticated, .mysterious],
                  colorAssociations: ColorPreset.dark() + ColorPreset.earthy(0.6),
                  seasonality: [.fall, .winter], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: "B07HLKBH76", iconName: "bag.fill", shortDescription: "Rich leather with jasmine and dark patchouli",
                  bottleColor: "#3B2F2F", bottleShape: .square),
        Fragrance(id: "w_born_in_roma_u", name: "Born in Roma Uomo", house: "Valentino",
                  accords: [.aromatic, .woody, .spicy],
                  topNotes: ["Ginger", "Mineral Sage"], heartNotes: ["Smoked Vetiver", "Guaiac Wood"], baseNotes: ["Bourbon Vanilla", "Cashmeran"],
                  moodTags: [.confident, .bold, .sophisticated],
                  colorAssociations: ColorPreset.dark() + ColorPreset.warm(0.5),
                  seasonality: [.fall, .winter, .spring], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "building.columns.fill", shortDescription: "Smoked vetiver and vanilla with ginger spark",
                  bottleColor: "#2C3333", bottleShape: .modern),
        Fragrance(id: "w_phantom", name: "Phantom", house: "Paco Rabanne",
                  accords: [.aromatic, .fresh, .woody],
                  topNotes: ["Lemon", "Lavender"], heartNotes: ["Apple", "Smoky Notes"], baseNotes: ["Vanilla", "Cashmeran", "Lavender"],
                  moodTags: [.energetic, .bold, .playful],
                  colorAssociations: ColorPreset.cool() + ColorPreset.neutral(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "antenna.radiowaves.left.and.right", shortDescription: "Futuristic lavender-vanilla robot spirit",
                  bottleColor: "#708090", bottleShape: .modern),
        Fragrance(id: "w_scandal_ph", name: "Scandal Pour Homme", house: "Jean Paul Gaultier",
                  accords: [.oriental, .gourmand, .woody],
                  topNotes: ["Orange", "Mandarin"], heartNotes: ["Caramel Popcorn", "Tonka Bean"], baseNotes: ["Woodsy Notes", "Vetiver", "Leather"],
                  moodTags: [.playful, .bold, .warm],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.6),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "exclamationmark.triangle.fill", shortDescription: "Rebellious caramel-leather with popcorn twist",
                  bottleColor: "#B8860B", bottleShape: .modern),
        Fragrance(id: "w_gentleman_edp", name: "Gentleman Eau de Parfum", house: "Givenchy",
                  accords: [.oriental, .woody, .spicy],
                  topNotes: ["Pepper", "Lavender", "Cardamom"], heartNotes: ["Iris", "Orris", "Orange Blossom"], baseNotes: ["Tolu Balsam", "Patchouli", "Black Vanilla"],
                  moodTags: [.sophisticated, .elegant, .warm],
                  colorAssociations: ColorPreset.dark() + ColorPreset.warm(0.4),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: nil, iconName: "person.fill", shortDescription: "Dark iris elegance with lavender and vanilla",
                  bottleColor: "#1A1A1A", bottleShape: .square),
        Fragrance(id: "w_layton", name: "Layton", house: "Parfums de Marly",
                  accords: [.oriental, .fresh, .spicy],
                  topNotes: ["Apple", "Bergamot", "Mandarin"], heartNotes: ["Jasmine", "Violet", "Lavender"], baseNotes: ["Vanilla", "Pepper", "Sandalwood", "Cashmeran", "Guaiac Wood"],
                  moodTags: [.sophisticated, .bold, .elegant],
                  colorAssociations: ColorPreset.dark() + ColorPreset.cool(0.4) + ColorPreset.gold(0.3),
                  seasonality: [.fall, .winter, .spring], region: .western, priceTier: .luxury, gender: .masculine,
                  amazonASIN: "B075V2DX5Q", iconName: "shield.fill", shortDescription: "Apple-vanilla sophistication with lavender heart",
                  bottleColor: "#2B2B52", bottleShape: .flacon),
        Fragrance(id: "w_pegasus", name: "Pegasus", house: "Parfums de Marly",
                  accords: [.oriental, .gourmand, .woody],
                  topNotes: ["Heliotrope", "Almond"], heartNotes: ["Jasmine", "Vanilla"], baseNotes: ["Sandalwood", "Amber", "Oud"],
                  moodTags: [.opulent, .warm, .elegant],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.6),
                  seasonality: [.fall, .winter], region: .western, priceTier: .luxury, gender: .masculine,
                  amazonASIN: nil, iconName: "shield.fill", shortDescription: "Almond-vanilla-sandalwood Arabian luxury",
                  bottleColor: "#C5B358", bottleShape: .flacon),
        Fragrance(id: "w_armani_code", name: "Armani Code", house: "Giorgio Armani",
                  accords: [.oriental, .woody, .aromatic],
                  topNotes: ["Bergamot", "Lemon"], heartNotes: ["Olive Blossom", "Star Anise"], baseNotes: ["Leather", "Tobacco", "Guaiac Wood", "Tonka Bean"],
                  moodTags: [.sensual, .sophisticated, .mysterious],
                  colorAssociations: ColorPreset.dark() + ColorPreset.warm(0.4),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B000E7YCXG", iconName: "lock.fill", shortDescription: "Seductive olive blossom and tobacco mystery",
                  bottleColor: "#0A0A0A", bottleShape: .tall),
        Fragrance(id: "w_jimmy_choo_man", name: "Jimmy Choo Man", house: "Jimmy Choo",
                  accords: [.aromatic, .woody, .fruity],
                  topNotes: ["Honeydew Melon", "Mandarin", "Lavender"], heartNotes: ["Patchouli", "Pink Pepper", "Suede"], baseNotes: ["Amber", "Sandalwood"],
                  moodTags: [.confident, .sophisticated, .bold],
                  colorAssociations: ColorPreset.dark() + ColorPreset.neutral(0.5),
                  seasonality: [.spring, .fall], region: .western, priceTier: .mid, gender: .masculine,
                  amazonASIN: "B00HO2K9V6", iconName: "shoe.fill", shortDescription: "Suede and melon sophistication, modern luxury",
                  bottleColor: "#36454F", bottleShape: .square),
    ]

    // MARK: - Women's Bestsellers (~55)

    static let womensBestsellers: [Fragrance] = [
        Fragrance(id: "w_chanelno5", name: "No. 5 Eau de Parfum", house: "Chanel",
                  accords: [.floral, .powdery, .woody],
                  topNotes: ["Aldehydes", "Ylang-Ylang", "Neroli"], heartNotes: ["Rose", "Jasmine", "Iris"], baseNotes: ["Sandalwood", "Vanilla", "Vetiver"],
                  moodTags: [.elegant, .sophisticated, .vintage],
                  colorAssociations: ColorPreset.gold() + ColorPreset.white(0.8) + ColorPreset.pink(0.5),
                  seasonality: [.spring, .fall, .winter], region: .western, priceTier: .luxury, gender: .feminine,
                  amazonASIN: "B000C1V0LG", iconName: "sparkles", shortDescription: "Timeless floral elegance, the icon of luxury",
                  bottleColor: "#FFD700", bottleShape: .tall),
        Fragrance(id: "w_coco_mademoiselle", name: "Coco Mademoiselle", house: "Chanel",
                  accords: [.floral, .citrus, .oriental],
                  topNotes: ["Orange", "Mandarin", "Bergamot"], heartNotes: ["Rose", "Jasmine", "Lychee"], baseNotes: ["Musk", "Vanilla", "Patchouli", "Vetiver"],
                  moodTags: [.elegant, .confident, .sophisticated],
                  colorAssociations: ColorPreset.gold() + ColorPreset.pink(0.6) + ColorPreset.warm(0.4),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .luxury, gender: .feminine,
                  amazonASIN: "B000GH5HN6", iconName: "wand.and.stars", shortDescription: "Fresh oriental elegance with citrus sparkle",
                  bottleColor: "#FFDAB9", bottleShape: .tall),
        Fragrance(id: "w_chance_tendre", name: "Chance Eau Tendre", house: "Chanel",
                  accords: [.floral, .fruity, .musky],
                  topNotes: ["Quince", "Grapefruit"], heartNotes: ["Hyacinth", "Jasmine"], baseNotes: ["White Musk", "Iris", "Amber", "Cedar"],
                  moodTags: [.playful, .fresh, .romantic],
                  colorAssociations: ColorPreset.pink() + ColorPreset.bright(0.6) + ColorPreset.white(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .luxury, gender: .feminine,
                  amazonASIN: "B001V6OQXQ", iconName: "sparkle", shortDescription: "Soft, flirtatious grapefruit-jasmine radiance",
                  bottleColor: "#FFB6C1", bottleShape: .round),
        Fragrance(id: "w_miss_dior", name: "Miss Dior Eau de Parfum", house: "Dior",
                  accords: [.floral, .fresh, .fruity],
                  topNotes: ["Blood Orange", "Mandarin"], heartNotes: ["Rose", "Peony", "Lily of the Valley"], baseNotes: ["Patchouli", "Musk", "Rosewood"],
                  moodTags: [.romantic, .elegant, .playful],
                  colorAssociations: ColorPreset.pink() + ColorPreset.white(0.6),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B00GBYALRA", iconName: "heart.fill", shortDescription: "Parisian chic: rose-peony with citrus sparkle",
                  bottleColor: "#FFD1DC", bottleShape: .tall),
        Fragrance(id: "w_jadore", name: "J'adore Eau de Parfum", house: "Dior",
                  accords: [.floral, .fruity, .woody],
                  topNotes: ["Pear", "Melon", "Magnolia"], heartNotes: ["Jasmine", "Tuberose", "Rose"], baseNotes: ["Musk", "Vanilla", "Cedar", "Blackberry"],
                  moodTags: [.elegant, .warm, .opulent],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.5),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .luxury, gender: .feminine,
                  amazonASIN: "B000C1VOBC", iconName: "crown.fill", shortDescription: "Golden goddess bouquet, pure floral luxury",
                  bottleColor: "#FFD700", bottleShape: .tall),
        Fragrance(id: "w_black_opium", name: "Black Opium", house: "Yves Saint Laurent",
                  accords: [.oriental, .gourmand, .floral],
                  topNotes: ["Pink Pepper", "Orange Blossom", "Pear"], heartNotes: ["Coffee", "Jasmine", "Bitter Almond"], baseNotes: ["Vanilla", "Patchouli", "Cedar"],
                  moodTags: [.sensual, .bold, .mysterious],
                  colorAssociations: ColorPreset.dark() + ColorPreset.purple(0.7),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B00N5TSGI4", iconName: "moon.stars.fill", shortDescription: "Addictive coffee-vanilla with dark glamour",
                  bottleColor: "#1A0A2E", bottleShape: .modern),
        Fragrance(id: "w_libre", name: "Libre Eau de Parfum", house: "Yves Saint Laurent",
                  accords: [.floral, .oriental, .aromatic],
                  topNotes: ["Mandarin", "Lavender", "Black Currant"], heartNotes: ["Orange Blossom", "Jasmine"], baseNotes: ["Vanilla", "Cedar", "Musk"],
                  moodTags: [.bold, .confident, .elegant],
                  colorAssociations: ColorPreset.gold() + ColorPreset.purple(0.4),
                  seasonality: [.fall, .winter, .spring], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B07XVHXC6V", iconName: "flame", shortDescription: "Bold lavender-vanilla duality, modern freedom",
                  bottleColor: "#D4AF37", bottleShape: .modern),
        Fragrance(id: "w_good_girl", name: "Good Girl", house: "Carolina Herrera",
                  accords: [.oriental, .floral, .gourmand],
                  topNotes: ["Almond", "Coffee", "Bergamot"], heartNotes: ["Tuberose", "Jasmine", "Orange Blossom"], baseNotes: ["Cacao", "Tonka Bean", "Sandalwood"],
                  moodTags: [.sensual, .bold, .sophisticated],
                  colorAssociations: ColorPreset.dark() + ColorPreset.pink(0.6) + ColorPreset.gold(0.5),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B01LY04MRY", iconName: "star.fill", shortDescription: "Duality of light tuberose and dark cacao",
                  bottleColor: "#1A0A2E", bottleShape: .modern),
        Fragrance(id: "w_flowerbomb", name: "Flowerbomb", house: "Viktor & Rolf",
                  accords: [.floral, .oriental, .gourmand],
                  topNotes: ["Tea", "Bergamot"], heartNotes: ["Jasmine", "Rose", "Freesia", "Orchid"], baseNotes: ["Patchouli", "Musk", "Vanilla"],
                  moodTags: [.romantic, .opulent, .warm],
                  colorAssociations: ColorPreset.pink() + ColorPreset.warm(0.7),
                  seasonality: [.fall, .winter, .spring], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B0012RO626", iconName: "camera.macro", shortDescription: "Explosive floral bouquet with vanilla warmth",
                  bottleColor: "#FF69B4", bottleShape: .round),
        Fragrance(id: "w_la_vie_est_belle", name: "La Vie Est Belle", house: "Lancome",
                  accords: [.gourmand, .floral, .oriental],
                  topNotes: ["Black Currant", "Pear"], heartNotes: ["Iris", "Jasmine", "Orange Blossom"], baseNotes: ["Praline", "Vanilla", "Patchouli", "Tonka Bean"],
                  moodTags: [.romantic, .warm, .elegant],
                  colorAssociations: ColorPreset.pink() + ColorPreset.gold(0.7) + ColorPreset.warm(0.5),
                  seasonality: [.fall, .winter, .spring], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B009629YYA", iconName: "heart.fill", shortDescription: "Joyful iris-praline sweetness, a modern classic",
                  bottleColor: "#E8B4B8", bottleShape: .tall),
        Fragrance(id: "w_idole", name: "Idole", house: "Lancome",
                  accords: [.floral, .fresh, .musky],
                  topNotes: ["Bergamot", "Pink Pepper", "Pear"], heartNotes: ["Rose", "Jasmine", "Chypre Accord"], baseNotes: ["White Musk", "Cedarwood", "Cashmeran", "Vanilla"],
                  moodTags: [.elegant, .fresh, .confident],
                  colorAssociations: ColorPreset.pink() + ColorPreset.white(0.6),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "sparkle", shortDescription: "Clean rose-jasmine chypre for modern women",
                  bottleColor: "#F5E6CC", bottleShape: .tall),
        Fragrance(id: "w_si_edp", name: "Si Eau de Parfum", house: "Giorgio Armani",
                  accords: [.floral, .oriental, .woody],
                  topNotes: ["Black Currant", "Freesia"], heartNotes: ["Rose de Mai", "Osmanthus"], baseNotes: ["Vanilla", "Ambroxan", "Patchouli", "Woody Notes"],
                  moodTags: [.elegant, .sophisticated, .confident],
                  colorAssociations: ColorPreset.pink() + ColorPreset.warm(0.5),
                  seasonality: [.spring, .fall], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B00EVE5GGW", iconName: "s.circle.fill", shortDescription: "Chic blackcurrant-rose with vanilla depth",
                  bottleColor: "#D63384", bottleShape: .square),
        Fragrance(id: "w_my_way", name: "My Way", house: "Giorgio Armani",
                  accords: [.floral, .musky, .woody],
                  topNotes: ["Bergamot", "Orange Blossom"], heartNotes: ["Tuberose", "Indian Jasmine"], baseNotes: ["White Musk", "Cedarwood", "Vanilla"],
                  moodTags: [.elegant, .natural, .serene],
                  colorAssociations: ColorPreset.white() + ColorPreset.pink(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B08BCGJNWG", iconName: "globe", shortDescription: "Sustainable tuberose-jasmine with clean musk",
                  bottleColor: "#E6D5B8", bottleShape: .round),
        Fragrance(id: "w_cloud", name: "Cloud Eau de Parfum", house: "Ariana Grande",
                  accords: [.gourmand, .musky, .fruity],
                  topNotes: ["Lavender Blossom", "Juicy Pear", "Bergamot"], heartNotes: ["Coconut", "Praline", "Vanilla Orchid"], baseNotes: ["Creamy Musks", "Blonde Woods", "Cashmere"],
                  moodTags: [.playful, .cozy, .romantic],
                  colorAssociations: ColorPreset.pink(0.8) + ColorPreset.white(0.7) + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .budget, gender: .feminine,
                  amazonASIN: "B07GZD9VYX", iconName: "cloud.fill", shortDescription: "Dreamy coconut-praline wrapped in soft musk",
                  bottleColor: "#E6E6FA", bottleShape: .round),
        Fragrance(id: "w_god_is_a_woman", name: "God Is a Woman", house: "Ariana Grande",
                  accords: [.musky, .floral, .gourmand],
                  topNotes: ["Rose", "Ambrette"], heartNotes: ["Turkish Rose Petals", "Orris"], baseNotes: ["Cedarwood", "Ambroxan", "Cashmeran"],
                  moodTags: [.bold, .elegant, .confident],
                  colorAssociations: ColorPreset.purple() + ColorPreset.pink(0.5),
                  seasonality: [.spring, .fall], region: .western, priceTier: .budget, gender: .feminine,
                  amazonASIN: nil, iconName: "moon.fill", shortDescription: "Clean rose and musk with celestial confidence",
                  bottleColor: "#DDA0DD", bottleShape: .round),
        Fragrance(id: "w_gucci_bloom", name: "Gucci Bloom", house: "Gucci",
                  accords: [.floral, .green, .powdery],
                  topNotes: ["Rangoon Creeper"], heartNotes: ["Jasmine", "Tuberose"], baseNotes: ["Sandalwood", "Musk", "Orris"],
                  moodTags: [.natural, .romantic, .elegant],
                  colorAssociations: ColorPreset.pink() + ColorPreset.white(0.6),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B074P5WLH8", iconName: "leaf.fill", shortDescription: "Rich white floral garden with green depth",
                  bottleColor: "#FFC0CB", bottleShape: .square),
        Fragrance(id: "w_flora_gardenia", name: "Flora Gorgeous Gardenia", house: "Gucci",
                  accords: [.floral, .fruity, .gourmand],
                  topNotes: ["Pear Blossom", "Red Berries"], heartNotes: ["Gardenia", "Jasmine"], baseNotes: ["Brown Sugar", "Musk"],
                  moodTags: [.playful, .romantic, .warm],
                  colorAssociations: ColorPreset.pink() + ColorPreset.warm(0.4),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "camera.macro", shortDescription: "Sweet gardenia with brown sugar warmth",
                  bottleColor: "#FF85B3", bottleShape: .square),
        Fragrance(id: "w_daisy", name: "Daisy", house: "Marc Jacobs",
                  accords: [.floral, .fresh, .fruity],
                  topNotes: ["Strawberry", "Violet Leaves", "Ruby Red Grapefruit"], heartNotes: ["Gardenia", "Violet Petals", "Jasmine"], baseNotes: ["Musk", "Vanilla", "White Woods"],
                  moodTags: [.playful, .fresh, .natural],
                  colorAssociations: ColorPreset.white() + ColorPreset.bright(0.7) + ColorPreset.green(0.4),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B001BYHIM8", iconName: "sun.min.fill", shortDescription: "Innocent garden-fresh daisies and strawberries",
                  bottleColor: "#FFFACD", bottleShape: .round),
        Fragrance(id: "w_light_blue_w", name: "Light Blue", house: "Dolce & Gabbana",
                  accords: [.citrus, .fresh, .floral],
                  topNotes: ["Sicilian Lemon", "Apple", "Cedar"], heartNotes: ["Bamboo", "Jasmine", "White Rose"], baseNotes: ["Cedar", "Musk", "Amber"],
                  moodTags: [.fresh, .playful, .energetic],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.7) + ColorPreset.white(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B000LPHV0Q", iconName: "sun.max.fill", shortDescription: "Sparkling Sicilian lemon captures summer joy",
                  bottleColor: "#87CEEB", bottleShape: .square),
        Fragrance(id: "w_bright_crystal", name: "Bright Crystal", house: "Versace",
                  accords: [.floral, .fresh, .musky],
                  topNotes: ["Pomegranate", "Yuzu", "Frost Accord"], heartNotes: ["Peony", "Magnolia", "Lotus"], baseNotes: ["Musk", "Amber", "Mahogany"],
                  moodTags: [.elegant, .fresh, .romantic],
                  colorAssociations: ColorPreset.pink() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B001FEZCFQ", iconName: "sparkle", shortDescription: "Crystalline floral freshness with peony heart",
                  bottleColor: "#FFD1DC", bottleShape: .modern),
        Fragrance(id: "w_viva_la_juicy", name: "Viva La Juicy", house: "Juicy Couture",
                  accords: [.fruity, .floral, .gourmand],
                  topNotes: ["Wild Berries", "Mandarin"], heartNotes: ["Gardenia", "Honeysuckle", "Jasmine"], baseNotes: ["Caramel", "Vanilla", "Sandalwood", "Amber"],
                  moodTags: [.playful, .bold, .warm],
                  colorAssociations: ColorPreset.pink() + ColorPreset.gold(0.5),
                  seasonality: [.spring, .fall], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B001AO0Q20", iconName: "party.popper.fill", shortDescription: "Fruity party girl with caramel and berries",
                  bottleColor: "#FFB6C1", bottleShape: .round),
        Fragrance(id: "w_olympea", name: "Olympea", house: "Paco Rabanne",
                  accords: [.oriental, .floral, .aquatic],
                  topNotes: ["Green Mandarin", "Aquatic Notes"], heartNotes: ["Jasmine", "Salt", "Ginger Lily"], baseNotes: ["Cashmere Wood", "Amber", "Sandalwood", "Vanilla"],
                  moodTags: [.sensual, .elegant, .bold],
                  colorAssociations: ColorPreset.gold() + ColorPreset.cool(0.4),
                  seasonality: [.fall, .winter, .spring], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B01380AAWY", iconName: "crown.fill", shortDescription: "Salty-sweet goddess with amber cashmere",
                  bottleColor: "#C5B358", bottleShape: .modern),
        Fragrance(id: "w_lady_million", name: "Lady Million", house: "Paco Rabanne",
                  accords: [.floral, .woody, .fresh],
                  topNotes: ["Amalfi Lemon", "Raspberry"], heartNotes: ["Gardenia", "African Orange Flower", "Arabian Jasmine"], baseNotes: ["Patchouli", "Honey", "Amber"],
                  moodTags: [.bold, .confident, .opulent],
                  colorAssociations: ColorPreset.gold() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .fall], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B003TJ3MAO", iconName: "dollarsign.circle.fill", shortDescription: "Diamond-cut gardenia with honey-amber warmth",
                  bottleColor: "#FFD700", bottleShape: .modern),
        Fragrance(id: "w_prada_paradoxe", name: "Paradoxe", house: "Prada",
                  accords: [.floral, .oriental, .musky],
                  topNotes: ["Pear", "Bergamot"], heartNotes: ["Neroli", "Jasmine"], baseNotes: ["Amber", "Musk", "Vanilla"],
                  moodTags: [.elegant, .bold, .sophisticated],
                  colorAssociations: ColorPreset.gold() + ColorPreset.pink(0.4),
                  seasonality: [.fall, .winter, .spring], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "triangle.fill", shortDescription: "Shape-shifting amber-floral with pear opening",
                  bottleColor: "#E8D5B7", bottleShape: .modern),
        Fragrance(id: "w_burberry_her", name: "Burberry Her", house: "Burberry",
                  accords: [.fruity, .floral, .gourmand],
                  topNotes: ["Dark Berries", "Raspberry", "Blackberry", "Black Currant"], heartNotes: ["Jasmine", "Violet"], baseNotes: ["Musk", "Amber", "Dry Cocoa", "Cashmeran"],
                  moodTags: [.playful, .bold, .warm],
                  colorAssociations: ColorPreset.pink() + ColorPreset.warm(0.5),
                  seasonality: [.spring, .fall], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B07F21VHQF", iconName: "handbag.fill", shortDescription: "Berry cocktail with cocoa depth, very British",
                  bottleColor: "#FF6B6B", bottleShape: .square),
        Fragrance(id: "w_donna_roma", name: "Donna Born in Roma", house: "Valentino",
                  accords: [.floral, .gourmand, .oriental],
                  topNotes: ["Jasmine Grandiflorum"], heartNotes: ["Bourbon Vanilla", "Jasmine Sambac"], baseNotes: ["Cashmeran", "Woody Notes"],
                  moodTags: [.bold, .sensual, .opulent],
                  colorAssociations: ColorPreset.pink() + ColorPreset.gold(0.5),
                  seasonality: [.fall, .winter, .spring], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "building.columns.fill", shortDescription: "Couture jasmine-vanilla, Roman glamour",
                  bottleColor: "#FFB3BA", bottleShape: .modern),
        Fragrance(id: "w_alien", name: "Alien", house: "Mugler",
                  accords: [.oriental, .floral, .woody],
                  topNotes: ["Jasmine Sambac"], heartNotes: ["Cashmeran", "Amber"], baseNotes: ["White Amber", "Cedar", "Tonka Bean"],
                  moodTags: [.mysterious, .bold, .opulent],
                  colorAssociations: ColorPreset.purple() + ColorPreset.gold(0.5) + ColorPreset.dark(0.4),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B000E7Y3UM", iconName: "staroflife.fill", shortDescription: "Otherworldly solar jasmine-amber radiance",
                  bottleColor: "#6A0DAD", bottleShape: .flacon),
        Fragrance(id: "w_angel", name: "Angel", house: "Mugler",
                  accords: [.gourmand, .oriental, .floral],
                  topNotes: ["Helional", "Bergamot", "Coconut"], heartNotes: ["Honey", "Caramel", "Apricot"], baseNotes: ["Patchouli", "Chocolate", "Vanilla", "Tonka Bean"],
                  moodTags: [.bold, .opulent, .cozy],
                  colorAssociations: ColorPreset.purple() + ColorPreset.warm(0.5) + ColorPreset.gold(0.4),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B000C1V0MC", iconName: "star.fill", shortDescription: "Revolutionary patchouli-chocolate gourmand icon",
                  bottleColor: "#4B0082", bottleShape: .flacon),
        Fragrance(id: "w_linterdit", name: "L'Interdit", house: "Givenchy",
                  accords: [.floral, .oriental, .powdery],
                  topNotes: ["Pear", "Bergamot"], heartNotes: ["Orange Blossom", "Jasmine", "Tuberose"], baseNotes: ["Patchouli", "Vetiver", "Ambroxan"],
                  moodTags: [.bold, .elegant, .mysterious],
                  colorAssociations: ColorPreset.dark() + ColorPreset.white(0.5) + ColorPreset.pink(0.3),
                  seasonality: [.fall, .winter, .spring], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B07R2YCKJY", iconName: "lock.fill", shortDescription: "Forbidden white flowers over dark vetiver",
                  bottleColor: "#F5F5F5", bottleShape: .tall),
        Fragrance(id: "w_narciso_for_her", name: "For Her", house: "Narciso Rodriguez",
                  accords: [.musky, .floral, .oriental],
                  topNotes: ["Rose", "Peach"], heartNotes: ["Musk", "Amber", "Osmanthus"], baseNotes: ["Vanilla", "Patchouli", "Vetiver", "Sandalwood"],
                  moodTags: [.sensual, .elegant, .warm],
                  colorAssociations: ColorPreset.pink() + ColorPreset.neutral(0.5),
                  seasonality: [.spring, .fall, .winter], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: "B000QUHJ3C", iconName: "heart.fill", shortDescription: "Pure musk sensuality with rose and amber",
                  bottleColor: "#FFB6C1", bottleShape: .tall),
        Fragrance(id: "w_glossier_you", name: "Glossier You", house: "Glossier",
                  accords: [.musky, .woody, .floral],
                  topNotes: ["Pink Pepper", "Iris Root"], heartNotes: ["Ambrette", "Ambrox"], baseNotes: ["Musk", "Cedarwood", "Cashmeran"],
                  moodTags: [.minimal, .serene, .elegant],
                  colorAssociations: ColorPreset.neutral() + ColorPreset.pink(0.3),
                  seasonality: [.spring, .summer, .fall, .winter], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "drop.fill", shortDescription: "Your skin but better — warm pink pepper musk",
                  bottleColor: "#FFE4E1", bottleShape: .round),
        Fragrance(id: "w_la_panthere", name: "La Panthere", house: "Cartier",
                  accords: [.floral, .oriental, .musky],
                  topNotes: ["Gardenia"], heartNotes: ["Rose", "Peach"], baseNotes: ["Musk", "Oakmoss"],
                  moodTags: [.elegant, .sophisticated, .warm],
                  colorAssociations: ColorPreset.gold() + ColorPreset.pink(0.4),
                  seasonality: [.fall, .winter], region: .western, priceTier: .luxury, gender: .feminine,
                  amazonASIN: nil, iconName: "pawprint.fill", shortDescription: "Prowling gardenia with feline amber grace",
                  bottleColor: "#F4A460", bottleShape: .flacon),
        Fragrance(id: "w_coach_edp", name: "Coach Eau de Parfum", house: "Coach",
                  accords: [.floral, .fruity, .fresh],
                  topNotes: ["Raspberry", "Pear", "Pink Pepper"], heartNotes: ["Turkish Rose", "Gardenia"], baseNotes: ["Suede Musk", "Sandalwood", "Cashmeran"],
                  moodTags: [.playful, .warm, .confident],
                  colorAssociations: ColorPreset.pink() + ColorPreset.warm(0.4),
                  seasonality: [.spring, .fall], region: .western, priceTier: .mid, gender: .feminine,
                  amazonASIN: nil, iconName: "handbag.fill", shortDescription: "New York raspberry-rose with suede warmth",
                  bottleColor: "#F5C2C7", bottleShape: .tall),
        Fragrance(id: "w_amazing_grace", name: "Amazing Grace", house: "Philosophy",
                  accords: [.floral, .musky, .fresh],
                  topNotes: ["Bergamot", "Grapefruit"], heartNotes: ["Muguet Blossoms", "Rose"], baseNotes: ["Musk", "Blonde Woods"],
                  moodTags: [.serene, .elegant, .fresh],
                  colorAssociations: ColorPreset.white() + ColorPreset.pink(0.4),
                  seasonality: [.spring, .summer], region: .western, priceTier: .budget, gender: .feminine,
                  amazonASIN: "B000VA7H3Q", iconName: "sparkles", shortDescription: "Simple muguet-musk grace, clean and timeless",
                  bottleColor: "#FADADD", bottleShape: .tall),
        Fragrance(id: "w_bombshell", name: "Bombshell", house: "Victoria's Secret",
                  accords: [.fruity, .floral, .fresh],
                  topNotes: ["Purple Passion Fruit", "Shangri-La Peony", "Vanilla Orchid"], heartNotes: ["Peony", "Jasmine Petals"], baseNotes: ["Musk", "Woodsy Notes"],
                  moodTags: [.playful, .bold, .energetic],
                  colorAssociations: ColorPreset.pink() + ColorPreset.bright(0.6),
                  seasonality: [.spring, .summer], region: .western, priceTier: .budget, gender: .feminine,
                  amazonASIN: "B003IAY0IG", iconName: "bolt.fill", shortDescription: "Fruity-floral bombshell energy",
                  bottleColor: "#FF69B4", bottleShape: .tall),
        Fragrance(id: "w_pleasures", name: "Pleasures", house: "Estee Lauder",
                  accords: [.floral, .green, .fresh],
                  topNotes: ["Violet Leaves", "Green Notes"], heartNotes: ["Lilies", "Peony", "Rose"], baseNotes: ["Sandalwood", "Patchouli"],
                  moodTags: [.fresh, .romantic, .elegant],
                  colorAssociations: ColorPreset.green() + ColorPreset.pink(0.4),
                  seasonality: [.spring, .summer], region: .western, priceTier: .budget, gender: .feminine,
                  amazonASIN: "B000GHUXYW", iconName: "leaf.fill", shortDescription: "Sheer lilies and green freshness, timeless",
                  bottleColor: "#90EE90", bottleShape: .tall),
    ]

    // MARK: - Unisex / Niche (~40)

    static let unisexNiche: [Fragrance] = [
        Fragrance(id: "w_br540", name: "Baccarat Rouge 540", house: "Maison Francis Kurkdjian",
                  accords: [.oriental, .floral, .woody],
                  topNotes: ["Saffron", "Jasmine"], heartNotes: ["Amberwood", "Ambergris"], baseNotes: ["Fir Resin", "Cedar"],
                  moodTags: [.opulent, .mysterious, .elegant],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.6) + ColorPreset.pink(0.3),
                  seasonality: [.fall, .winter, .spring], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: "B06XKT12QN", iconName: "diamond.fill", shortDescription: "Luminous saffron-amber crystal, iconic niche",
                  bottleColor: "#D4A574", bottleShape: .flacon),
        Fragrance(id: "w_br540_extrait", name: "Baccarat Rouge 540 Extrait", house: "Maison Francis Kurkdjian",
                  accords: [.oriental, .woody, .musky],
                  topNotes: ["Bitter Almond", "Saffron"], heartNotes: ["Egyptian Jasmine", "Cedar"], baseNotes: ["Ambergris", "Fir Balsam"],
                  moodTags: [.opulent, .warm, .sensual],
                  colorAssociations: ColorPreset.gold() + ColorPreset.dark(0.5),
                  seasonality: [.fall, .winter], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "diamond.fill", shortDescription: "Concentrated amber-almond luxury, ultra-rich",
                  bottleColor: "#B8860B", bottleShape: .flacon),
        Fragrance(id: "w_grand_soir", name: "Grand Soir", house: "Maison Francis Kurkdjian",
                  accords: [.oriental, .woody, .gourmand],
                  topNotes: ["Labdanum Resin"], heartNotes: ["Amber Accord", "Benzoin"], baseNotes: ["Vanilla", "Tonka Bean", "Musk"],
                  moodTags: [.warm, .opulent, .cozy],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.7),
                  seasonality: [.fall, .winter], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "sparkles", shortDescription: "Pure liquid amber warmth for grand evenings",
                  bottleColor: "#B8860B", bottleShape: .flacon),
        Fragrance(id: "w_santal_33", name: "Santal 33", house: "Le Labo",
                  accords: [.woody, .aromatic, .leather],
                  topNotes: ["Violet", "Cardamom"], heartNotes: ["Iris", "Ambrox"], baseNotes: ["Australian Sandalwood", "Cedarwood", "Leather", "Musk"],
                  moodTags: [.sophisticated, .minimal, .warm],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.neutral(0.6),
                  seasonality: [.spring, .summer, .fall, .winter], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "leaf.fill", shortDescription: "Smoky sandalwood icon, the scent of NYC lofts",
                  bottleColor: "#D2B48C", bottleShape: .tall),
        Fragrance(id: "w_another_13", name: "Another 13", house: "Le Labo",
                  accords: [.musky, .woody, .fresh],
                  topNotes: ["Ambroxan"], heartNotes: ["Jasmine Petals", "Ambrette Seeds"], baseNotes: ["Moss", "Musk", "Woody Notes"],
                  moodTags: [.minimal, .mysterious, .cool],
                  colorAssociations: ColorPreset.neutral() + ColorPreset.cool(0.4),
                  seasonality: [.spring, .summer, .fall, .winter], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "atom", shortDescription: "Invisible second-skin ambroxan glow",
                  bottleColor: "#C0C0C0", bottleShape: .tall),
        Fragrance(id: "w_gypsy_water", name: "Gypsy Water", house: "Byredo",
                  accords: [.woody, .aromatic, .fresh],
                  topNotes: ["Bergamot", "Lemon", "Pepper"], heartNotes: ["Incense", "Pine Needles", "Orris"], baseNotes: ["Vanilla", "Sandalwood", "Amber"],
                  moodTags: [.natural, .mysterious, .warm],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.green(0.4) + ColorPreset.warm(0.3),
                  seasonality: [.spring, .fall], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "tent.fill", shortDescription: "Bohemian incense and vanilla campfire spirit",
                  bottleColor: "#DEB887", bottleShape: .tall),
        Fragrance(id: "w_bal_dafrique", name: "Bal d'Afrique", house: "Byredo",
                  accords: [.woody, .floral, .musky],
                  topNotes: ["African Marigold", "Bucchu", "Bergamot", "Lemon"], heartNotes: ["Violet", "Jasmine Petals", "Cyclamen"], baseNotes: ["Vetiver", "Amber", "Musk"],
                  moodTags: [.bold, .natural, .warm],
                  colorAssociations: ColorPreset.gold() + ColorPreset.green(0.4),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "sun.max.fill", shortDescription: "African marigold and vetiver dance, joyful warmth",
                  bottleColor: "#DAA520", bottleShape: .tall),
        Fragrance(id: "w_mojave_ghost", name: "Mojave Ghost", house: "Byredo",
                  accords: [.woody, .musky, .floral],
                  topNotes: ["Ambrette", "Jamaican Nesberry"], heartNotes: ["Violet", "Sandalwood", "Magnolia"], baseNotes: ["Cedarwood", "Amber", "Musk"],
                  moodTags: [.serene, .mysterious, .warm],
                  colorAssociations: ColorPreset.neutral() + ColorPreset.warm(0.4),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "sun.haze.fill", shortDescription: "Desert ghost: sandalwood and violet in dry heat",
                  bottleColor: "#F5DEB3", bottleShape: .tall),
        Fragrance(id: "w_lost_cherry", name: "Lost Cherry", house: "Tom Ford",
                  accords: [.fruity, .gourmand, .oriental],
                  topNotes: ["Black Cherry", "Cherry Liqueur"], heartNotes: ["Bitter Almond", "Cherry Syrup", "Turkish Rose"], baseNotes: ["Peru Balsam", "Tonka Bean", "Sandalwood", "Vetiver", "Cedar"],
                  moodTags: [.sensual, .playful, .opulent],
                  colorAssociations: ColorPreset.warm() + ColorPreset.pink(0.6) + ColorPreset.dark(0.4),
                  seasonality: [.fall, .winter], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "cherry.fill", shortDescription: "Decadent cherry liqueur with almond and rose",
                  bottleColor: "#8B0000", bottleShape: .square),
        Fragrance(id: "w_black_orchid", name: "Black Orchid", house: "Tom Ford",
                  accords: [.oriental, .floral, .gourmand],
                  topNotes: ["Truffle", "Bergamot", "Black Currant"], heartNotes: ["Black Orchid", "Lotus Wood", "Spicy Notes"], baseNotes: ["Patchouli", "Vanilla", "Vetiver", "Dark Chocolate"],
                  moodTags: [.mysterious, .opulent, .sensual],
                  colorAssociations: ColorPreset.dark() + ColorPreset.purple(0.5),
                  seasonality: [.fall, .winter], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: "B000GHUE1Q", iconName: "camera.macro", shortDescription: "Dark luxurious orchid with truffle and chocolate",
                  bottleColor: "#1A0A2E", bottleShape: .square),
        Fragrance(id: "w_molecule01", name: "Molecule 01", house: "Escentric Molecules",
                  accords: [.musky, .woody, .fresh],
                  topNotes: ["Iso E Super"], heartNotes: ["Iso E Super"], baseNotes: ["Iso E Super"],
                  moodTags: [.minimal, .mysterious, .serene],
                  colorAssociations: ColorPreset.neutral() + ColorPreset.white(0.7),
                  seasonality: [.spring, .summer, .fall, .winter], region: .western, priceTier: .mid, gender: .unisex,
                  amazonASIN: "B004FGWDDE", iconName: "atom", shortDescription: "Invisible velvety aura, a singular molecule",
                  bottleColor: "#D3D3D3", bottleShape: .tall),
        Fragrance(id: "w_angels_share", name: "Angels' Share", house: "By Kilian",
                  accords: [.oriental, .gourmand, .woody],
                  topNotes: ["Cognac", "Cinnamon"], heartNotes: ["Praline", "Oak", "Tonka Bean"], baseNotes: ["Vanilla", "Sandalwood", "Musk"],
                  moodTags: [.opulent, .warm, .cozy],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.7) + ColorPreset.earthy(0.4),
                  seasonality: [.fall, .winter], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "wineglass.fill", shortDescription: "Cognac-vanilla warmth aging in oak barrels",
                  bottleColor: "#8B4513", bottleShape: .flacon),
        Fragrance(id: "w_love_dont_be_shy", name: "Love, Don't Be Shy", house: "By Kilian",
                  accords: [.gourmand, .floral, .oriental],
                  topNotes: ["Neroli", "Pink Pepper"], heartNotes: ["Orange Blossom", "Honeysuckle", "Iris"], baseNotes: ["Marshmallow", "Vanilla", "Sugar", "Musk", "Caramel"],
                  moodTags: [.romantic, .playful, .warm],
                  colorAssociations: ColorPreset.pink() + ColorPreset.gold(0.5),
                  seasonality: [.spring, .fall, .winter], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "heart.fill", shortDescription: "Marshmallow-neroli sweetness with honeyed warmth",
                  bottleColor: "#FFB6C1", bottleShape: .flacon),
        Fragrance(id: "w_not_a_perfume", name: "Not a Perfume", house: "Juliette Has a Gun",
                  accords: [.musky, .woody],
                  topNotes: ["Ambroxan"], heartNotes: ["Ambroxan"], baseNotes: ["Ambroxan"],
                  moodTags: [.minimal, .cool, .serene],
                  colorAssociations: ColorPreset.neutral() + ColorPreset.white(0.6),
                  seasonality: [.spring, .summer, .fall, .winter], region: .western, priceTier: .mid, gender: .unisex,
                  amazonASIN: nil, iconName: "nosign", shortDescription: "Single-molecule minimalism, clean and modern",
                  bottleColor: "#F5F5DC", bottleShape: .tall),
        Fragrance(id: "w_by_the_fireplace", name: "By the Fireplace", house: "Maison Margiela",
                  accords: [.woody, .gourmand, .spicy],
                  topNotes: ["Clove Oil", "Pink Pepper", "Orange Flower Petals"], heartNotes: ["Chestnut Accord", "Guaiac Wood"], baseNotes: ["Vanilla", "Peru Balsam", "Cashmeran"],
                  moodTags: [.cozy, .warm, .natural],
                  colorAssociations: ColorPreset.warm() + ColorPreset.earthy(0.6),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .unisex,
                  amazonASIN: nil, iconName: "flame.fill", shortDescription: "Smoked chestnuts by a crackling autumn fire",
                  bottleColor: "#A0522D", bottleShape: .tall),
        Fragrance(id: "w_jazz_club", name: "Jazz Club", house: "Maison Margiela",
                  accords: [.oriental, .woody, .aromatic],
                  topNotes: ["Pink Pepper", "Lemon", "Neroli Oil"], heartNotes: ["Rum Absolute", "Clary Sage Oil", "Java Vetiver Oil"], baseNotes: ["Tobacco Leaf", "Vanilla Bean", "Tonka Bean", "Styrax Resin"],
                  moodTags: [.sophisticated, .warm, .bold],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.dark(0.5) + ColorPreset.warm(0.4),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .unisex,
                  amazonASIN: nil, iconName: "music.note", shortDescription: "Smoky jazz lounge: rum, tobacco, and leather",
                  bottleColor: "#4A3728", bottleShape: .tall),
        Fragrance(id: "w_lazy_sunday", name: "Lazy Sunday Morning", house: "Maison Margiela",
                  accords: [.floral, .musky, .powdery],
                  topNotes: ["Pear", "Lily of the Valley", "Aldehydes"], heartNotes: ["Iris", "Rose", "Orange Blossom"], baseNotes: ["White Musk", "Woods", "Ambroxan"],
                  moodTags: [.serene, .fresh, .romantic],
                  colorAssociations: ColorPreset.white() + ColorPreset.pink(0.3),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .unisex,
                  amazonASIN: nil, iconName: "bed.double.fill", shortDescription: "Clean linen and lily Sunday morning bliss",
                  bottleColor: "#FFFAF0", bottleShape: .tall),
        Fragrance(id: "w_coffee_break", name: "Coffee Break", house: "Maison Margiela",
                  accords: [.gourmand, .oriental, .aromatic],
                  topNotes: ["Coffee", "Pepper"], heartNotes: ["Lavender", "Milk Mousse"], baseNotes: ["Vanilla", "Cedar"],
                  moodTags: [.cozy, .warm, .playful],
                  colorAssociations: ColorPreset.earthy() + ColorPreset.warm(0.6),
                  seasonality: [.fall, .winter], region: .western, priceTier: .mid, gender: .unisex,
                  amazonASIN: nil, iconName: "mug.fill", shortDescription: "Steamy lavender latte on a cold morning",
                  bottleColor: "#6F4E37", bottleShape: .tall),
        Fragrance(id: "w_bubble_bath", name: "Bubble Bath", house: "Maison Margiela",
                  accords: [.musky, .floral, .powdery],
                  topNotes: ["Rose Pepper", "Coconut Milk"], heartNotes: ["Soap Accord", "Rose Super Essence", "Jasmine"], baseNotes: ["Musk", "Tonka Bean", "Cedarwood"],
                  moodTags: [.serene, .playful, .fresh],
                  colorAssociations: ColorPreset.white() + ColorPreset.pink(0.3) + ColorPreset.cool(0.2),
                  seasonality: [.spring, .summer], region: .western, priceTier: .mid, gender: .unisex,
                  amazonASIN: nil, iconName: "bathtub.fill", shortDescription: "Clean soapy rose musk, fresh from the bath",
                  bottleColor: "#F0F8FF", bottleShape: .tall),
        Fragrance(id: "w_delina", name: "Delina", house: "Parfums de Marly",
                  accords: [.floral, .fruity, .musky],
                  topNotes: ["Lychee", "Rhubarb", "Bergamot", "Nutmeg"], heartNotes: ["Turkish Rose", "Peony", "Vanilla"], baseNotes: ["Cashmeran", "Musk", "Cedarwood", "Incense"],
                  moodTags: [.romantic, .elegant, .playful],
                  colorAssociations: ColorPreset.pink() + ColorPreset.white(0.5),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .luxury, gender: .feminine,
                  amazonASIN: nil, iconName: "heart.circle.fill", shortDescription: "Royal lychee-rose with vanilla-musk elegance",
                  bottleColor: "#FFB6C1", bottleShape: .flacon),
        Fragrance(id: "w_herod", name: "Herod", house: "Parfums de Marly",
                  accords: [.oriental, .woody, .spicy],
                  topNotes: ["Cinnamon", "Pepper", "Iso E Super"], heartNotes: ["Turkish Rose", "Incense", "Osmanthus"], baseNotes: ["Vanilla", "Tobacco", "Oud", "Cypriol", "Musk", "Cedarwood"],
                  moodTags: [.opulent, .warm, .bold],
                  colorAssociations: ColorPreset.dark() + ColorPreset.warm(0.6) + ColorPreset.gold(0.4),
                  seasonality: [.fall, .winter], region: .western, priceTier: .luxury, gender: .masculine,
                  amazonASIN: nil, iconName: "shield.fill", shortDescription: "Tobacco-vanilla royalty with cinnamon warmth",
                  bottleColor: "#800020", bottleShape: .flacon),
        Fragrance(id: "w_reflection_man", name: "Reflection Man", house: "Amouage",
                  accords: [.floral, .woody, .fresh],
                  topNotes: ["Rosemary", "Pink Pepper", "Neroli"], heartNotes: ["Jasmine", "Orris", "Rose"], baseNotes: ["Sandalwood", "Cedar", "Vetiver", "Musk"],
                  moodTags: [.elegant, .sophisticated, .serene],
                  colorAssociations: ColorPreset.cool() + ColorPreset.white(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .luxury, gender: .masculine,
                  amazonASIN: nil, iconName: "person.crop.artframe", shortDescription: "Regal jasmine-sandalwood, Omani masterpiece",
                  bottleColor: "#E6E6FA", bottleShape: .flacon),
        Fragrance(id: "w_erba_pura", name: "Erba Pura", house: "Xerjoff",
                  accords: [.fruity, .oriental, .musky],
                  topNotes: ["Orange", "Lemon", "Bergamot"], heartNotes: ["Fruits"], baseNotes: ["Amber", "Vanilla", "White Musk"],
                  moodTags: [.playful, .bold, .warm],
                  colorAssociations: ColorPreset.warm() + ColorPreset.bright(0.6),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "sparkles", shortDescription: "Explosive fruity-amber Mediterranean sunshine",
                  bottleColor: "#FF8C00", bottleShape: .flacon),
        Fragrance(id: "w_hacivat", name: "Hacivat", house: "Nishane",
                  accords: [.fruity, .woody, .fresh],
                  topNotes: ["Pineapple", "Bergamot", "Grapefruit"], heartNotes: ["Jasmine", "Rose", "Patchouli"], baseNotes: ["Oak Moss", "Sandalwood", "Cedarwood", "Musk"],
                  moodTags: [.bold, .fresh, .confident],
                  colorAssociations: ColorPreset.green() + ColorPreset.cool(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "leaf.fill", shortDescription: "Aventus-inspired pineapple-moss freshness, Turkish niche",
                  bottleColor: "#2E8B57", bottleShape: .flacon),
        Fragrance(id: "w_side_effect", name: "Side Effect", house: "Initio",
                  accords: [.oriental, .gourmand, .spicy],
                  topNotes: ["Rum", "Cinnamon", "Dark Chocolate"], heartNotes: ["Tobacco", "Vanilla"], baseNotes: ["Benzoin", "Cashmeran", "Musk", "Hedione"],
                  moodTags: [.bold, .warm, .sensual],
                  colorAssociations: ColorPreset.dark() + ColorPreset.warm(0.7),
                  seasonality: [.fall, .winter], region: .western, priceTier: .luxury, gender: .unisex,
                  amazonASIN: nil, iconName: "wineglass.fill", shortDescription: "Dark rum and tobacco intoxication",
                  bottleColor: "#2C1810", bottleShape: .square),
    ]

    // MARK: - Budget Picks (~30)

    static let budgetPicks: [Fragrance] = [
        Fragrance(id: "w_club_de_nuit", name: "Club de Nuit Intense Man", house: "Armaf",
                  accords: [.fruity, .woody, .fresh],
                  topNotes: ["Lemon", "Pineapple", "Bergamot", "Apple", "Black Currant"], heartNotes: ["Rose", "Birch", "Jasmine"], baseNotes: ["Musk", "Ambergris", "Patchouli", "Vanilla"],
                  moodTags: [.confident, .bold, .fresh],
                  colorAssociations: ColorPreset.dark() + ColorPreset.cool(0.5),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .budget, gender: .masculine,
                  amazonASIN: "B01LZRUMAQ", iconName: "crown", shortDescription: "Legendary Aventus-inspired value powerhouse",
                  bottleColor: "#1C1C1C", bottleShape: .square),
        Fragrance(id: "w_nautica_voyage", name: "Nautica Voyage", house: "Nautica",
                  accords: [.aquatic, .fresh, .green],
                  topNotes: ["Green Leaf", "Apple"], heartNotes: ["Mimosa", "Lotus", "Marine Notes"], baseNotes: ["Cedarwood", "Musk", "Amber", "Moss"],
                  moodTags: [.fresh, .natural, .energetic],
                  colorAssociations: ColorPreset.cool() + ColorPreset.green(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .budget, gender: .masculine,
                  amazonASIN: "B000ECIMDQ", iconName: "sailboat.fill", shortDescription: "Timeless ocean freshness under $20, incredible value",
                  bottleColor: "#4682B4", bottleShape: .modern),
        Fragrance(id: "w_cool_water", name: "Cool Water", house: "Davidoff",
                  accords: [.aquatic, .aromatic, .fresh],
                  topNotes: ["Sea Water", "Lavender", "Mint", "Coriander", "Rosemary"], heartNotes: ["Sandalwood", "Neroli", "Jasmine", "Geranium"], baseNotes: ["Musk", "Cedar", "Amber", "Tobacco"],
                  moodTags: [.fresh, .cool, .natural],
                  colorAssociations: ColorPreset.cool() + ColorPreset.green(0.4),
                  seasonality: [.spring, .summer], region: .western, priceTier: .budget, gender: .masculine,
                  amazonASIN: "B000C1V0L0", iconName: "water.waves", shortDescription: "The original aquatic legend since 1988",
                  bottleColor: "#008B8B", bottleShape: .tall),
        Fragrance(id: "w_ck_one", name: "CK One", house: "Calvin Klein",
                  accords: [.citrus, .fresh, .green],
                  topNotes: ["Pineapple", "Mandarin", "Papaya", "Bergamot", "Cardamom", "Lemon"], heartNotes: ["Nutmeg", "Violet", "Rose", "Lily of the Valley", "Jasmine"], baseNotes: ["Musk", "Cedar", "Sandalwood", "Amber", "Green Tea"],
                  moodTags: [.fresh, .playful, .minimal],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .budget, gender: .unisex,
                  amazonASIN: "B000E7Y420", iconName: "1.circle.fill", shortDescription: "The original unisex icon, clean citrus energy",
                  bottleColor: "#E0E0E0", bottleShape: .tall),
        Fragrance(id: "w_ck_eternity", name: "Eternity for Men", house: "Calvin Klein",
                  accords: [.aromatic, .green, .fresh],
                  topNotes: ["Lavender", "Mandarin", "Green Notes"], heartNotes: ["Jasmine", "Sage", "Basil", "Geranium"], baseNotes: ["Sandalwood", "Vetiver", "Amber", "Musk"],
                  moodTags: [.elegant, .fresh, .romantic],
                  colorAssociations: ColorPreset.green() + ColorPreset.cool(0.4),
                  seasonality: [.spring, .summer], region: .western, priceTier: .budget, gender: .masculine,
                  amazonASIN: "B000E7Y3FK", iconName: "infinity", shortDescription: "Romantic lavender fougere, timeless classic",
                  bottleColor: "#B0C4DE", bottleShape: .tall),
        Fragrance(id: "w_leau_dissey", name: "L'Eau d'Issey Pour Homme", house: "Issey Miyake",
                  accords: [.aquatic, .citrus, .woody],
                  topNotes: ["Yuzu", "Cypress", "Mandarin", "Bergamot"], heartNotes: ["Water Lily", "Calone", "Nutmeg"], baseNotes: ["Vetiver", "Sandalwood", "Musk", "Amber"],
                  moodTags: [.fresh, .serene, .minimal],
                  colorAssociations: ColorPreset.cool() + ColorPreset.white(0.7) + ColorPreset.green(0.3),
                  seasonality: [.spring, .summer], region: .western, priceTier: .budget, gender: .masculine,
                  amazonASIN: "B000E7WMUI", iconName: "drop.fill", shortDescription: "Zen-like yuzu and water, Japanese-French minimalism",
                  bottleColor: "#C0C0C0", bottleShape: .modern),
        Fragrance(id: "w_chrome", name: "Chrome", house: "Azzaro",
                  accords: [.citrus, .aquatic, .woody],
                  topNotes: ["Lemon", "Neroli", "Rosemary"], heartNotes: ["Cyclamen", "Pineapple", "Jasmine"], baseNotes: ["Musk", "Cedar", "Tonka Bean", "Oak Moss", "Brazilian Rosewood"],
                  moodTags: [.fresh, .energetic, .natural],
                  colorAssociations: ColorPreset.cool() + ColorPreset.neutral(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .budget, gender: .masculine,
                  amazonASIN: "B000E7WMVU", iconName: "circle.fill", shortDescription: "Bright citrus-musk at an incredible price",
                  bottleColor: "#C0C0C0", bottleShape: .round),
        Fragrance(id: "w_joop_homme", name: "Joop! Homme", house: "Joop!",
                  accords: [.oriental, .floral, .aromatic],
                  topNotes: ["Orange Blossom", "Bergamot"], heartNotes: ["Cinnamon", "Jasmine", "Heliotrope"], baseNotes: ["Sandalwood", "Tonka Bean", "Vanilla"],
                  moodTags: [.bold, .sensual, .warm],
                  colorAssociations: ColorPreset.pink() + ColorPreset.warm(0.7) + ColorPreset.dark(0.5),
                  seasonality: [.fall, .winter], region: .western, priceTier: .budget, gender: .masculine,
                  amazonASIN: "B000C1V2W2", iconName: "flame", shortDescription: "Intense cinnamon-vanilla in an iconic pink bottle",
                  bottleColor: "#FF69B4", bottleShape: .tall),
        Fragrance(id: "w_khamrah", name: "Khamrah", house: "Lattafa",
                  accords: [.oriental, .gourmand, .spicy],
                  topNotes: ["Cinnamon", "Nutmeg", "Bergamot"], heartNotes: ["Dates", "Praline", "Turkish Rose"], baseNotes: ["Vanilla", "Tonka Bean", "Amber", "Benzoin", "Musk"],
                  moodTags: [.opulent, .warm, .bold],
                  colorAssociations: ColorPreset.gold() + ColorPreset.warm(0.7) + ColorPreset.dark(0.5),
                  seasonality: [.fall, .winter], region: .western, priceTier: .budget, gender: .unisex,
                  amazonASIN: "B0B8SH3H6B", iconName: "flame.fill", shortDescription: "Arabian date-vanilla luxury at budget price",
                  bottleColor: "#8B4513", bottleShape: .flacon),
        Fragrance(id: "w_afnan_9pm", name: "9PM", house: "Afnan",
                  accords: [.oriental, .gourmand, .aromatic],
                  topNotes: ["Cinnamon", "Apple", "Lavender"], heartNotes: ["Orange Blossom", "Rose"], baseNotes: ["Vanilla", "Tonka Bean", "Amber"],
                  moodTags: [.bold, .warm, .playful],
                  colorAssociations: ColorPreset.purple() + ColorPreset.dark(0.5),
                  seasonality: [.fall, .winter], region: .western, priceTier: .budget, gender: .masculine,
                  amazonASIN: "B09FYKKMMB", iconName: "clock.fill", shortDescription: "Sweet apple-vanilla nightlife for under $30",
                  bottleColor: "#4B0082", bottleShape: .round),
        Fragrance(id: "w_rasasi_hawas", name: "Hawas", house: "Rasasi",
                  accords: [.aquatic, .fresh, .woody],
                  topNotes: ["Bergamot", "Apple", "Cinnamon"], heartNotes: ["Marine Accord", "Violet Leaf"], baseNotes: ["Ambergris", "Musk", "Cashmeran"],
                  moodTags: [.energetic, .fresh, .bold],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .budget, gender: .masculine,
                  amazonASIN: "B01E48RLPK", iconName: "water.waves", shortDescription: "Arabian aquatic beast mode at budget price",
                  bottleColor: "#0077BE", bottleShape: .modern),
        Fragrance(id: "w_clinique_happy", name: "Clinique Happy", house: "Clinique",
                  accords: [.citrus, .floral, .fresh],
                  topNotes: ["Blood Grapefruit", "Mandarin", "Bergamot"], heartNotes: ["Orchid", "Freesia", "Lily of the Valley"], baseNotes: ["Amber", "Musk", "Magnolia"],
                  moodTags: [.energetic, .playful, .fresh],
                  colorAssociations: ColorPreset.bright() + ColorPreset.warm(0.4),
                  seasonality: [.spring, .summer], region: .western, priceTier: .budget, gender: .feminine,
                  amazonASIN: "B00008OIUE", iconName: "sun.max.fill", shortDescription: "Instant happiness in a bottle, citrus burst",
                  bottleColor: "#FFA500", bottleShape: .tall),
        Fragrance(id: "w_tommy", name: "Tommy", house: "Tommy Hilfiger",
                  accords: [.aromatic, .citrus, .fresh],
                  topNotes: ["Apple", "Cranberry", "Lavender", "Mint", "Grapefruit", "Bergamot"], heartNotes: ["Rose", "Ginger", "Cotton Blossom", "Cinnamon"], baseNotes: ["Cedar", "Sandalwood", "Amber", "Musk"],
                  moodTags: [.fresh, .playful, .natural],
                  colorAssociations: ColorPreset.cool() + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer], region: .western, priceTier: .budget, gender: .masculine,
                  amazonASIN: "B0009OAGL0", iconName: "tshirt.fill", shortDescription: "American prep classic: apple, mint, and cotton",
                  bottleColor: "#4169E1", bottleShape: .tall),
        Fragrance(id: "w_fantasy", name: "Fantasy", house: "Britney Spears",
                  accords: [.fruity, .gourmand, .floral],
                  topNotes: ["Red Lychee", "Kiwi", "Quince"], heartNotes: ["Jasmine", "White Chocolate Orchid", "Cupcake Accord"], baseNotes: ["Musk", "Orris Root", "Sandalwood"],
                  moodTags: [.playful, .warm, .romantic],
                  colorAssociations: ColorPreset.pink() + ColorPreset.purple(0.4),
                  seasonality: [.spring, .fall], region: .western, priceTier: .budget, gender: .feminine,
                  amazonASIN: "B000C1Y7OK", iconName: "wand.and.stars", shortDescription: "Fun pink lychee-cupcake sweetness, iconic budget",
                  bottleColor: "#FF1493", bottleShape: .round),
        Fragrance(id: "w_english_pear", name: "English Pear & Freesia", house: "Jo Malone",
                  accords: [.fruity, .floral, .fresh],
                  topNotes: ["King William Pear", "Melon"], heartNotes: ["Freesia"], baseNotes: ["Patchouli", "Amber", "Musk"],
                  moodTags: [.elegant, .fresh, .playful],
                  colorAssociations: ColorPreset.green() + ColorPreset.white(0.7) + ColorPreset.bright(0.5),
                  seasonality: [.spring, .summer, .fall], region: .western, priceTier: .luxury, gender: .feminine,
                  amazonASIN: "B005DM426K", iconName: "leaf.arrow.triangle.circlepath", shortDescription: "Crisp, dewy pear with delicate freesia",
                  bottleColor: "#F5DEB3", bottleShape: .tall),
    ]
}
